### ISSUE TITLE
[Feature]: Does it now support Nuxt3?

### ISSUE THREAD

**Issue by evanlong-me** [radix-vue/shadcn-vue#10]
### Describe the feature

Nuxt3 module is provided.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
This still is super early dev... and the way it will works doesn't required Nuxt3 module. 😁

**Comment by evanlong-me** [comment]
Then how do I use [shacn-vue](https://github.com/radix-vue/shadcn-vue) in Nuxt3?

**Comment by evanlong-me** [comment]
I can't wait to use it 🤗

**Comment by madebyfabian** [comment]
@evanlong0926 check out how to use vue plugins in nuxt: https://nuxt.com/docs/guide/directory-structure/plugins#vue-plugins

**Comment by evanlong-me** [comment]
> @evanlong0926 check out how to use vue plugins in nuxt: https://nuxt.com/docs/guide/directory-structure/plugins#vue-plugins

[shadcn-vue](https://github.com/radix-vue/shadcn-vue) Is a Vue plugin for Nuxt3?

**Comment by zernonia** [comment]
@evanlong0926  please have a look on the concept of [shadcn](https://ui.shadcn.com/docs).

Essentially `shadcn-vue` is just a collections of reusable components, which you can copy and paste into Nuxt, which is support by default thanks to `radix-vue` Nuxt modules.

**Comment by madebyfabian** [comment]
@zernonia is Right, sorry for my false response. Thought you meant something else.

**Comment by evanlong-me** [comment]
> @evanlong0926 please have a look on the concept of [shadcn](https://ui.shadcn.com/docs).
> 
> Essentially `shadcn-vue` is just a collections of reusable components, which you can copy and paste into Nuxt, which is support by default thanks to `radix-vue` Nuxt modules.

Maybe this needs a documentation lol.

However, some parts may not be supported, such as the form component, etc., because it integrates ` react-hook-form`. Perhaps `shadcn-vue` needs independence.

**Comment by zernonia** [comment]
Please be patient @evanlong0926 . We are working hard on it.. and will announce it when it is ready ya

**Comment by orenmizr** [comment]
what is currently the preferred way to make it work with nuxt ? just running the cli ?

**Comment by miztizm** [comment]
> Please be patient @evanlong0926 . We are working hard on it.. and will announce it when it is ready ya

its ready?

**Comment by miztizm** [comment]
its ready? its ready? its ready? its ready?
