### ISSUE TITLE
[Bug]: Toggle widget does not have proper background

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#102]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

None

### Steps to reproduce

When using <Toggle variant="outline"> the background is transparent instead of being bg-background like on the other widgets (like <Button variant="outline">)

I assumed they should be similar, no?

### Describe the bug

It should be similar to the appearance of Button or Dropdown etc

**Comment by zernonia** [comment]
@maelp can you provide some code, or maybe a screenshot to the issue above? 😁

**Comment by maelp** [comment]
I'm just adding a `<Toggle>` on some non "bg-background" background and it is transparent

You can see the issue here: https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/toggle/index.ts#L10

Compare for instance with the default class for Button: https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/button/index.ts#L10

**Comment by zernonia** [comment]
Seems like it was designed as such. from [shadcn/ui](https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/toggle.tsx#L14).

I believe you can apply your own desired class right?

**Comment by maelp** [comment]
okay interesting, yes in my version of the Toggle I'm using the same classes as Button for consistency
