### ISSUE TITLE
[Feature]: Add CodeSandbox for easy reproduction

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#103]
### Describe the feature

Let's implement the same Codesandbox feature like [Radix Vue](https://www.radix-vue.com/components/accordion.html) in `ComponentPreview.vue`.

Reference for the code:
https://github.com/radix-vue/radix-vue/blob/a066730bf659d3a871fb50eb213e71d43ffb9c0b/docs/codeeditor/index.ts

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
@sadeghbarati  could you help with this? I believe with this implemented we allow devs to recreate minimal reproduction much easily, and easy for us to trace the issue immediately.

**Comment by sadeghbarati** [comment]
Sure, will check it 🙌

**Comment by zernonia** [comment]
Hey @sadeghbarati ! not sure if you have started working on this? I have some code ready for this 😁

**Comment by sadeghbarati** [comment]
Yeah, I did some things but your work should be prioritized 😄

**Comment by zernonia** [comment]
I realized there's some complications as `Demo` components required some `Base` component.. thus not so simple 😂
