### ISSUE TITLE
[Suggestion]: Invert the TableHead and TableHeader components

### ISSUE THREAD

**Issue by leogallot** [radix-vue/shadcn-vue#110]
Hello,

It seems that the `TableHead` component renders a `<th>` element and the `TableHeader` component renders a `<thead>` element.

If we refer to wording used on these pages ([thead](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead), [th](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th)), I wonder if it wouldn't make slightly more sense to have them inverted?

**Comment by sadeghbarati** [comment]
Hi 👋 

It seems okay based on shadcn-ui source 👇 

[`TableHeader` is pointed to `<thead>`](https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/new-york/ui/table.tsx#L19C1-L25C40)

[`TableHead` is pointed to `<th>`](https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/new-york/ui/table.tsx#L66C1-L79C36)

**Comment by leogallot** [comment]
I see, let's keep it synchronised with the original lib then 👍
