### ISSUE TITLE
[Bug]: Combobox inside Sheet not stable

### ISSUE THREAD

**Issue by CharlesOnAir** [radix-vue/shadcn-vue#112]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

no necessary

### Steps to reproduce

Use the Combobox in the content of a sheet

### Describe the bug

If we add an event to the Combobox content: @update:open="editUserModal = false" the combobox will close when we interact with the drop-down menu of the sheet.

**Comment by zernonia** [comment]
@CharlesOnAir  can you provide a minimal reproduction? 😁
