### ISSUE TITLE
[Bug]: Pagination param not working

### ISSUE THREAD

**Issue by CharlesOnAir** [radix-vue/shadcn-vue#113]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

no necessary

### Steps to reproduce

All you have to do is change the "total" parameter of the paging module, and you can see the malfunction. No matter how many we add, the number of pages does not increase or decrease.

### Describe the bug

All you have to do is change the "total" parameter of the paging module, and you can see the malfunction. No matter how many we add, the number of pages does not increase or decrease.

**Comment by zernonia** [comment]
Not reproducible. Please provide minimal reproduction

**Comment by CiobanuAlexandruAndrei** [comment]
I had the same problem if I put inside :total="5" I will get just 1 page but if you do 50 it will display 5 pages:
```
<Pagination class=" w-full" v-slot="{ page }" :total="totalPages * 10" :sibling-count="3" show-edges :default-page="1">
                        <PaginationList v-slot="{ items }" class="flex items-center gap-1 w-full" >
                        <PaginationFirst />
                        <PaginationPrev />
```

**Comment by cugu** [comment]
There is a `:itemsPerPage="10"` parameter, which seems to be 10 per default. 
This parameter is not directly documented on https://www.shadcn-vue.com/docs/components/pagination.html
