### ISSUE TITLE
[Feature]: (Minor improvement)

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#115]
### Describe the feature

In vue 3.3 you can destructure props and set defaults without using withDefaults, it's both more elegant and easier to maintain I guess, we could switch the codebase to using this

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
https://github.com/vuejs/rfcs/discussions/502

it's a opt-in feature, not enabled by default 


```ts
// vite.config
export default defineConfig({
  plugins: [
    vue({
      script: {
        propsDestructure: true
      }
    })
  ]
})
```

**Comment by zernonia** [comment]
Hey @maelp  thanks for the suggestion.. however I would love to keep the current way of composing components are not all projects will enable `propsDestructure: true`, and enabling it would cause some unforeseen behavior as it is still in `opt-in` feature, and not by default.
