### ISSUE TITLE
[Feature]: Make Switch work with v-model

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#121]
### Describe the feature

It seems that right now we have to do something like this

```
              <Switch
                class="flex-none"
                id="toggle"
                :checked="isToggleSelected"
                @update:checked="(v) => (isToggleSelected = v)"
              ></Switch>
```

I guess it would be easier to allow something like

```
              <Switch
                class="flex-none"
                id="toggle"
                v-model="isToggleSelected"
              ></Switch>
```

but when I use the latter it doesn't update the var

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
`radix-vue` intend to have the same API as `radix-ui` but I like `v-model` more cause you can easily use `vee-validate` `componentField` slotProp

| `radix-vue` | `radix-ui` |
|:--------:|:--------:|
| `checked` and `v-model:checked` | `checked` |
| `@update:checked` | `onCheckedChange` |

**Comment by romansp** [comment]
`v-model` binding should work properly when used together with `checked` argument. 

Try `v-model:checked="isToggleSelected"`.

**Comment by maelp** [comment]
okay thanks! any reason that we don't simply use `v-model` since this seems to be the most natural?

**Comment by sadeghbarati** [comment]
> okay thanks! any reason that we don't simply use `v-model` since this seems to be the most natural?

It's based on component **design/props**

https://vuejs.org/guide/components/v-model.html

```mermaid
flowchart LR
    C --> A["`2` checked (prop)"]
    A --> B
    B["`3` update:checked (emit)"] --> C
    C[`1` v-model:checked]
```

**Comment by maelp** [comment]
okay, not sure if I understood, but what I meant is: why using a "checked" variable rather than a "modelValue" variable, and using a simple `v-model` rather than `v-model:checked`?

**Comment by RihanArfan** [comment]
I believe usage for `v-model:checked` would be suited if a component had multiple things to change, such as something like `<SignupForm v-model:username="" v-model:password="" />`. However, since <Switch /> only has one thing, I agree with @maelp where only `v-model` should be used.

**Comment by hrynevychroman** [comment]
Yeah, I think that it must be ability to use `v-model` or `v-model:checked` (back compatibility). It is only Switch toggle, there will be no other `v-model` I think. But to update this we must change `Radix-vue` codebase, because all Props and Emits took from it, we just style components for `shadcn` styling 🙂 

Think that need to add `modelValue?: boolean;` to `SwitchRootProps`, and `'update:modelValue': [payload: boolean];` to `SwitchRootEmits`) But I don't think that `Radix-vue` will accept this 🤔 

<img width="678" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/82209198/675a3810-5adc-4162-ad5e-59d653126ed3">

@sadeghbarati maybe you can help here, maybe I don't familiar enough with codebase here ❤️

**Comment by sadeghbarati** [comment]
Radix Vue API intended to looks like main [Radix UI Checkbox](https://www.radix-ui.com/primitives/docs/components/checkbox#root)

https://github.com/radix-vue/shadcn-vue/issues/121#issuecomment-1763737779


Radix UI has **checked** `prop` and **onCheckedChange** function

Radix Vue has **checked** `prop` and **update:checked** `emit` which allow two way binding with `v-model:checked`

**Comment by sadeghbarati** [comment]
> Pick the components you need. Use the CLI to automatically add the components, or copy and paste the code into your project and customize to your needs. The code is yours.

Feel free to change the source 😀

**Comment by sugoidesune** [comment]
I patched the emits for Checkbox. The original functionality is kept but v-model added.
I think it's more than warranted to bring back expected vue functionality and dev experience even if shadcn-vue is just a "reskin" The main focus should be on VUE not REACT.js RADIX...
https://github.com/radix-vue/shadcn-vue/issues/622#issuecomment-2178932075
