### ISSUE TITLE
[Bug]: Input and autofocus, or vueuse useFocus

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#123]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

None

### Steps to reproduce

I'm trying to have the <Input> component work when using `autofocus` (which should normally work on regular <input> HTML components) and the `useFocus` method of vue-use, but it does not work, is there something to change for this to work?

### Describe the bug

See above

**Comment by sadeghbarati** [comment]
> The `autofocus` attribute only works reliably if the element is present when the page first loads. It won't work if the element is dynamically injected into the page afterwards.


Use [`useFocus`](https://vueuse.org/core/useFocus/) or Vue [`Template Refs`](https://vuejs.org/guide/essentials/template-refs.html) instead

**Comment by maelp** [comment]
interesting thanks! I tried useFocus, and for some reason (but might be linked to the code on my page) it doesn't work with the `initialValue`, I have to do some hack like `setTimeout(() => setFocus(), 500) after the page is mounted or something

**Comment by maelp** [comment]
but I see that the radix-vue code has an "auto-focus" (with an hyphen) property on my items, how is that implemented? could we add this to other components?

**Comment by sadeghbarati** [comment]
Vue doesn't have forwardRef like React you have to expose (defineExpose) input element
`elemenRef.value.exposedInputElement`

---

If input element is immediate child of template you don't need expose, you can access the dom element with for example `elementRef.value.$el`

[Vue SFC Playground](https://play.vuejs.org/#eNp9Uk1rwzAM/SvCDJZCSQ69lbSwjR422Afbjr6EVMnSObZry12h5L9PTtas0K2HQKT3JD3p+SBurE13AcVc5L50jSXwSMEupW5aaxzBARxWUzD60QRNuIYOKmdauOaq65F1Z1r7k0+zGMSmDJdGe4ItLGKXZCK11GOnJJnAYgkHqQEizyhMlamTbborVMD0ChUXdPzl2aCNVXFA2FpVEHIEkPeTuflCiq0UUAQylSmDzxjOsxOumAryPKdq6nTjjeaV+9FSlNyiUeieLTWsQ4r5ICpihVLm66HPkQs4PebLDyw//8hv/D7mpHhx6NHtUIoRo8LVSAO8envCPf+PYGvWQTH7AviKfKMQNQ6026DXLPuE16u97y1pdP3uV3tC7Y9LRaGR2fV8KdiieL3/Vv+VO0tnfR27wVc82nv2Zi7Z1GgbCM5N6b4BIz3Xiw==)


Also it's much better if you create a simple demo

---

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus#accessibility_concerns
