### ISSUE TITLE
docs:  improve API Reference for the Data Table Component

### ISSUE THREAD

**Issue by selemondev** [radix-vue/shadcn-vue#132]
### Describe the feature

The Shadcn Vue documentation currently provides limited information about the Data Table component. I propose expanding the documentation by incorporating references from Shadcn UI's comprehensive documentation on the Data Table component.

### Additional information

- [X] I intend to submit a PR for this feature.
- [x] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Awesome! ❤️ Let me know if there's any help needed!
