### ISSUE TITLE
[Bug]: Theme page padding and width 

### ISSUE THREAD

**Issue by anonimusprogramus** [radix-vue/shadcn-vue#136]
### Environment

```bash
Client OS: LinuxMint
Browser: Brave 1.59.120 Chromium: 118.0.5993.88 (Official Build) (64-bit)
Screen: 1370x681
```

### Link to minimal reproduction

https://www.shadcn-vue.com/themes.html

### Steps to reproduce

1. open [shadcn](https://ui.shadcn.com/themes)
2. open [shadcn-vue](https://www.shadcn-vue.com/themes.html)
3. compare

### Describe the bug

The width exceeds max, the padding not centered

### **shadcn**
![2023-10-23 12-02-02](https://github.com/radix-vue/shadcn-vue/assets/7464749/b6af1b61-eac2-4881-bcb6-eab01a408bd7)

### **shadcn-vue**
![2023-10-23 12-01-52](https://github.com/radix-vue/shadcn-vue/assets/7464749/7afb08ac-17e1-484b-a77d-340fdb063749)

**Comment by sadeghbarati** [comment]
Charts are growing bigger after window resize
This also happens in the shadcn-ui

![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/d549d0a5-53e2-4032-add2-46a5887e8257)

**Comment by anonimusprogramus** [comment]
I think I found the cause.

It's that `ThemingLayout.vue` has `container` class:
```vue
<template>
  <div class="container relative">
    <div class="flex justify-between items-center">
    </div>
    <section>
      <slot />
    </section>
  </div>
</template>
```

while `MainLayout.vue` already has `container` class:
```vue
<main v-else class="container">
  <Transition name="fade" mode="out-in">
    <Content :key="$route.path" />
  </Transition>
</main>
```

Removing `container` class in `ThemingLayout.vue` should fix.

Here's the differences (notice those twice `container` class in shadcn-vue):

### shadcn-ui
![2023-10-23 19-36-37](https://github.com/radix-vue/shadcn-vue/assets/7464749/d82d0868-24c7-404c-bc88-bd907281c434)

### shadcn-vue
![2023-10-23 19-36-51](https://github.com/radix-vue/shadcn-vue/assets/7464749/9c0ce5f7-fd95-4272-8033-0584ac4f64ef)

**Comment by sadeghbarati** [comment]
> Removing `container` class in `ThemingLayout.vue` should fix.

Did the same, but I think it's related to [`@unovis` ](https://github.com/f5/unovis)

https://github.com/radix-vue/shadcn-vue/assets/17789047/12a04a10-0198-4dd3-897c-7bbffe6b46c9

**Comment by sadeghbarati** [comment]
@anonimusprogramus the issue is

- `grid-template-columns: 280px 1fr;` ✅(on first render) but after resize ❌ 
- althought this is right `grid-template-columns: repeat(2, minmax(0, 1fr));` ✅ (50%, 50%)

`grid fraction` (1fr) causes the issue and `ResizeObserver` function inside `@unovis/ts` can't calculate the **right width** for SVG

**Comment by sadeghbarati** [comment]
Changed `Total Revenue` and `Subscriptions` card grid CSS to `grid-template-columns: 280px 1fr;` and this happened

![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/03f48e5b-9e3e-4da9-a13c-bdb14fe8360f)
