### ISSUE TITLE
[Bug]: Issue with SelectRoot in mobile

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#137]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

None

### Steps to reproduce

Not sure how to reproduce this one, as it happens on a quite complicated setup. This is what happens there is a weird overflow-x on mobile (if I drag horizontally the page will seem to scroll to the right, although there is no content), and this is linked to the `<Select>` when some items are particularly long in it.

I fixed it by adding this weird hack in Select, which seems to solve the issue, but not sure if there's a better way?

```vue
<SelectRoot
  :class="cn('max-w-[0px]', $attrs.class ?? ')"
  v-bind="{ ...props, ...useEmitAsProps(emits) }"
>
  <slot />
</SelectRoot>
```

https://github.com/radix-vue/shadcn-vue/assets/15458/1dffd837-95c5-46e7-ab53-1c407111518c

### Describe the bug

It scrolls

**Comment by sadeghbarati** [comment]
Zernonia already includes `Stackblitz` or `CodesandBox` buttons

Make a reproduction first to test on our mobile

**Comment by maelp** [comment]
how does that work? is that when creating an issue? I'll see if I can reproduce it

**Comment by Blinks44** [comment]
> Author

It's here:

![2023-10-23_15-12-17](https://github.com/radix-vue/shadcn-vue/assets/8570193/6d9be413-4f79-42d1-a748-1e777c037205)

Then you can create reproduction of your code
