### ISSUE TITLE
[Bug]: Calendar component throwing peer dependency error. 

### ISSUE THREAD

**Issue by TechAkayy** [radix-vue/shadcn-vue#142]
### Environment

```bash
Developement/Production OS: macOS Monterey v12.6.1
Node version: 21.1.0
Package manager: npm 10.2.0
Radix Vue version: Not sure, where to find this info? Even package-lock.json didn't have this info
Shadcn Vue version: Not sure, where to find this info? Even package-lock.json didn't have this info
Vue version: 3.3.7
Astro version: 3.4.0
CSS framework: tailwindcss@3.3.5
Browser: n/a
```

### Link to minimal reproduction

https://github.com/TechAkayy/astro-shadcn-vue-calendar-issue

### Steps to reproduce

- Clone repo
- `npm install`
- `npx shadcn-vue@latest add calendar`

### Describe the bug

Getting some peer dependency (vue2) error. Unable to install the calendar component. 

![image](https://github.com/radix-vue/shadcn-vue/assets/73772701/3b6f10c8-1c3c-4a81-abd3-35fb32e0f07a)

### Expected behavior

Able to install calendar component.

**Comment by sadeghbarati** [comment]
`v-calendar` latest tag is **2.4.2** and CLI tries to install v2.4.2 


For now, use 

```shell
npm install v-calendar@next
```
or
```shell
npm install v-calendar@3.1.2
```
