### ISSUE TITLE
[Bug]: "TeamSwitcher" freezes if you click "add" after searching

### ISSUE THREAD

**Issue by teleskop150750** [radix-vue/shadcn-vue#144]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.shadcn-vue.com/

### Steps to reproduce

https://www.youtube.com/watch?v=JFARPdwyyTk

### Describe the bug

"TeamSwitcher" freezes if you click "add" after searching

[https://www.shadcn-vue.com/](https://www.shadcn-vue.com/)

**Comment by gregmsanderson** [comment]
I'm also finding an issue with that component.

In my case if I visit https://www.shadcn-vue.com/ and simply _click_ on "Alicia Koch" ... the browser freezes, just like you are seeing. The menu doesn't even open for me. No error in the console. CPU fan starts up, so it's doing _something_. Eventually have to close the tab.

The Combobox on https://www.radix-vue.com/ seems to work fine.

Chrome 119 on a Mac.

**Comment by anonimusprogramus** [comment]
Can confirm here, using Brave browser on LinuxMint.

Fixed it by changing one line in `TeamSwitcher.vue`

from
```javascript
<CommandItem
  :value="{ label: 'Create Team' }"
  @select="() => {
    open = false
    showNewTeamDialog = true
  }"
>
  <PlusCircledIcon class="mr-2 h-5 w-5" />
  Create Team
</CommandItem>
```

to
```javascript
<CommandItem
  value="create-team"
  @select="() => {
    open = false
    showNewTeamDialog = true
  }"
>
  <PlusCircledIcon class="mr-2 h-5 w-5" />
  Create Team
</CommandItem>
```

**Comment by sadeghbarati** [comment]
@anonimusprogramus Can you make PR for this?

**Comment by anonimusprogramus** [comment]
@sadeghbarati done, thanks for the opportunity

**Comment by zernonia** [comment]
Thanks @anonimusprogramus  @sadeghbarati ! Fixed in https://github.com/radix-vue/shadcn-vue/pull/167
