### ISSUE TITLE
docs: Improve the API reference of all the components 

### ISSUE THREAD

**Issue by selemondev** [radix-vue/shadcn-vue#145]
### Describe the feature

I want to create a complete API reference for all the components in Shadcn Vue, so the documentation site is ready for use.

### Additional information

- [X] I intend to submit a PR for this feature.
- [x] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Wondering what do you mean by "Complete API" reference ya? Does't most of the component already have reference to Radix Vue? 🤔

**Comment by selemondev** [comment]
> Wondering what do you mean by "Complete API" reference ya? Does't most of the component already have reference to Radix Vue? 🤔

By `Complete API reference` I mean the entire documentation of a particular component. For example: The Button component's full documentation based on what Shadcn UI has.
