### ISSUE TITLE
[Feature]: Nuxt installation steps - add `'~/components'` to components key (not sure if it's required)

### ISSUE THREAD

**Issue by TechAkayy** [radix-vue/shadcn-vue#153]
### Describe the feature

Please refer to this question in nuxt repo - https://github.com/nuxt/nuxt/discussions/24169. 

When using the `components` array (as per step-4 for Nuxt installation instructions - like below), the components in the base of the `components` folder are not getting scanned and auto-imported anymore. 

```
export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss'],
  components: [
    {
      path: '~/components/ui',
      // this is required else Nuxt will autoImport `.ts` file
      extensions: ['.vue'],
      // prefix for your components, eg: UiButton
      prefix: 'Ui'
    },
  ],
})
```

In the below reproduction, you can notice that NavBar component used in the default layout, and DarkModeSwitch used in the index page are not getting auto-imported anymore. 

Not sure if this is a bug with nuxt's components scanning. If not, then we should add `'~/components'` to the components array in Nuxt config. 

Stackblitz - [stackblitz.com/github/TechAkayy/my-nuxtui-shadcn-vue-x-clone-path-prefix-issue](https://stackblitz.com/github/TechAkayy/my-nuxtui-shadcn-vue-x-clone-path-prefix-issue)
Github repo - [TechAkayy/my-nuxtui-shadcn-vue-x-clone-path-prefix-issue](https://github.com/TechAkayy/my-nuxtui-shadcn-vue-x-clone-path-prefix-issue)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Ow Yes, You Right,

Default `Nuxt` config for auto import directories is

```
[
  { priority: 1, path: 'D:/Test/nuxt-test/components/islands', island: true },
  { priority: 1, path: 'D:/Test/nuxt-test/components/global', global: true },
  { priority: 1, path: 'D:/Test/nuxt-test/components' },
]
```

After explicitly adding `components: []` or `component.dirs: []` default config will disposed


---

Possible ways to resolve this issue is

1. Adding auto-import `components` option in Nuxt Layer
2. Using Nuxt module for extending directories with hook `components:dirs` inside `defineNuxtModule`
3. Using `nuxt.config.ts` `components:dirs` hook for extending directories

---

Step 2,3 had this error `WARN  Two component files resolving to the same name` but I found out, I used it wrong 

I was using `push` instead of `unshift` method for adding directories


#### push
```
[
  { priority: 1, path: 'D:/Test/nuxt-test/components/islands', island: true },
  { priority: 1, path: 'D:/Test/nuxt-test/components/global', global: true },
  { priority: 1, path: 'D:/Test/nuxt-test/components' },
  { path: '~/components/ui', extensions: [ '.vue' ], prefix: 'Ui' }, // new directory
]
```

#### unshift
```
[
  { path: '~/components/ui', extensions: [ '.vue' ], prefix: 'Ui' }, // new directory
  { priority: 1, path: 'D:/Test/nuxt-test/components/islands', island: true }, // will ignore new dir
  { priority: 1, path: 'D:/Test/nuxt-test/components/global', global: true }, // will ignore new dir
  { priority: 1, path: 'D:/Test/nuxt-test/components' }, // will ignore new dir
  
]
```

**Comment by TechAkayy** [comment]
Thanks for the detailed explanation @sadeghbarati :-) That's very helpful. 

While you are at this (Nuxt installation instructions), can I suggest also to add `pathPrefix: false`. The folder names for each component groups, for eg, accordion, alert etc are ignored, because all the component-names start with the same. 

But, just in case any component-name slightly deviates from the containing folder name, then pathPrefix will get added. For eg, try renaming `accordion/Accordion.vue` to `accordion/MyAccordion.vue`, the component turns into `<AccordionMyAccordion/>`. 

I guess all components are prefixed with the folder-names, but this is still something that needs to be strictly followed by the maintainers in the future. So, setting `pathPrefix: false` will decouple the containing foldername & the component's usage. Nuxt-UI-Pro does the same.

**Comment by sneakylenny** [comment]
Leaving this here for anyone to copy paste:

```ts
  components: [
    { path: '~/components', ignore: ['~/components/ui'] },
    { path: '~/components/ui', pathPrefix: false },
  ],
```
