### ISSUE TITLE
[Bug]: Using `cssVariables: false` causing Tailwind classes to be wrong for `Button/index.ts`

### ISSUE THREAD

**Issue by rogrile** [radix-vue/shadcn-vue#156]
### Environment

```bash
Developement/Production OS: MacOs Ventura 13.5.2
Node version: 18.18.0
Package manager: npm 9.8.1
 "@nuxtjs/tailwindcss": "^6.9.4",
"nuxt": "^3.8.1",
"typescript": "^5.2.2",
"vue": "^3.3.8",
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-bnrfh1?file=nuxt.config.ts,app.vue

### Steps to reproduce

Follow steps from https://www.shadcn-vue.com/docs/installation/nuxt.html.

### Describe the bug

Utility classes option not working at all

### Expected behavior

When I follow the steps from the documentation and I choose utility classes instead of CSS variables, I expect my components to work and display proper classes

**Comment by zernonia** [comment]
The Utility classes is actually working.. try `Dialog` component. The root issue is with the parser ignoring `.ts`file, which shouldn't be the case.
