### ISSUE TITLE
[Bug]: Not clear from documentation how to use Dialog programmatically

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#160]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

none

### Steps to reproduce

I have a use-case where I'm using a `<Dialog :open="isOpen" @update:open="(v) => isOpen = v">...</Dialog>` but if I have a button inside my dialog to close it using programmatic code (eg just doing `isOpen.value = false`, it still keeps the "overflow-hidden" on the body of the app so I cannot scroll my page anymore.

It's not clear to me how I can close the dialog "programmatically" rather than using a "DialogClose" component?

### Describe the bug

There should be a way to close the dialog programmatically

**Comment by maelp** [comment]
Here is a reproduction URL for the bug https://stackblitz.com/edit/kgeztv?file=src%2FApp.vue

**Comment by maelp** [comment]
Weirdly, the code works if there is only one SelectModal shown, but if I do the current code where it opens the second, then closes it, the background content is no longer scrollable afterwards

**Comment by maelp** [comment]
(note that because of the "bug" on StackBlitz that I mentioned in the other issue you have to say "N" to all the install in the VM while it boots and installs dependencies)

**Comment by maelp** [comment]
Also weird:

 - when the first dialog is open, you cannot scroll the content behind the modal (as expected)
 - but when you use the button inside the modal to close it and open the next, then the content behind the modal becomes scrollable

NOTE: I know that there is a "DialogClose" button to close a dialog, but in my setting I have an app where I need to close the dialog "programmatically", either using `isOpen = false` or equivalent

what is the correct way to do it, such that there is no bug (the "main" content is not scrollable on the second modal, and it becomes scrollable again when both modals are closed?)

**Comment by maelp** [comment]
I guess there might be a "toggling" of the "overflow-hidden" class on the body, rather than just forcing it to "true" when closed and "false" when open? this might explain why when closing the first modal and opening the second one, the background becomes scrollable, and when closing the second one, it is no longer scrollable? perhaps the "toggling" for each Modal is done "in the wrong order" and thus there is the bug?

**Comment by sadeghbarati** [comment]
@zernonia 

Yeah that is a bug in main `radix-vue` source

https://stackblitz.com/edit/5afwtt?file=src%2FApp.vue

I think it's related to [`useBodyScrollLock`](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/shared/useBodyScrollLock.ts)

**Comment by zernonia** [comment]
Thansk @maelp @sadeghbarati . 
Indeed this was an issue from `radix-vue`, in particular `useScrollLock` from `@vueuse/core`. Perhaps we need to implement a workaround instead seeing that this usage is quite common.

**Comment by zernonia** [comment]
Created an issue https://github.com/radix-vue/radix-vue/issues/512

**Comment by maelp** [comment]
I guess since the related issue is closed we can close this one? I'll test it soon

**Comment by maelp** [comment]
working

**Comment by maelp** [comment]
@zernonia reopening because I see there's still a bug

- I moved to the latest radix-vue lib with your fix
- it works correctly on desktop
- but it fails on mobile (???) on Google Chrome

if you go to my website [https://builder.gouach.com](https://builder.gouach.com) on desktop, it will show a modal, click on "create new project", it closes the first modal and open the second, click on a project, and the side menu is correctly scrollable

go to the website on iOS Chrome browser (tested it on this at least), do the same, the body is no longer scrollable?

**Comment by maelp** [comment]
same for iOS / safari

**Comment by maelp** [comment]
hmmmm actually for some reason it was using an old cached version

**Comment by maelp** [comment]
okay weirdly it seems to work on iOS/Safari but not iOS/Chrome 😅

**Comment by maelp** [comment]
I reloaded multiple time, using the linked debugger (connected to my mobile browser from my laptop), and in Chrome it seems the overflow:hidden is kept after updating???
