### ISSUE TITLE
[Bug]: Issue on CodeSandbox

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#161]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

None

### Steps to reproduce

When opening the "Dialog" component StackBlitz link, I have this error
<img width="358" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/15458/d38c1a16-7cf6-4e34-908d-01e5bcc53e7e">

### Describe the bug

Error with Node version

**Comment by maelp** [comment]
Sorry the bug is in CodeSandBox

there's also an issue in StackBlitz, which is that you use the CLI with `-y` flag but it still asks for input from user and hangs

<img width="508" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/15458/4123d539-3239-4a3d-9638-9a3cbc08d18e">

**Comment by sadeghbarati** [comment]
> Sorry the bug is in CodeSandBox
> 
> there's also an issue in StackBlitz, which is that you use the CLI with `-y` flag but it still asks for input from user and hangs
> 
> <img alt="image" width="508" src="https://user-images.githubusercontent.com/15458/282245566-4123d539-3239-4a3d-9638-9a3cbc08d18e.png">

Tested Stackblitz/Codesandbox, you should add `-o` or `--overwrite`

Like this

```
shadcn-vue add button dialog input -y -o
```

Use `shadcn-vue` CLI `--help` flag for each command you want to use
