### ISSUE TITLE
lucide-vue-next:  Cannot redeclare block-scoped variable

### ISSUE THREAD

**Issue by CassioLuis** [radix-vue/shadcn-vue#169]
### Discussed in https://github.com/radix-vue/radix-vue/discussions/513

<div type='discussions-op-text'>

<sup>Originally posted by **CassioLuis** November 12, 2023</sup>
I know this is a bug with a third-party library, but I believe it's important for you to know.
![image_2023-11-12_09-19-25](https://github.com/radix-vue/radix-vue/assets/21344396/aa1d916f-fe4e-4c66-997a-f5cec3ef86b6)

I'm just `npm run build` my typescript project, with some components that make use of `lucide-vue-next` (accordion and toast components).
</div>

**Comment by zernonia** [comment]
Hey @CassioLuis . Can you provide a minimal reproduction for this? Radix vue package doesn't export any Icon. You sure it's related to `radix-vue`?

**Comment by CassioLuis** [comment]
I'm sorry, this is related to the shadcn vue components, I hadn't noticed that.

**Comment by zernonia** [comment]
@CassioLuis  I've transfer the issue here, do you mind provide a minimal reproduction please? 😁

**Comment by CassioLuis** [comment]
here is the link to stackblitz:

https://stackblitz.com/edit/vitejs-vite-sd3x3s

just run 'npm run build'.

**Comment by zernonia** [comment]
Thanks @CassioLuis ! you need to add `"skipLibCheck": true` in your tsconfig to prevent type checking for libs.

**Comment by CassioLuis** [comment]
thanks, this worked for me !
