### ISSUE TITLE
[Bug]: Uncaught (in promise) TypeError: Cannot destructure property 'page' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by Haunth** [radix-vue/shadcn-vue#173]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://github.com/radix-vue/shadcn-vue/tree/dev/apps/www/src/lib/registry/default/ui/pagination

### Steps to reproduce

Using pagination with nuxt3

### Describe the bug

Bug about Pagination with nuxt3

### Expected behavior

Resolve this bug

### Conext & Screenshots (if applicable)

I'm using pagination with nuxt3 but I have this error. Please give me hơ to fix this
![image](https://github.com/radix-vue/shadcn-vue/assets/50883629/f7df6b64-e8c5-4d6b-8427-6440fb287a58)

**Comment by sadeghbarati** [comment]
Same issue as `vee-validate` component export in `index.ts` https://github.com/radix-vue/shadcn-vue/issues/172

You have to explicitly import from `radix-vue`

```ts
import {
  PaginationRoot as Pagination,
  PaginationList,
  PaginationListItem,
} from 'radix-vue'
```

**Comment by Haunth** [comment]
> Same issue as `vee-validate` component export in `index.ts` #172
> 
> You have to explicitly import from `radix-vue`
> 
> ```ts
> import {
>   PaginationRoot as Pagination,
>   PaginationList,
>   PaginationListItem,
> } from 'radix-vue'
> ```
yes. Thanks . I'm using auto import of Nuxtjs. => import in file vue
