### ISSUE TITLE
[Feature]: add default animation for collapsibles

### ISSUE THREAD

**Issue by raxelo** [radix-vue/shadcn-vue#185]
### Describe the feature

Currently, the [docs](https://www.shadcn-vue.com/docs/components/collapsible.html) show a default collapsible animation but do not provide clear instructions on how to set that up. Instead, you have to figure that out by navigating into the StackBlitz/CodeSandbox example.

By default, the `accordion-down` and `accordion-up` animations are added, but that's not the case for the `collapsible-down` and `collapsible-up` animations.

I wasn't really sure if this should be reported as a bug or a feature. Since the docs include that animation by default I think it makes sense to add them in the library too.

### Additional information

- [x] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Closed https://github.com/radix-vue/shadcn-vue/pull/186
