### ISSUE TITLE
[Bug]: detypes transform incorrectly for `as` props

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#187]
Primitive from [radix-vue](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Primitive/Primitive.ts#L46) was updated to have `as` props to accept `AsTag | Component`, which is breaking the type transformation here, which is breaking the pipeline.

![image](https://github.com/radix-vue/shadcn-vue/assets/59365435/85cb1db0-1d2f-4dce-8d77-e716a58b05f6)

@Dunqing  can you help with this? 😁

**Comment by Dunqing** [comment]
I will take a look at this next week

**Comment by Dunqing** [comment]
~~How to reproduce?~~

**Comment by Dunqing** [comment]
https://play.vuejs.org/#__DEV__eNp9kU1PwzAMhv+KlctAmjah3UYpArQDHGCCHXOpWrfLSJ0oSbeiqv8dp9U+DrCb7fd1/NjpxJO1s32DYikSnztlA3gMjQWdUfUgRfBSpJJUbY0L0MGL4YiQAvRQOlPDhJsnkgosFeHaGeuTThJk/nF5Nt9L6tObW0nJfBzCT3ISsLY6C8gZQLK9Szc/FuHgDFXJnNPov/CIKePkhkpVzXbeEDPHUSBFzoOURvdhgzLEyEsYlKhlWpvD21ALrsHpsZ5vMf/+o77zbaxJsXbo0e1RipMWMldhGOXV1zu2HJ/E2hSNZvcV8RO90U1kHG3PDRWMfeEbaF+HayuqNn7VBiR/XCqCRmc/+KXg28cb/7f6GXcxWwx9/A+i/wXqeKcQ

It looks like this is a bug with the `vue` compiler

**Comment by zernonia** [comment]
Thanks for the findings @Dunqing  😁

**Comment by zernonia** [comment]
Thanks for the upstream issue, and since it's not a bug, I will update the snapshot as well as closing this ticket.
Thanks @Dunqing !
