### ISSUE TITLE
[Feature]: datepicker

### ISSUE THREAD

**Issue by andredewaard** [radix-vue/shadcn-vue#20]
### Describe the feature

Im really curious to see which date picker component will be used for this library. 
Shadcn for react is using this one: https://react-day-picker.js.org/

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by k11q** [comment]
[vue-datepicker](https://vue3datepicker.com/) seems cool.

**Comment by zernonia** [comment]
I've tested with both components, and it seems [v-calendar](https://vcalendar.io/) has better keyboard navigation, and utilities compare to [vue-datepicker](https://vue3datepicker.com/). 😁

**Comment by andredewaard** [comment]
Both options are not headless, I think its better to have something like this: https://ark-ui.com/docs/react/components/date-picker

**Comment by zernonia** [comment]
Yup. It's not perfect.. but it would do for now. I've also created a new issue to introduce DatePicker primitives https://github.com/radix-vue/radix-vue/issues/379
