### ISSUE TITLE
[Feature]: `FieldArray` support

### ISSUE THREAD

**Issue by kevin70** [radix-vue/shadcn-vue#204]
### Describe the feature

Hello, we hope to add dynamic array validation in the `form`.

See also [https://vee-validate.logaretm.com/v4/examples/array-fields/](https://vee-validate.logaretm.com/v4/examples/array-fields/).

Thanks.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
@kevin70 

Take a look at this example you can use `useFieldArray` composable or `FieldArray` component from `vee-validate`
There is no need to add another wrapper around these composable or component

https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/examples/forms/components/ProfileForm.vue

**Comment by kevin70** [comment]
Thank you.

**Comment by halws** [comment]
Hi there,  what about validation for `<TagsInput/>` ?

I did it with `useFieldArray`, and it works, but maybe there is more elegant way? 
```js
const schema = toTypedSchema(
  z.object({
    
    categories: z
      .string()
      .array()
      .nonempty('Please select at least one category'),
  })
);


const form = useForm({
  validationSchema: schema,
  initialValues: {
    categories: ['', 'fullstack'],
  },
});

const {
  remove: removeCategory,
  replace: replaceCategories,
  fields: categories,
} = useFieldArray<string>('categories');
```

```html
// ... template
    <FormItem>
      <FormLabel>Categories</FormLabel>
      <FormControl>
        <TagsInput
          id="categories"
          :model-value="categories.map((field) => field.value)"
          @update:model-value="replaceCategories($event)"
        >
          <TagsInputItem
            v-for="(item, index) in categories.map(
              (field) => field.value
            )"
            :key="item"
            :value="item"
          >
            <TagsInputItemText />
            <TagsInputItemDelete
              @click="[removeCategory(index), validate()]"
            />
          </TagsInputItem>
          <TagsInputInput
            v-bind="componentField"
            placeholder="Categories..."
          />
        </TagsInput>
      </FormControl>
      <FormMessage />
    </FormItem>
```
