### ISSUE TITLE
[Bug]: Dialog's top right close icon cannot close the dialog if open the dialog programmatically

### ISSUE THREAD

**Issue by sunny-repo88** [radix-vue/shadcn-vue#206]
### Environment

```bash
Radix Vue version: 1.2.4
```

### Link to minimal reproduction

https://github.com/sunny-repo88/shadcn-vue-dialog-bug

### Steps to reproduce

```
`
<script setup lang="ts">
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { ref } from 'vue'


const open = ref(false)

</script>

<template>
  <Dialog :open="open">
    <DialogTrigger>
      <Button @click="open = true">Edit Profile</Button>
    </DialogTrigger>
    <DialogContent>
      <DialogHeader>
        <DialogTitle>Edit profile</DialogTitle>
        <DialogDescription>
          Make changes to your profile here. Click save when you're done.
        </DialogDescription>
      </DialogHeader>

      <DialogFooter>
        Save changes
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
`
```

### Describe the bug

![image](https://github.com/radix-vue/shadcn-vue/assets/30856837/4a07540b-e308-480d-9681-6a2c28b06818)

right top icon cannot close the dialog

### Expected behavior

right top icon should be able to close the dialog

**Comment by sadeghbarati** [comment]
You are using `Controlled Component` which you control the (`open`) state (`show/hide`)
in this case, you should handle the hiding or showing of the component

You could use 
- `v-model:open="open"` easy way ✅ or
- `:open="open"` and `@update:open="(openState) => (open = openState)"` 🙅 


Dialog demo here: https://stackblitz.com/edit/github-eurciq?file=src%2FApp.vue

**Comment by sadeghbarati** [comment]
If you want to use `UnControlled Component` and still want to show dialog by default you could use 

[`defaultOpen`](https://www.radix-vue.com/components/dialog.html#root) prop which you can read about in **MAIN** `radix-vue` documentation

**Comment by sunny-repo88** [comment]
@sadeghbarati , thanks!
