### ISSUE TITLE
Question: Support for MonoRepos 

### ISSUE THREAD

**Issue by selemondev** [radix-vue/shadcn-vue#210]
An issue was raised in the `shadcn-vue-vscode` extension regarding monorepo support by @naveeng2402.

Issue: https://github.com/selemondev/vscode-shadcn-vue/issues/21#issue-2018885747

Here are the questions asked:

1. A clear plan for implementing the shadcn-vue on monorepos while following best practices and guidelines.

2. A clear explanation on how to proceed when using a monorepo either by having a separate package in it or having it installed in each application.

What would be the best way of doing this?

**Comment by sadeghbarati** [comment]
You can test it yourself `(pnpm workspaces)`

[shadcn-vue-monorepo.zip](https://github.com/radix-vue/shadcn-vue/files/13697499/shadcn-vue-monorepo.zip)

---


- First of all, don't do this cause you have to fully understand **Node** `moduleResolution` for the **ui** `monorepo` package

- We lose Vite **HMR** after using `monorepo` way If we want to change **ui** package class/styles, Vite will **fully reload** the page instead

- We have to add another path to `tailwind.config` and `content` to **scan** the classes inside `monorepo` **ui** package

---

Further reading from this comment to down

https://github.com/radix-vue/shadcn-vue/issues/176#issuecomment-1822128561

**Comment by selemondev** [comment]
Thanks @sadeghbarati 🔥.

**Comment by sadeghbarati** [comment]
Monorepo will add complexity to the project

It's a good choice if you want to build your Design System with custom logic `(wrapper-around(radix-vue))` and also with Storybook

But `wrapper-around(shadcn-vue(radix-vue))` I'm not sure about it
