### ISSUE TITLE
[Bug]: Multiple checkbox docs example different from stackblitz

### ISSUE THREAD

**Issue by leogallot** [radix-vue/shadcn-vue#212]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 18.18.0
Radix Vue version: 1.2.5
Shadcn Vue version: 0.8.4
Vue version: 3.3.12
CSS framework: tailwindcss@3.3.7
Client OS: Windows 10.0.19045
Browser: Chrome 120.0.6099.110
```

### Link to minimal reproduction

https://www.shadcn-vue.com/docs/components/checkbox.html

### Steps to reproduce

1. Open the checkbox documentation page https://www.shadcn-vue.com/docs/components/checkbox.htm
2. Go to the **Form** (multiple checkboxes) section
3. Unselect all the checkboxes

### Describe the bug

The validation done in the form multiple checkbox example from the documentation behaves differently when we open it in stackblitz. 
When we uncheck all the checkboxes in the documentation page, the title and all the labels are coloured in red whereas on stackblitz only the last label is coloured.

### Expected behavior

The validation is the same in the documentation example and in stackblitz.

### Conext & Screenshots (if applicable)

Documentation validation
![docs_example](https://github.com/radix-vue/shadcn-vue/assets/35570927/45d32fb2-da7b-4a85-a6bd-58a61b3b1241)

Stackblitz validation
![stackblitz](https://github.com/radix-vue/shadcn-vue/assets/35570927/d128068e-1c53-477b-ab72-6b25a0fe36fb)

**Comment by sadeghbarati** [comment]
Thanks for reporting 🙌
