### ISSUE TITLE
[Bug](Nuxt modules): HMR not working when edit component, load too slow

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#214]
### Environment

```bash
Shadcn Vue version: latest
Nuxt version: 3.8.2
```

### Link to minimal reproduction

run locally

### Steps to reproduce

1. Fork https://github.com/zernonia/memory-lanes,
2. pnpm i
3. pnpm dev

### Describe the bug

<img width="423" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/59365435/1f6fbc1e-a76f-403c-84b0-c46840c791b7">

Slow modules, took 7s to load many components.

### Expected behavior

HMR should work when edit component, faster module

**Comment by sadeghbarati** [comment]
I think it should better to callout Daniel or other Nuxt maintainers 


For solving auto-import issue we partially resolve with `nuxt.hook('components:dirs')`


I think TsMorph process cause this issue

**Comment by zernonia** [comment]
Yeah I think so too. `ts-morph` is causing the slow performance when there's many components.
Also, I had the hacky `ignorePath` which is casuing Nuxt to ignore any changes in the component. This is kinda painful as I have to keep restart the server, and had to wait 7s for components to be imported.

**Comment by zernonia** [comment]
@danielroe could you share some insight on how to `autoImport` those component that were exported in `index.ts`? Currently the [approach](https://github.com/radix-vue/shadcn-vue/blob/dev/packages/module/src/module.ts#L28-L58) is abit hacky, where we ignore the component dirs, and manually imported it with the help of `ts-morph`.  However that leads to this issue. 🙈

**Comment by danielroe** [comment]
Why don't you just add all the components with `addComponent` and let Nuxt auto-import them as needed?

**Comment by zernonia** [comment]
That's for your reply @danielroe !

Here's some challenges that we faced:
1. Some component were exported from `index.ts` directly, such as 
https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/form/index.ts#L1 , thus Nuxt can't detect them.

2. We have duplicate component if we let Nuxt handle auto-import them.
<img width="594" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/59365435/377275d3-8cdb-48a0-b499-075897da3bf5">


--- 
some of our finding https://github.com/radix-vue/shadcn-vue/issues/172

**Comment by sadeghbarati** [comment]
Since shadcn is about Copy and Paste instead of  Component Library 

It would be better if we solve this without adding another npm package like `shadcn-nuxt`


We just mention how config it with

- `nuxt.config` or
- `modules/shadcn-vue.ts`

Or we could do it with `shadcn-vue` CLI to handle this configurations 👆
