### ISSUE TITLE
[Bug]: Cannot find module 'radix-vue' or its corresponding type declarations

### ISSUE THREAD

**Issue by devberkay** [radix-vue/shadcn-vue#215]
### Environment

```bash
"nuxt": "^3.8.2",
"shadcn-nuxt": "^0.1.0",
"typescript": "^5.3.3",
"vue": "^3.3.12",
"radix-vue": "^1.2.5"
```

### Link to minimal reproduction

No need since folder/linter issue

### Steps to reproduce

Install radix-vue and shadcn-vue following instructions
Download any component using command line ( I have used Button)
`import { Primitive, type PrimitiveProps } from 'radix-vue'` line gives error:

`[Bug]: Cannot find module 'radix-vue' or its corresponding type declarations`

### Describe the bug

"nuxt": "^3.8.2",
"shadcn-nuxt": "^0.1.0",
"typescript": "^5.3.3",
"vue": "^3.3.12",
"radix-vue": "^1.2.5",

Download any component using command line ( I have used Button)

Component script section gives the following error:
`Cannot find module 'radix-vue' or its corresponding type declarations.`

**Comment by devberkay** [comment]
Bug has been fixed when i restarted VS Code.

**Comment by sadeghbarati** [comment]
in VSCode install these two extensions 

1. https://marketplace.visualstudio.com/items?itemName=Vue.volar
2. https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin
3. Disable built-in VSCode TypeScript extensions 

For Volar 2 (not released yet) step 3 is redundant I think xd


---

This is nice extension too

https://marketplace.visualstudio.com/items?itemName=YuTengjing.reload-can-solve-any-problems
