### ISSUE TITLE
[Feature]: Add support for Vue 2.7

### ISSUE THREAD

**Issue by mudassirmaqbool** [radix-vue/shadcn-vue#217]
### Describe the feature

It would be nice have support for vue 2.7.

**Comment by sadeghbarati** [comment]
https://blog.vuejs.org/posts/vue-2-eol



Please don't tell me you guys are using Vue 2.7 
Just because it's called "Naruto" 😁

**Comment by mudassirmaqbool** [comment]
> https://blog.vuejs.org/posts/vue-2-eol
> 
> Please don't tell me you guys are using Vue 2.7 Just because it's called "Naruto" 😁

Well, Unfortunately we are stuck with VueFormulate on one of the projects with over 2000 instances of VueFormulate component. Formulate to FormKit migration is stopping us from the upgrade at the moment. Thanks to vue2.7 we are using composition API and other goodies from vue 3. But for time being it would be great to have some of Shadcn in the project.

**Comment by sadeghbarati** [comment]
RadixVue uses some features that only exist in Vue>3.2 
Also, It would be hard to maintain the project if we add Vue2.7 support not just by the code but even multiple registry theme folders like

- default-vue3
- default-vue2.7
- new-york-vue3
- new-york-vue2.7

Please head to this npm package 👇 it uses the API/features that exist in Vue2.6, 2.7, and 3.2
Go to the `src/component` folder 😨 it uses `vue-demi` but it is still hard to support all those versions at once

https://www.npmjs.com/package/@smooth-scrollbar-contrib/vue-test?activeTab=code
