### ISSUE TITLE
How do I export the buttonVariants to another Vue component in Nuxt 3?

### ISSUE THREAD

**Issue by endan-917v** [radix-vue/shadcn-vue#218]
https://www.shadcn-vue.com/docs/components/button.html

In the React version of the library, you can import `buttonVariants` to other components. 
Is there a way to do that in Nuxt 3? 
It seems like you can't export in the `script setup` tag either.

**Comment by nikuscs** [comment]
My recommendation is to detach the styles yourself into a separate file, i usually create a design.ts file with the cva/cv defenitions there, so its way more portable

**Comment by endan-917v** [comment]
Thank you for your reply! I did that instead. 👍
