### ISSUE TITLE
[Bug]: Safari browser v17.0 <Button> mouseEvents are not triggered

### ISSUE THREAD

**Issue by devberkay** [radix-vue/shadcn-vue#219]
### Environment

```bash
"nuxt": "^3.8.2",
"shadcn-nuxt": "^0.1.0",
"typescript": "^5.3.3",
"vue": "^3.3.12",
"radix-vue": "^1.2.5",
Safari Version 17.0
```

### Link to minimal reproduction

Easy to reproduce based on title and description

### Steps to reproduce

Easy to reproduce based on title and description

### Describe the bug

<Button> component doesn't trigger the mouse events on Safari 17.0 (v-on:click, v-on:mouseenter, v-on:mouseleave)

### Expected behavior

Any other browser is working properly. Safari should too.

**Comment by sadeghbarati** [comment]
Can you share a record? it works on Safari 16

https://github.com/radix-vue/shadcn-vue/assets/17789047/f4b2df0f-0b94-4a60-bc09-13ff61339288

**Comment by devberkay** [comment]
ah shoot!, i've already updated my mac before seeing your answer @sadeghbarati , Now the Safari also updated to 17.2.1 and it works without a problem.

**Comment by devberkay** [comment]
For some reason it occurred on Safari v17.2.1 too but i did `bun run build` and `bun run dev` and it got fixed.
