### ISSUE TITLE
[Feature]: Drawer, Carousel, Sonner & Resizable

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#220]
### Describe the feature

New component! 

https://twitter.com/shadcn/status/1738283281424982488

- [x] #370
- [x] [Vue Sonner](https://vue-sonner.vercel.app/) https://github.com/radix-vue/shadcn-vue/issues/254
- [x] [Vue Embla Carousel](https://www.embla-carousel.com/get-started/vue/)
- [x]  [SplitPane Resizable](https://github.com/antoniandre/splitpanes) (might be replace by https://github.com/radix-vue/radix-vue/issues/401 in the future)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by wasimTQ** [comment]
@zernonia I'd like to attempt implementing any one of these

**Comment by sadeghbarati** [comment]
@wasimTQ Thanks for your contribution 👍 

Just create a separate issue per component we will assign it to you

**Comment by wasimTQ** [comment]
@sadeghbarati I'll start off with the carousel

**Comment by Elliot-Alexander** [comment]
I've started looking at porting Vaul to Vue, first time doing something like this so will update with progress

**Comment by connerblanton** [comment]
@Elliot-Alexander and anyone else interested - I have also started porting Vaul to Vue. It's also the first time I have attempted anything like this so not entirely sure what I'm doing 😅. 

It is still very much a work in progress but it is currently functional.

Repo - https://github.com/connerblanton/vue-vaul

Feel free to fork it, make PRs, use it as a reference or whatever you feel like. I am very interested in getting this ported to Vue and don't care if it's my repo, yours, or someone else's. Just excited for all of us to get something working and to see what we can build together 😀

**Comment by Elliot-Alexander** [comment]
This looks really good, will definitely use this a reference / raise some PRs, just to refactor things to make them a bit more 'library' style. I wonder if it's worth creating a `vaul-vue` repo under the `radix-vue` org?

**Comment by connerblanton** [comment]
Perfect! I agree that it would be ideal if this package was under the `radix-vue` org. I wasn't sure if they were working on it or not, but after I saw your comment, I decided to share what I have so far to see if it would help anyone

**Comment by zernonia** [comment]
Love the initiative @connerblanton  @Elliot-Alexander  💚... We are glad to have the package move under `radix-vue` if you guys don't mind it  😁

**Comment by connerblanton** [comment]
@zernonia I don't mind at all!

Like I mentioned above, I have no experience with building a package from scratch, so I just started building in the quickest way I knew how.

Not sure how you want to move it. If you want me to transfer ownership of what I have, I can do that. But also completely understand if you want to start with a fresh repo. Just let me know 😀

**Comment by Elliot-Alexander** [comment]
Just had a look also, the `vaul-vue` package name is taken (as well as `vue-vaul` 😓). I wonder if it's worth setting up a package scope for packages maintained under Radix-vue?

**Comment by zernonia** [comment]
Yup @Elliot-Alexander . I've been thinking of rebranding the `radix-vue` organization instead something else, then we can setup package scope for all the packages we maintained.

The reason is that we might have packages that are not really connected to "Radix" in the future

**Comment by Elliot-Alexander** [comment]
Yeah, personally really like that idea, particularly as feature parity is maintained with shadcn/ui I think it will be important to have somewhere ported packages can be published.

I have just pushed a cleaned version of the work as a monorepo, with playground and refactored a few types from @connerblanton work. 

https://github.com/Elliot-Alexander/vaul-vue

**Comment by wasimTQ** [comment]
Does anyone started working on `vaul-vue`? Can you mention the repo where everyone can collaborate. 

I do plan to work on the `resizable` component next tho.

The `vue-sonner` package needs some work as far as I know.

**Comment by connerblanton** [comment]
@wasimTQ we are currently working on `vaul-vue` in the https://github.com/Elliot-Alexander/vaul-vue repo 😀

**Comment by xiaoluoboding** [comment]
Any one working on `vue-sonner` here?

Maybe I can integrate it into `shadcn-vue`.

**Comment by valentinhttr** [comment]
I'm so excited to have the Drawer, congratulations on your work @Elliot-Alexander @connerblanton 🚀

**Comment by zernonia** [comment]
@xiaoluoboding  I believe you can integrate `vue-sonner` with `shadcn-vue`! Feel free to create an issue with the PR ya 😁

**Comment by Elliot-Alexander** [comment]
The first release of `vaul-vue` is available. It's definitely still a little rough but please feel free to give it a try.

**Comment by tylerprimmer** [comment]
> The first release of `vaul-vue` is available. It's definitely still a little rough but please feel free to give it a try.

Incredible! Any support for Nuxt in the future?

**Comment by lucascnunes** [comment]
When is Drawer going to be added to shadcn-vue? 🥸

Edit:: thank you guys! It was added https://www.shadcn-vue.com/docs/components/drawer.html

**Comment by sadeghbarati** [comment]
"Thank You All" For Your Contributions ❤️
