### ISSUE TITLE
[Bug]: toggle not setting pressed property on init

### ISSUE THREAD

**Issue by agnauck** [radix-vue/shadcn-vue#221]
### Environment

```bash
Node version: 16.0.0
Package manager: npm
Radix Vue version: 1.2.5
Shadcn Vue version: 0.8.5
Vue version: 3.3.11
CSS framework: tailwindcss@3.4.0
```

### Link to minimal reproduction

https://github.com/agnauck/shadcn-vue-toggle-bug

### Steps to reproduce

1. clone https://github.com/agnauck/shadcn-vue-toggle-bug
2. npm run dev
3. Toggle should be pressed on startup, see also `area-pressed` and `data-state` css attributes

### Describe the bug

Toggle Buttons do not initialize the pressed property correctly.

### Expected behavior

 The toggle should initialize correctly when the pressed property is set to true. I always initialized false (undefined)

**Comment by sadeghbarati** [comment]
Yes this indeed a bug, Wrapper Component can't pass props and emits properly
~~I think it's related to `useForwardPropsEmits` function~~ `useForwardPropsEmits` is working fine the problem was

```diff
- const forwarded = useForwardPropsEmits(toggleProps, emits);
+ const forwarded = useForwardPropsEmits(toggleProps.value, emits);
```

~~I think it's better to get rid of `emits` and add emits as `props` 😩~~
See this [discord message ](https://discord.com/channels/1121805548782878813/1188378401283780698/1189025614699712552)

For now replace your Toggle code with this

<details><summary>Toggle code</summary>
<p>

```vue
<script setup lang="ts">
import type { ToggleEmits, ToggleProps } from 'radix-vue'
import { Toggle, useEmitAsProps } from 'radix-vue'
import type { VariantProps } from 'class-variance-authority'
import { toggleVariants } from '.'
import { cn } from '@/lib/utils'

interface ToggleVariantProps extends VariantProps<typeof toggleVariants> {}

interface Props extends ToggleProps {
  variant?: ToggleVariantProps['variant']
  size?: ToggleVariantProps['size']
  disabled?: boolean
}
const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  size: 'default',
  disabled: false,
})
const emits = defineEmits<ToggleEmits>()
const emitsAsProps = useEmitAsProps(emits)
</script>

<template>
  <Toggle
    v-bind="{
      ...props,
      ...emitsAsProps,
    }"
    :class="cn(toggleVariants({ variant, size, class: $attrs.class ?? '' }))"
    :disabled="props.disabled"
  >
    <slot />
  </Toggle>
</template>
```

</p>
</details>

**Comment by zernonia** [comment]
@sadeghbarati  We can always link the related issue back to `radix-vue`, and we can fix the upstream issue there 😁
