### ISSUE TITLE
[Bug]: CVA styling changes don't get applied without a server restart

### ISSUE THREAD

**Issue by titusdecali** [radix-vue/shadcn-vue#222]
### Environment

```bash
Development/Production OS: Mac Ventura 13.6
Node version: v21.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: (shadcn-nuxt) 0.1.0
Vue version: 3.3.13
Nuxt version: 3.9.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@6.10.1
```

### Link to minimal reproduction

local server required

### Steps to reproduce

-Start a new Nuxt project
-Install all shadcn requirements
-install a button component using CLI
-start local live server
-change the button/index.ts -> CVA styles (any)
-watch the browser and see that nothing has changed after hard browser refresh
-restart server
-confirm that changes are now live in the browser

### Describe the bug

I am unable to update CVA styling without having to also restart my local server for the changes to take effect.
Other changes to templates, etc, do take affect as expected. It only seems to be CVA which doesn't update.

I don't see any similar github issue on CVA's repo, so I assume it's something about the Shadcn config, though I haven't seen others mention this here, so I'm a bit stumped. I previously used CVA in a Next.js project, and remember sometimes having similar issues, though it was intermittent as far as I can recall.

I've followed the Shadcn guide step by step, and have even started a new project as I thought maybe my initial JS (non-TS) project was the issue, but even with a fresh TS installation of Nuxt, the result is the same. I also tried wrapping components in `<ClientOnly>` tags, but no change.

If you could suggest anything I might check to resolve this, it would be appreciated.

### Expected behavior

CVA style changes shouldn't require a server restart to take affect

**Comment by sadeghbarati** [comment]
Are you using `shadcn-nuxt`?

**Comment by sadeghbarati** [comment]
@titusdecali 

Thanks for the report, It kinda related to `shadcn-nuxt` #214 
Which Zernonia will ~~deprecates it~~ fix it

---

You can check this StackBlitz 
https://stackblitz.com/edit/github-xkryhq-egbi1f?file=modules%2Fshadcn-vue.ts,nuxt.config.ts


<details><summary>Nuxt >= 3.9</summary>
<p>

#### `modules/shadcn-vue.ts` 

It only works in Nuxt >= 3.9 cause the `addComponentsDir` **prepend** option does not exist in older versions

```ts
import {
  defineNuxtModule,
  addComponent,
  addComponentsDir,
  tryResolveModule,
} from 'nuxt/kit';

export interface ShadcnVueOptions {
  /**
   * Prefix for all the imported component
   */
  prefix: string;

  /**
   * Directory that the component lives in.
   * @default "~/components/ui"
   */
  componentDir: string;
}

export default defineNuxtModule<ShadcnVueOptions>({
  defaults: {
    prefix: 'Ui',
    componentDir: '~/components/ui',
  },
  meta: {
    name: 'ShadcnVue',
    configKey: 'shadcn',
    version: '0.0.1',
    compatibility: {
      nuxt: '^3.9.0',
      bridge: false,
    },
  },
  async setup({ componentDir, prefix }) {
    const isVeeValidateExist = await tryResolveModule('vee-validate');

    addComponentsDir(
      {
        path: componentDir,
        extensions: ['.vue'],
        prefix,
        pathPrefix: false,
      },
      {
        prepend: true,
      }
    );

    if (isVeeValidateExist !== undefined) {
      addComponent({
        filePath: 'vee-validate',
        export: 'Form',
        name: `${prefix}Form`,
        priority: 999,
      });

      addComponent({
        filePath: 'vee-validate',
        export: 'Field',
        name: `${prefix}FormField`,
        priority: 999,
      });
    }

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationRoot',
      name: `${prefix}Pagination`,
      priority: 999,
    });

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationList',
      name: `${prefix}PaginationList`,
      priority: 999,
    });

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationListItem',
      name: `${prefix}PaginationListItem`,
      priority: 999,
    });
  },
});

declare module '@nuxt/schema' {
  interface NuxtConfig {
    shadcn?: ShadcnVueOptions;
  }
  interface NuxtOptions {
    shadcn?: ShadcnVueOptions;
  }
}

```

</p>
</details> 

<details><summary>Nuxt < 3.9</summary>
<p>

#### `modules/shadcn-vue.ts` 

Add components dir with `hooks` option `components:dirs` which can't be dynamic like setup section

```ts
import {
  defineNuxtModule,
  addComponent,
  addComponentsDir,
  tryResolveModule,
} from 'nuxt/kit';

export interface ShadcnVueOptions {
  /**
   * Prefix for all the imported component
   */
  prefix: string;

  /**
   * Directory that the component lives in.
   * @default "~/components/ui"
   */
  componentDir: string;
}

export default defineNuxtModule<ShadcnVueOptions>({
  defaults: {
    prefix: 'Ui',
    componentDir: '~/components/ui',
  },
  meta: {
    name: 'ShadcnVue',
    configKey: 'shadcn',
    version: '0.0.1',
    compatibility: {
      nuxt: '^3.0.0',
      bridge: false,
    },
  },
  hooks: {
   // hooks option is can't be dynamic like setup section
    "components:dirs": (dirs) {
      dirs.unshift({
        path: '~/components/ui',
        extensions: ['.vue'],
        prefix: 'Ui',
        pathPrefix: false,
      })
    }
  },
  async setup({ componentDir, prefix }) {
    const isVeeValidateExist = await tryResolveModule('vee-validate');

    if (isVeeValidateExist !== undefined) {
      addComponent({
        filePath: 'vee-validate',
        export: 'Form',
        name: `${prefix}Form`,
        priority: 999,
      });

      addComponent({
        filePath: 'vee-validate',
        export: 'Field',
        name: `${prefix}FormField`,
        priority: 999,
      });
    }

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationRoot',
      name: `${prefix}Pagination`,
      priority: 999,
    });

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationList',
      name: `${prefix}PaginationList`,
      priority: 999,
    });

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationListItem',
      name: `${prefix}PaginationListItem`,
      priority: 999,
    });
  },
});

declare module '@nuxt/schema' {
  interface NuxtConfig {
    shadcn?: ShadcnVueOptions;
  }
  interface NuxtOptions {
    shadcn?: ShadcnVueOptions;
  }
}

```

</p>
</details>

**Comment by zernonia** [comment]
It's due to the module having `ignorePath` in `components/ui`, thus the HMR doesn't work until server restart.

@sadeghbarati  I dun quite understand why deprecate it? We just need to fix the above issue and it will all be good. And in future we can directly use `withDefault` utility from "radix-vue" to apply default props and stylign without creating more and more `.vue` file.

**Comment by titusdecali** [comment]
>  I dun quite understand why deprecate it?

I think he meant "replicated" instead of "deprecated".

**Comment by titusdecali** [comment]
> I dun quite understand why deprecate it?

I think he meant that you "replicated" the issue, instead of "deprecate"

**Comment by sadeghbarati** [comment]
@zernonia 

I meant this https://github.com/radix-vue/shadcn-vue/issues/214#issuecomment-1863361722

People want to have less dependency in their package.json, or perhaps offer two way to the user

1. `shadcn-nuxt`
2. manual configuration in `modules/shadcn-vue.ts`

**Comment by titusdecali** [comment]
@zernonia Is there an interim solution I can use before this is fixed to get HMR working? I didn't find `ignorePath` anywhere... not sure what to change.

**Comment by zernonia** [comment]
> @titusdecali
> 
> Thanks for the report, It kinda related to `shadcn-nuxt` #214 Which it's better Zernonia deprecates it
> 
> You can check this StackBlitz https://stackblitz.com/edit/github-xkryhq-egbi1f?file=modules%2Fshadcn-vue.ts,nuxt.config.ts
> 
> Nuxt >= 3.9
> Nuxt < 3.9

@titusdecali  this should works well 😁
