### ISSUE TITLE
[Bug]: Toast not showing in StackBlitz/CodeSandbox playgrounds

### ISSUE THREAD

**Issue by GasperVrh** [radix-vue/shadcn-vue#232]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/tdkd3r?file=src%2FApp.vue

### Steps to reproduce

Code from examples

### Describe the bug

Toast not visible

### Expected behavior

Toast should be visible upon click

**Comment by sadeghbarati** [comment]
Toast example is missing `<Toaster />` component in root of the application like `App.vue`

Some of the doc examples (reproduction buttons) are not complete cause it's based on registry example code contents 
Will check how to include missing steps in Stackblitz and CodeSandboxes

**Comment by sadeghbarati** [comment]
@zernonia Remember [this PR](https://github.com/radix-vue/shadcn-vue/pull/131) I thought my local was the same as the production environment? xd

I think I could fix this issue with `manifest.json` generated by Vite but now I'm thinking again `manifest.json` refers to a compiled version of examples which we can't use in Stackblitzs

Do you have any tips? Maybe migrating to Nuxt would help us

**Comment by sadeghbarati** [comment]
https://github.com/radix-vue/shadcn-vue/pull/642

This PR fixed Navigation Menu Stackblitz demo but Toast still needs Toaster component
