### ISSUE TITLE
[Feature]: Doc section about how to toggle theme 

### ISSUE THREAD

**Issue by devberkay** [radix-vue/shadcn-vue#236]
### Describe the feature

I can't find out implementation of how to toggle between light-dark theme from documentation, would be helpful for rookies

**Comment by zernonia** [comment]
Make sense 👍🏻 I tried using `shadcn-vue` in other project and realized this missing instruction too. 
We can add `Dark mode` page similar to original `ui.shadcn`

https://ui.shadcn.com/docs/dark-mode

**Comment by MuhammadM1998** [comment]
@zernonia Can I suggest adding a version switcher for Vue, Nuxt, Astro and other integerations ? like the Options API <--> Composition API one in the vue docs.

I've tried to use the module in a nuxt project and not all the instructions fully apply to nuxt

**Comment by devberkay** [comment]
Leaving a reference for future visitors, how i've setup:

Using color-mode nuxt module: [https://nuxt.com/modules/color-mode](url)

Refer to following video, if u can't setup: [https://www.youtube.com/watch?v=aPdDUMuxmEw](url)

**Comment by TheDutchDev** [comment]
> Leaving a reference for future visitors, how i've setup:
> 
> Using color-mode nuxt module: [https://nuxt.com/modules/color-mode](url)
> 
> Refer to following video, if u can't setup: [https://www.youtube.com/watch?v=aPdDUMuxmEw](url)

How exactly do you do this without nuxtJS?

**Comment by devberkay** [comment]
@TheDutchDev 

I am not an expert but you can check out vueuse: [https://vueuse.org/core/useColorMode/](url)
