### ISSUE TITLE
[Bug]: Form validation bug when interacting with the dialog component

### ISSUE THREAD

**Issue by w2ca** [radix-vue/shadcn-vue#237]
### Environment

```bash
Developement/Production OS: Ubuntu 22.04.3 LTS
Node version: v19.9.0
Package manager: pnpm@8.11.0
Radix Vue version: 1.2.4
Shadcn Vue version: 0.8.6
Vue version: 3.3.11
CSS framework: tailwindcss@3.4.0
Client OS: Ubuntu 22.04.3 LTS
Browser: Brave Browser 120.1.61.109
```

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-wukzt2

### Steps to reproduce

**Reproduce when click close button**

1° - Click on "edit profile" to open dialog
2° - Click on close button the dialog in the upper right corner

 **Reproduce when click in anywhere dialog body**
1° - Click on "edit profile" to open dialog
2° - Click click in anywhere dialog body

 **Reproduce when switch window**
1° - Click on "edit profile" to open dialog
2° - switch windows without interacting with the dialog

### Describe the bug

Form validation bug when interacting with the dialog component by pressing Tab, clicking the dialog body or the close dialog button. It seems that when I do one of these actions it is as if I were clicking submit

Toast didn't work either for some reason.

### Expected behavior

The form should not validate the form if I don't fill it out or click the submit button. It is validating when I do any action. Without even interacting with the inputs.

**Comment by sadeghbarati** [comment]
`vee-validate` behavior is different than `react-hook-form`

`vee-validate` is more aggressive and runs on `blur`, `change`, `input`, `v-model update` you have to configure the behaviour with 

- [`configure` composable](https://vee-validate.logaretm.com/v4/api/configuration/) 
- [`FormField` props](https://vee-validate.logaretm.com/v4/api/field/#props) like **`:validateOnBlur="false"`**

---


Also `radix-vue` Dialog will focus the first focusable element when Dialog is open so onBlur will call the validation function
You can **prevent** `auto-focus` with this event on `DialogContent` component

```html
<DialogContent class="sm:max-w-[425px]" @openAutoFocus.prevent>
```

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/vitejs-vite-a1gaan?file=src%2FApp.vue

**Comment by sadeghbarati** [comment]
Man we need more documentation on shadcn-vue

**Comment by WDaan** [comment]
@sadeghbarati Thanks, that helped me
