### ISSUE TITLE
[Feature]: Trailing text before/after user-input text in <Input> component

### ISSUE THREAD

**Issue by titusdecali** [radix-vue/shadcn-vue#240]
### Describe the feature

There are many cases where trailing (read-only) text before or after user-inputted values are needed.
In my case, I want to allow the user to preview how their new subdomain and slug will look.

**Basic Usage:**
`<Input trailingText=".kmpfr.co" ...>
![SHOT 13 46 50@2x](https://github.com/radix-vue/shadcn-vue/assets/4532534/e0c6819a-f099-4429-984f-91811167ed6b)

**with `placeBefore`**
`<Input trailingText="company.kmpfr.co/" placeBefore ...>
![SHOT 13 45 11@2x](https://github.com/radix-vue/shadcn-vue/assets/4532534/e1ce1ac9-d977-4d2d-b76e-484dc550c26f)

- For my specific case, I've modified the `<Input />` component to fit my needs, 
however if added as a feature I suspect there are more generic ways to implement this.

**Here is my implementation if anyone else needs it**
```
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { useVModel } from '@vueuse/core'
import { cn } from '@/lib/utils'

const props = defineProps<{
  defaultValue?: string | number
  modelValue?: string | number
  class?: HTMLAttributes['class']
  trailingText?: string
  preventSpaces?: boolean
  placeBefore?: boolean
}>()

const emits = defineEmits<{
  (e: 'update:modelValue', payload: string | number): void
}>()

const modelValue = useVModel(props, 'modelValue', emits, {
  passive: true,
  defaultValue: props.defaultValue
})

const displayValue = computed(() =>
  props.modelValue !== undefined ? props.modelValue : ''
)

watch(
  modelValue,
  (newValue) => {
    if (props.preventSpaces && typeof newValue === 'string') {
      const sanitizedValue = newValue.replace(/[^a-zA-Z0-9]/g, '').toLowerCase()
      if (sanitizedValue !== newValue) {
        modelValue.value = sanitizedValue
      }
    }
  },
  { deep: true }
)

// Correct spacing when placeBefore is true
const placeBeforeSpacer = computed(() =>
  props.trailingText?.length && props.placeBefore
    ? `calc(${Number(props.trailingText?.length) - 1 + 'ch'} - 3px`
    : ''
)
</script>

<template>
  <div class="relative">
    <!-- Conditionally render trailingText before or after user input -->
    <template v-if="props.trailingText">
      <span
        v-if="props.placeBefore"
        class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none text-gray-400">
        {{ props.trailingText }}
      </span>

      <span
        v-else
        class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none text-gray-400">
        <!-- Hidden displayValue for spacing -->
        <span class="opacity-0">{{ displayValue }}</span>
        <span class="ml-[1px]">{{ props.trailingText }}</span>
      </span>
    </template>

    <!-- User input -->
    <input
      v-model="modelValue"
      :style="{ paddingLeft: placeBeforeSpacer }"
      :class="
        cn(
          'flex h-11 w-full rounded-sm border border-input bg-transparent pl-3 py-2 text-md ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
          props.class
        )
      " />
  </div>
</template>

```

### Additional information

- [ ] I intend to submit a PR for this feature.
- [x] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Nice, thanks for sharing 

I'm gonna refactor all components to use `class` as props, destructuring `attrs` was my idea but it led to attrs being **not** reactive after the first render

please take your time and refactor your input component based on the source

https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/input/Input.vue

also, I forgot to remove Nullish Operator in that PR, so for now remove it yourself

```diff
- props.class  ?? ''
+ props.class
```

**Comment by titusdecali** [comment]
@sadeghbarati I've updated my component to match your changes, and I've also added a `placeBefore` prop to handle that use case.

**Comment by sadeghbarati** [comment]
Thanks for the tip 😁👍 

https://github.com/radix-vue/shadcn-vue/discussions/316#discussioncomment-8361177
