### ISSUE TITLE
[Feature]: Add style to work with v-calendar time picker

### ISSUE THREAD

**Issue by valentinhttr** [radix-vue/shadcn-vue#243]
### Describe the feature

Hi,

Would it be possible to [add a minimum of style](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/calendar/Calendar.vue#L93) to be able to use the `datetime` mode of the underlying `v-calendar` library please?

Here's what a datetime field looks like, according to the `v-calendar` documentation:

![CleanShot 2024-01-05 at 13 20 37](https://github.com/radix-vue/shadcn-vue/assets/20521112/cf626311-315a-467a-bdbb-d722b621fae6)

With shadcn-vue, however, the inputs are one after the other, making them very difficult for the user to read:

![CleanShot 2024-01-05 at 13 21 41](https://github.com/radix-vue/shadcn-vue/assets/20521112/1c9bac15-6470-48ec-896a-9b9bd601bf97)

### Additional information

- [x] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by valentinhttr** [comment]
@sadeghbarati Do you have an idea of what the design should look like? I can implement this feature

**Comment by sadeghbarati** [comment]
Same as v-calendar but with shadcn style but it's ok if you use native selectbox too

**Comment by Kuba-Kajderowicz** [comment]
when in mode="date" you cannot actually click on the month to select month / year.

**Comment by valentinhttr** [comment]
> when in mode="date" you cannot actually click on the month to select month / year.

Thanks for your feedback, but what does this feature request have to do with it? Indeed, it only concerns the `datetime` or `time` mode.

Maybe it's worth opening a new issue?

**Comment by valentinhttr** [comment]
Hi @sadeghbarati,
I'd like to migrate to the new radix-vue component and drop v-calendar, but is it possible to have a `DateTimeRangPicker` component?

I need to select an arrival and departure date**TIME**.
