### ISSUE TITLE
[Bug]: when I npx shadcn-vue@latest init, I did not see the option to select global CSS

### ISSUE THREAD

**Issue by xiangrikuil** [radix-vue/shadcn-vue#247]
### Environment

```bash
Developement/Production OS: macOS 14.0
Node version: 20.9.0
Package manager: npm@9.8.1
Shadcn Vue version: 1.2.6
Vue version: 3.3.9
CSS framework: tailwindcss@3.4.1
Client OS: macOS 14.0
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/shadcn-test-46j64s?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr21wyff00073b6m6o1zqv40%2522%252C%2522sizes%2522%253A%255B53.333333333333336%252C46.666666666666664%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr21wyff00023b6mvauvy70e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr21wyff00043b6mwutt3cua%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr21wyff00063b6m0295vayk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr21wyff00023b6mvauvy70e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr21wyff00013b6m62b8mq4p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr21wyff00023b6mvauvy70e%2522%252C%2522activeTabId%2522%253A%2522clr21wyff00013b6m62b8mq4p%2522%257D%252C%2522clr21wyff00063b6m0295vayk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr21wyff00053b6me7gin9b3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr21wyff00063b6m0295vayk%2522%252C%2522activeTabId%2522%253A%2522clr21wyff00053b6me7gin9b3%2522%257D%252C%2522clr21wyff00043b6mwutt3cua%2522%253A%257B%2522id%2522%253A%2522clr21wyff00043b6mwutt3cua%2522%252C%2522activeTabId%2522%253A%2522clr21y499004x3b6m3xl2ajg3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr21wyff00033b6mky51lffu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522clr21y499004x3b6m3xl2ajg3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr21y4fq00agechu0x7b0lbb%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

in terminal input
```
npx shadcn-vue@latest init
```

### Describe the bug

I did not see the option "Where is your global CSS file? › › src/index.css"
<img width="632" alt="codesanx" src="https://github.com/radix-vue/shadcn-vue/assets/80461300/4ca86c77-f216-4ac7-9827-e777b8e75473">

### Expected behavior

can see the option "Where is your global CSS file? › › src/index.css"

**Comment by sadeghbarati** [comment]
`shadcn-ui`: Where is your global CSS file? ›  src/assets/index.css

`shadcn-vue`: Where is your Tailwind CSS file? … src/assets/index.css

---

https://github.com/radix-vue/shadcn-vue/commit/989c0e20245bcf27f943a09eceb8d60bf22df916

I don't noticed this whole time xd

**Comment by xiangrikuil** [comment]
> `shadcn-ui`: Where is your global CSS file? › src/assets/index.css
> 
> `shadcn-vue`: Where is your Tailwind CSS file? … src/assets/index.css
> 
> [989c0e2](https://github.com/radix-vue/shadcn-vue/commit/989c0e20245bcf27f943a09eceb8d60bf22df916)
> 
> I don't noticed this whole time xd

Also, there are errors in the document. [https://www.shadcn-vue.com/docs/installation/vite](https://www.shadcn-vue.com/docs/installation/vite)   
In the sixth section. 6.Configure components.json

**Comment by sadeghbarati** [comment]
@xiangrikuil 

CLI global CSS option should be fixed after new release 

Also I didn't get it (6.Configure components.json)

feel free to make PR or add suggestions here

**Comment by sadeghbarati** [comment]
![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/ec57cb43-b397-487a-b9d4-ea1442e886c6)
