### ISSUE TITLE
[Feature]: New York style components

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#25]
### Describe the feature

Currently we have only the `default` style for components. `Shadcn UI` also provides "New York" style.
Let's add them into `apps/www/src/lib/registry/new-york/ui/...`

### Additional information

- [x] I intend to submit a PR for this feature.
- [x] I have already implemented and/or tested this feature.

**Comment by ahmedmayara** [comment]
I'll add most of the components today.

**Comment by zernonia** [comment]
Thank you @ahmedmayara ! 😁

**Comment by ahmedmayara** [comment]
Hello! @zernonia, I just completed all the components in the `new york` style, you can merge it with the rest of the work 😃
