### ISSUE TITLE
[Feature]: Sonner component

### ISSUE THREAD

**Issue by xiaoluoboding** [radix-vue/shadcn-vue#254]
### Describe the feature

Create a `sonner` component using the [vue-sonner](https://github.com/xiaoluoboding/vue-sonner) library

Part of https://github.com/radix-vue/shadcn-vue/issues/220

### Additional information

- [x]  I intend to submit a PR for this feature.
- [x]  I have already implemented in `vue-sonner`
- [x]  I will integrate into `shadcn-vue`

**Comment by sadeghbarati** [comment]
❤️‍🔥
