### ISSUE TITLE
[Bug]: Error when trying to run init command

### ISSUE THREAD

**Issue by KonradHEXANT** [radix-vue/shadcn-vue#258]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

localhost

### Steps to reproduce

Run shadcn-vue init with the latest Nuxt.

### Describe the bug

Error is thrown during the "installing dependencies" process and then Nuxt then won't run dev or build with the same error:
![image](https://github.com/radix-vue/shadcn-vue/assets/17060750/43ad393b-e57d-43b0-82ac-0c08a2533e0b)

**Comment by sadeghbarati** [comment]
latest `Vite` and `Nuxt` minimum `node` version is **^18.0.0** and **>=20.0.0**

Can you try with new node version

**Comment by KonradHEXANT** [comment]
Don know why Github etered those infos by themself, but i didn't even check it assuming it was right - my bad.
Nuxt info:
Nuxt project info:                                                                                            10:39:58

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     ^3.9.1
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, build, css, app
- Runtime Modules:  @pinia/nuxt@^0.5.1, @nuxtjs/tailwindcss@^6.10.4, nuxt-headlessui@^1.1.5
- Build Modules:    -
------------------------------

So Node is v20

**Comment by KonradHEXANT** [comment]
I've deleted `node_modules` folder and `yarn.lock` file and run clean install. All working fine now. Sorry for false alarm.

**Comment by sadeghbarati** [comment]
Great, I was trying to install yarn classic to test xd

BTW why not Yarn 4? why everyone stick to v1
