### ISSUE TITLE
[Feature]: add UnoCss support dirrectly in CLI 

### ISSUE THREAD

**Issue by HugoSbl** [radix-vue/shadcn-vue#261]
There is more and more peoples using unoCss, and it's honnestly kind of trouble to adapt it to shadcn. 
Anyway, i haven't succeded... but the project is huge and already has a lot of trouble configuration, so i guess it would be a lot simpler for new projects.

UnoCSS is growing everyday, it would be so cool to see it integrate simply with shadcn for vue.

**Comment by sadeghbarati** [comment]
It's on other maintainers roadmap for sure

https://github.com/radix-vue/shadcn-vue/issues/34


---

For test UnoCSS manually you can refer to these repositories before it's supported in CLI

- https://github.com/fisand/unocss-preset-shadcn
- https://github.com/hyoban/unocss-preset-shadcn

**Comment by HugoSbl** [comment]
I already tested that, but as i'm having kind of complex configuration of uno css on my project, linked to another custom lib from my company, the custom preset for shadcn just broked my entire application. 

But for new project, installing it via CLI with unoCSS would be just perfect.
