### ISSUE TITLE
[Bug]: Popover max-height need to be limited by available height

### ISSUE THREAD

**Issue by hrynevychroman** [radix-vue/shadcn-vue#263]
### Environment

```bash
Main Website
```

### Link to minimal reproduction

https://www.shadcn-vue.com/examples/cards

### Steps to reproduce

Just open Year Select on left card

<img width="1686" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/82209198/28f3a196-517e-44a1-aeb0-ebca4200e874">

### Describe the bug

Select don't limit by available height 🙂 

### Expected behavior

Need to add height, or max-height (think that max-height is better) to popover element, so scroll will be shown

<img width="1687" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/82209198/74337643-52de-4e22-9a9b-0d3fefd892b6">

**Comment by hrynevychroman** [comment]
I will make PR to fix this issue 🙂

**Comment by sadeghbarati** [comment]
Great, Thanks 🙌

**Comment by hrynevychroman** [comment]
@sadeghbarati sorry for tagging you, but I don't familiar with GitHub (working on GitLab mostly), how can I push new branch with PR, I don't have permissions( Maybe you can give me some guide how to make PR rightly)

<img width="577" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/82209198/59c1fea9-0cd2-4a8d-a39c-d1cbe61a2376">

**Comment by sadeghbarati** [comment]
Fork the repository -> go to the main page of the repository -> top-right -> left side of the start button

Now you have your own (origin) which you can push a new branch to it, without affecting (upstream) repository which also you have no permission but it's better to work on your origin even if you have permission 

You can use `VSCode` or `Git CLI` or `Git GUI` Apps like **GitHub Desktop**, **SourceTree**, **GitKraken**, ...

**Comment by hrynevychroman** [comment]
@sadeghbarati Thank you! ❤️ 

> Fork the repository -> go to the main page of the repository -> top-right -> left side of the start button
> 
> Now you have your own (origin) which you can push a new branch to it, without affecting (upstream) repository which also you have no permission but it's better to work on your origin even if you have permission
> 
> You can use `VSCode` or `Git CLI` or `Git GUI` Apps like **GitHub Desktop**, **SourceTree**, **GitKraken**, ...
