### ISSUE TITLE
[Feature]: The Calendar component should inherits the VCalendar slots

### ISSUE THREAD

**Issue by valentinhttr** [radix-vue/shadcn-vue#268]
### Describe the feature

Hi,

The following VCalendar slots are currently available: https://github.com/nathanreyes/v-calendar/blob/v3.1.2/src/components/Calendar/CalendarSlot.vue#L16-L28

However, it is not possible to pass them directly to the `Calendar` component.

This feature request asks for the same slots to be available and passed directly to the VCalendar child component.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by Tajcore** [comment]
Looking forward to see this implemented 🙏🏾
