### ISSUE TITLE
[Bug]: Nuxt shadcn error in nuxt.config.ts

### ISSUE THREAD

**Issue by hrynevychroman** [radix-vue/shadcn-vue#270]
### Environment

```bash
Developement/Production OS: MacOS Sonoma 14.1.2
Node version: 20.9.0
Package manager: pnpm@8.12.1
Radix Vue version: 1.3.0
Shadcn Vue version: 0.8.7
Vue version: 3.4.10
Nuxt version: 3.9.1
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.4.1
Client OS: MacOS Sonoma 14.1.2
Browser: -
```

### Link to minimal reproduction

[link](https://codesandbox.io/p/devbox/shadcn-vue-nuxt-864dkv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrbyu1t200063b6ef820dihg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrbyu1t200023b6ep4ycexdq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrbyu1t200043b6emsus3evs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrbyu1t200053b6eszz7nfes%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrbyu1t200023b6ep4ycexdq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrbyu1t100013b6et9vjk0ja%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clrbyu1t200023b6ep4ycexdq%2522%252C%2522activeTabId%2522%253A%2522clrbyu1t100013b6et9vjk0ja%2522%257D%252C%2522clrbyu1t200053b6eszz7nfes%2522%253A%257B%2522id%2522%253A%2522clrbyu1t200053b6eszz7nfes%2522%252C%2522activeTabId%2522%253A%2522clrbyux3e008l3b6ejdudifeh%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clrbyux3e008l3b6ejdudifeh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrbyu1t200043b6emsus3evs%2522%253A%257B%2522id%2522%253A%2522clrbyu1t200043b6emsus3evs%2522%252C%2522activeTabId%2522%253A%2522clrbyu1t200033b6ew54y1o54%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrbyu1t200033b6ew54y1o54%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrbyu2sf0009dxei9hq44atl%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clrbyus57005y3b6e0l58xrx8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

go to `nuxt.module.ts` file:

<img width="896" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/82209198/784bd4a1-d412-475e-8d67-a150c431f345">

### Describe the bug

☝️ 

### Expected behavior

no error in editor 🙂

**Comment by sadeghbarati** [comment]
Types are working on Local, This is maybe Codesandbox/Stackblitz issue

![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/7025f409-f652-42ca-9b44-4a64a613a130)

I have **no**  Component in the components directory that is why Terminal has warnings

**Comment by Aldikrasniqi** [comment]
Make sure you have run locally: npm run dev, it will make the build and the error with disappear
