### ISSUE TITLE
[Feature]: Add ScrollBar Button

### ISSUE THREAD

**Issue by MangMax** [radix-vue/shadcn-vue#276]
### Describe the feature

I tried to add a separate scroll button to mimic the winui style, like this 
![PixPin_2024-01-16_14-43-59](https://github.com/radix-vue/shadcn-vue/assets/68525017/633206ff-5d7a-427a-ac1c-ab5ca3e9e4c6)
but ran into a few Problems, due to the space squeeze of the button the scrollbar is positioned outside of my expectations, it seems this can only be solved perfectly by adding the size of the button when calculating the offset, or I'd like to know what options are available to achieve this 
![PixPin_2024-01-16_14-46-41](https://github.com/radix-vue/shadcn-vue/assets/68525017/66d863c1-bb68-4047-8ac0-6a217a5670cd)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by hrynevychroman** [comment]
Need more info, what component from library are you using?

**Comment by sadeghbarati** [comment]
I think what he wants is related to [Scroll Area](https://www.radix-vue.com/components/scroll-area.html) in radix-vue

@MangMax can you close this and report it in radix-vue I can't transfer this issue there

**Comment by MangMax** [comment]
Sorry, I got it wrong. I'll move it there.
