### ISSUE TITLE
[Question]: Why it's not possible to directly extend the `VariantProps`?

### ISSUE THREAD

**Issue by jd-solanki** [radix-vue/shadcn-vue#277]
### Describe the feature

Hi 👋🏻 

I was learning how to use cva in Vue and noticed below code:
```ts
interface ButtonVariantProps extends VariantProps<typeof buttonVariants> {}

interface Props extends PrimitiveProps {
  variant?: ButtonVariantProps['variant']
  size?: ButtonVariantProps['size']
  as?: string
}
```

should be written like

```ts
// Let's ignore optional for now
interface Props extends PrimitiveProps {
	as?: string
}
```

So I tried it in fresh vue project and found that we get Vue type error:
![image](https://github.com/radix-vue/shadcn-vue/assets/47495003/afac2f97-8e08-47da-bb5c-313e7099f6e8)

Is anyone know what's causing this?

### Additional information

- [X] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Hi @jd-solanki


- https://github.com/vuejs/core/discussions/9906
- https://github.com/vuejs/core/issues/9774#issuecomment-1848597661
- https://github.com/vuejs/core/issues/4294#issuecomment-1718745105
