### ISSUE TITLE
[Feature]: Column Freezing in Data Table

### ISSUE THREAD

**Issue by anakin001** [radix-vue/shadcn-vue#288]
I'd like to allow a column and its data position to be fixed, while scrolling the table horizontally.

The image below describes it.
![image](https://github.com/radix-vue/shadcn-vue/assets/62232054/073771ed-a6df-4fea-b137-de947515f1c4)

**Comment by sadeghbarati** [comment]
For now, look `material-react-table` which uses `tanstack table` APIs

https://www.material-react-table.com/docs/guides/column-pinning

Will add `column pinning` example to the doc
