### ISSUE TITLE
[Feature]: New York demo

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#29]
### Describe the feature

User should have the ability to switch style when previewing component, and we would need to have examples for `new-york`.

Let's populate the `registry/new-york/example` folder with demo please 😁

### Additional information

- [x] I intend to submit a PR for this feature.
- [x] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
@ahmedmayara able to help out here? 😁

**Comment by ahmedmayara** [comment]
Yes sure!! I'll do what I can.
