### ISSUE TITLE
[Bug]: Toast timeout not working properly 

### ISSUE THREAD

**Issue by Clemens-B** [radix-vue/shadcn-vue#290]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/tdkd3r-cpu8k8?file=src%2Fcomponents%2Fui%2Ftoast%2FToast.vue

### Steps to reproduce

Use toast component

### Describe the bug

The TOAST_REMOVE_DELAY variable does not seem to work. The default value is set to 1000 seconds but the toast is closing after 3-5 seconds.

It looks like `onOpenChange` is triggered falsely.

**Comment by sadeghbarati** [comment]
**`TOAST_REMOVE_DELAY`** is not the same as `duration` 

Try `const TOAST_REMOVE_DELAY = 0;` and you will notice what that variable is used for

default duration is 5 sec 

https://www.radix-vue.com/components/toast.html#provider

if you want to change the duration you need to set duration on `ToastProviders` in `Toaster.vue` or 

duration in `toast` function

**Comment by mkeyy0** [comment]
@sadeghbarati, just to clarify, is `TOAST_REMOVE_DELAY` used to make the animation smoother? To be honest, the code related to this part is not quite clear. I would really appreciate the answer.
