### ISSUE TITLE
[Bug]: Navigation Menu component missing file NavigationMenuDemoItem.vue

### ISSUE THREAD

**Issue by jychen23333** [radix-vue/shadcn-vue#292]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/shadcn-vue-navigationmenudemo-mkd9rr?file=%2Fsrc%2FApp.vue%3A2%2C25-2%2C51

### Steps to reproduce

![屏幕截图 2024-01-19 112531](https://github.com/radix-vue/shadcn-vue/assets/115698410/98c48f5e-36b4-458f-b5a3-494b13664ef1)

### Describe the bug

Missing file

**Comment by sadeghbarati** [comment]
Same issue https://github.com/radix-vue/shadcn-vue/issues/232

**Comment by AlexanderKozhevin** [comment]
+1

**Comment by shiny** [comment]
excuse me?
