### ISSUE TITLE
[Bug]: shadcn-nuxt: Error: Cannot find module '@oxc-parser/binding-linux-x64-musl'

### ISSUE THREAD

**Issue by choongsil** [radix-vue/shadcn-vue#293]
### Environment

```bash
Developement/Production OS: Windows 10/ Amazon Linux release 2023 (Amazon Linux)
Node version: 20.9.0
Package manager: pnpm@8.10.0
Radix Vue version: ^1.2.7
shadcn nuxt version: ^0.8.6
Vue version: ^3.4.15
Nuxt version: ^3.9.3
Nuxt mode: universal
Nuxt target: server
CSS framework: @nuxtjs/tailwindcss :^6.10.4
Client OS: Amazon Linux release 2023 (Amazon Linux)
```

### Link to minimal reproduction

empty

### Steps to reproduce

I am currently working with Nuxt3 and TypeScript and encountering an issue while deploying to an Amazon Linux server. The following error is being thrown:

ERROR Error while requiring module shadcn-nuxt: Error: Cannot find module '@oxc-parser/binding-linux-x64-musl'
Require stack:
#10 54.95 - /app/node_modules/.pnpm/oxc-parser@0.2.0/node_modules/oxc-parser/index.js
ERROR Cannot find module '@oxc-parser/binding-linux-x64-musl'
Require stack:
- /app/node_modules/.pnpm/oxc-parser@0.2.0/node_modules/oxc-parser/index.js
In my project, I am using shadcn-nuxt, which seems to reference oxc-parser. However, within .nodeModules/@oxc-parser, I only find @oxc-parser/binding-win32-x64-msvc.

In an attempt to resolve this error, I explicitly tried adding the package using:

pnpm add @oxc-parser/binding-linux-x64-musl
But I encountered a 404 Not Found error indicating that the package doesn't exist in the registry:

GET https://registry.npmjs.org/@oxc-parser%2Fbinding-linux-x64-musl: Not Found - 404

Is there any way to resolve this issue? Any suggestions or guidance would be greatly appreciated.

### Describe the bug

It runs on Windows, but there is a problem when deploying to a Linux server

### Conext & Screenshots (if applicable)

![msedge_XOwUBoLYWq](https://github.com/radix-vue/shadcn-vue/assets/105252597/8ee4dd3d-5f3c-4aaf-b337-f95a8973fc15)

**Comment by zernonia** [comment]
Sound like an upstream issue with `@oxc-parser`.  should be related https://github.com/oxc-project/oxc/issues/1736#issuecomment-1884094884.

Meanwhile you can use the manual approach for adding the nuxt-module for now 😁

**Comment by choongsil** [comment]
Thank you for your kind response. I have checked the link you provided, but there are parts that I don't quite understand, and I would like to ask a follow-up question.

Should I install it directly on the Linux server, or should I add the biome mentioned in your link to my project?

**Comment by choongsil** [comment]
> 기부자



> 의업스트림 문제인 것 같아요 `@oxc-parser`. [oxc-project/oxc#1736 (설명)](https://github.com/oxc-project/oxc/issues/1736#issuecomment-1884094884) 과 관련이 있어야 합니다 .
> 
> 그동안 nuxt-module을 추가하기 위해 수동 접근 방식을 사용할 수 있습니다 😁



> Sound like an upstream issue with `@oxc-parser`. should be related [oxc-project/oxc#1736 (comment)](https://github.com/oxc-project/oxc/issues/1736#issuecomment-1884094884).
> 
> Meanwhile you can use the manual approach for adding the nuxt-module for now 😁

Thank you for your kind response. I have checked the link you provided, but there are parts that I don't quite understand, and I would like to ask a follow-up question.

Should I install it directly on the Linux server, or should I add the biome mentioned in your link to my project?

**Comment by choongsil** [comment]
> Sound like an upstream issue with `@oxc-parser`. should be related [oxc-project/oxc#1736 (comment)](https://github.com/oxc-project/oxc/issues/1736#issuecomment-1884094884).
> 
> Meanwhile you can use the manual approach for adding the nuxt-module for now 😁

Thank you for your kind response. I have checked the link you provided, but there are parts that I don't quite understand, and I would like to ask a follow-up question.

Should I install it directly on the Linux server, or should I add the biome mentioned in your link to my project?

**Comment by zernonia** [comment]
@choongsil  it might be upstream issue with `@oxc-parser`.

As an alternative for now you can checkout this [tab with manual installation](https://www.shadcn-vue.com/docs/installation/nuxt.html)

![image](https://github.com/radix-vue/shadcn-vue/assets/59365435/cf01f555-4a6f-45cd-9e99-c36f7b4bb87a)

**Comment by choongsil** [comment]
> zernonia

Thank you so much for your help. 
Have a great day.

**Comment by veritymedia** [comment]
Just had this issue. What helped is adding another step in the docker build to install -D oxc-parser. After that, all works.

**Comment by buggzeth** [comment]
Just had this issue when running the 'npm install' command in my project on linux. Solved by deleting package-lock.json from the repo and reinstalling.
