### ISSUE TITLE
[Bug]: can't get themes to work on Nuxt

### ISSUE THREAD

**Issue by MyWay** [radix-vue/shadcn-vue#294]
### Environment

```bash
Developement/Production OS: Linux
Node version: 20.10.0
Package manager: npm@10.2.3
Radix Vue version: 1.3.2
Shadcn Vue version: shadcn-nuxt 0.8.7
Vue version: 3.4.14
Nuxt version: 3.9.3
Nuxt mode: universal
Nuxt target: server
CSS framework: nuxtjs/tailwindcss 6.10.4
Client OS: Linux
Browser: Chrome latest
```

### Link to minimal reproduction

https://github.com/MyWay/my-nuxt-shadcn-app

### Steps to reproduce

Clone the repo and run.

### Describe the bug

1. I followed instructions at https://www.shadcn-vue.com/docs/installation.html, choosing Nuxt.
2. Then from the Themes page, I customized the color to orange and copied the code into assets/css/tailwind.css.

### Expected behavior

 I expected my button to become orange, like in the Themes and Components page, but mine didn't.

### Conext & Screenshots (if applicable)

![screen_button](https://github.com/radix-vue/shadcn-vue/assets/1765284/3ed06bf3-bb77-4265-ab57-35a69e456167)

**Comment by sadeghbarati** [comment]
I have an error with `oxc parser`, Can you try the manual `modules/shadcn.ts`?

<details><summary>modules/shadcn.ts</summary>
<p>

```ts
import {
  defineNuxtModule,
  addComponent,
  addComponentsDir,
  tryResolveModule,
} from 'nuxt/kit';

export interface ShadcnVueOptions {
  /**
   * Prefix for all the imported component
   */
  prefix: string;

  /**
   * Directory that the component lives in.
   * @default "~/components/ui"
   */
  componentDir: string;
}

export default defineNuxtModule<ShadcnVueOptions>({
  defaults: {
    prefix: 'Ui',
    componentDir: '~/components/ui',
  },
  meta: {
    name: 'ShadcnVue',
    configKey: 'shadcn',
    version: '0.0.1',
    compatibility: {
      nuxt: '^3.9.0',
      bridge: false,
    },
  },
  async setup({ componentDir, prefix }) {
    const isVeeValidateExist = await tryResolveModule('vee-validate');

    addComponentsDir(
      {
        path: componentDir,
        extensions: ['.vue'],
        prefix,
        pathPrefix: false,
      },
      {
        prepend: true,
      }
    );

    if (isVeeValidateExist !== undefined) {
      addComponent({
        filePath: 'vee-validate',
        export: 'Form',
        name: `${prefix}Form`,
        priority: 999,
      });

      addComponent({
        filePath: 'vee-validate',
        export: 'Field',
        name: `${prefix}FormField`,
        priority: 999,
      });
    }

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationRoot',
      name: `${prefix}Pagination`,
      priority: 999,
    });

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationList',
      name: `${prefix}PaginationList`,
      priority: 999,
    });

    addComponent({
      filePath: 'radix-vue',
      export: 'PaginationListItem',
      name: `${prefix}PaginationListItem`,
      priority: 999,
    });
  },
});

declare module '@nuxt/schema' {
  interface NuxtConfig {
    shadcn?: ShadcnVueOptions;
  }
  interface NuxtOptions {
    shadcn?: ShadcnVueOptions;
  }
}
```

</p>
</details> 

---

Cannot find module '@oxc-parser/binding-linux-x64-musl'
Require stack:
- /home/projects/nbwijnqyo.github/node_modules/oxc-parser/index.js

**Comment by MyWay** [comment]
Still no errors, I only see:  WARN  Overriding Button component. You can specify a priority option when calling addComponent to avoid this warning.

But the theme isn't applied, I still see the black button.

**Comment by sadeghbarati** [comment]
> Still no errors, I only see: WARN Overriding Button component. You can specify a priority option when calling addComponent to avoid this warning.

You don't have `oxc parser` error?

---


BTW this is manual `modules/shadcn.ts` which you can change the theme colors

https://stackblitz.com/edit/github-autnkm

**Comment by MyWay** [comment]
> > Still no errors, I only see: WARN Overriding Button component. You can specify a priority option when calling addComponent to avoid this warning.
> 
> You don't have `oxc parser` error?
> 
> BTW this is manual `modules/shadcn.ts` which you can change the theme colors
> 
> https://stackblitz.com/edit/github-autnkm

Exactly, I don't see any error.

**Comment by sadeghbarati** [comment]
I also have `oxc-parser` error in my Terminal, that's why I can't test it

I'll test with another OS and will let you know what is the problem

**Comment by sadeghbarati** [comment]
@MyWay 

HMR is working for me, also I had `oxc-parser` error in StackBlitz Playground

Tested `dev` and `build` with

- macOS
- Windows
- Windows + WSL

https://github.com/radix-vue/shadcn-vue/assets/17789047/faf5d498-96f0-4339-9d9a-685a71d11d8a

---

Can you try with new packageManagers like `pnpm` or `bun`?

**Comment by MyWay** [comment]
Hi, I had tried already with bun too, same. No errors, but no theme. Thanks for trying. I'm on Ubuntu 23.10.

Did you test, e.g. with the orange theme? Because by default it's already black.

**Comment by sadeghbarati** [comment]
@MyWay No I choose `default` registry and `slate` baseColor

I only change the primary CSS variable in the code

**Comment by sadeghbarati** [comment]
@MyWay No I choose `default` registry and `slate` baseColor

I only change the primary CSS variable in the code

**Comment by MyWay** [comment]
Yeah, so on my repository for the issue reproduction you are seeing the orange button, while I see the black one.

**Comment by sadeghbarati** [comment]
@MyWay now I understand your problem, If you look at your `component.json`

```json
{
  "$schema": "https://shadcn-vue.com/schema.json",
  "style": "new-york",
  "typescript": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "assets/css/tailwind.css",
    "baseColor": "neutral",
    "cssVariables": false /////////////////////
  },
  "framework": "nuxt",
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

You set `cssVariables` to **false** that's why your button bg doesn't change because in `components/ui/button/index.ts`

CVA variants classes are pointing to `bg-slate-900` (cssVariables: false) instead of `bg-primary` (cssVariables: true)


---

If you want to modify your button background you need to define your custom color in `tailwind.config` **theme.extend.colors**

https://tailwindcss.com/docs/customizing-colors#adding-additional-colors


---

If you want to use CSS variables way just use `npx shadcn-vue init` again and set `cssVariables: true` in your Terminal

**Comment by MyWay** [comment]
Ah-ha. I thought that was the opposite and didn't enable it. Thanks I'll try.

**Comment by MyWay** [comment]
Confirm that it worked, thanks.
