### ISSUE TITLE
[Bug]: Carousel installation error

### ISSUE THREAD

**Issue by rainbowdog1** [radix-vue/shadcn-vue#297]
### Environment

```bash
Developement/Production OS: macOS 13.1
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
CSS framework: tailwindcss@3.3.3
Client OS: macOS 13.1
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

Dont know how to put it to a codesandbox or etc.

### Steps to reproduce

1. Install carousel component using `npx shadcn-vue@latest add carousel`

### Describe the bug

Installation gives an error:

```
⠋ Installing components...[@vue/compiler-sfc] Failed to resolve import source "./interface".

anonymous.vue
5  |  import { cn } from '@/lib/utils'
6  |  
7  |  const props = withDefaults(defineProps<CarouselProps & WithClassAsProps>(), {
   |                                         ^^^^^^^^^^^^^
8  |    orientation: 'horizontal',
9  |  })
```

### Expected behavior

It should normally install a carousel component.

### Conext & Screenshots (if applicable)

Not using TypeScript.

**Comment by lilkimo** [comment]
same issue here

**Comment by sadeghbarati** [comment]
@Dunqing Thanks! ❤️ 

These components have errors while installing them in the JavaScript project with `shadcn-vue`

- Carousel
- Calendar
- vue-sonner

**Comment by Dunqing** [comment]
I've done some digging and Carousel has an `interface.ts` file, under javascript all of its types are moved out and renamed to `interface.js`, making it impossible to find `interface.ts`. This is a bit of a tricky one, we'll probably need to add the original file somewhere first on how then to transform to js

**Comment by sadeghbarati** [comment]
@Dunqing 

Please take a look at `shadcn-svelte` the way they handle it is way simpler 
Instead of a transformer in CLI to process the TS contents they build separated styles (registry JSON files, not source files)

`default` - `default-js`
`new-york` - `new-york-js` 


https://github.com/huntabyte/shadcn-svelte/releases/tag/shadcn-svelte%400.7.0
https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/static/registry/styles

**Comment by Dunqing** [comment]
> @Dunqing
> 
> Please take a look at `shadcn-svelte` the way they handle it is way simpler Instead of a transformer in CLI to process the TS contents they build separated styles (JSON files)
> 
> `default` - `default-js` `new-york` - `new-york-js`

It's much simpler but increases maintenance costs. When you have a bug in one of your components we need to change the js and ts files simultaneously.

**Comment by jeshtan** [comment]
@Dunqing thanks for your hard work to make the carousel compatible with pure javascript setup. Would you mind checking another 2 components which are caleander and sooner too?

**Comment by Dunqing** [comment]
> @Dunqing thanks for your hard work to make the carousel compatible with pure javascript setup. Would you mind checking another 2 components which are caleander and sooner too?

I had a [PR](https://github.com/radix-vue/shadcn-vue/pull/348) to fix the calendar cannot be installed. 

I have a preliminary understanding of the issue of not being able to install `vue-sonner`, which is not the same as the calendar issue. I need to dig deeper into the
