### ISSUE TITLE
[Feature]: V-Calendar mode="date" ability to choose month and year.

### ISSUE THREAD

**Issue by Kuba-Kajderowicz** [radix-vue/shadcn-vue#298]
### Describe the feature

Currently in Shadcn-vue you cannot select month or year by clicking on the "header" of the calendar, when setting mode to "date".

I've highlighted in red the Month that is not clickable to expand the picker further to show months & years

![image](https://github.com/radix-vue/shadcn-vue/assets/137412102/5979c84b-fdda-4aae-98a0-35b75e3afc57)
 

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by valentinhttr** [comment]
Thanks for the suggestion, I think it could be a nice addition 🚀 
 Don't hesitate to propose a PR if you have the time/skills/desire...

**Comment by sadeghbarati** [comment]
We should only add style cause I don't think `v-calendar` has slot for it to handle it manually

`v-calendar` has `header-title` slot which will remove this Popover

**Comment by Kuba-Kajderowicz** [comment]
> Thanks for the suggestion, I think it could be a nice addition 🚀 Don't hesitate to propose a PR if you have the time/skills/desire...


Sadly im a beginner user of shadcn-vue so not that confident to be touching it without proper knowledge of how it works in the background

**Comment by wasimTQ** [comment]
@sadeghbarati @valh1996 I can try it out

**Comment by sadeghbarati** [comment]
@wasimTQ Great 👍

**Comment by wasimTQ** [comment]
@sadeghbarati I was able to fix it with a little tweak and added some styling. But the accessibility is broken inside the month and year selector. I have to force it somewhat.

I'll push the changes and let you know. Check the styles and let me know if that's good enough.

Also I came to malaysia for a tour, I'm staying till 26th. So expect some delays on my side.

**Comment by wasimTQ** [comment]
[Calendar.vue](https://github.com/wasimTQ/shadcn-vue/blob/fix-calendar-month-selection/apps/www/src/lib/registry/default/ui/calendar/Calendar.vue)

![Screenshot 2024-02-01 204851](https://github.com/radix-vue/shadcn-vue/assets/62562483/86cf4f8a-2aba-4350-a52b-ad97e46b747b)


@sadeghbarati Also check whether the styling is fine and let me know what to change. I have to work on the accessibility.

**Comment by sadeghbarati** [comment]
@wasimTQ LGTM xd let's do the PR and fix this annoying bug :D

**Comment by wasimTQ** [comment]
@sadeghbarati I couldn't add custom icons for the popover and also dealing with accessibility in this looks hard as well.

I tried using teleport for adding custom icons but it's not working. Maybe a lot of css tweaks will do the trick.

Update: Working on the accessibility rn. It's coming good.

**Comment by sadeghbarati** [comment]
Template slot for popover buttons working on dev 

But in prod it's gone weird 🥲

Update: browser cache 😬

**Comment by wasimTQ** [comment]
@sadeghbarati Do you think working on accessibility for month popover here or on their official repo best?

I think doing it in the off repo is the best way.

**Comment by sadeghbarati** [comment]
@wasimTQ 

Official repo is not maintained I guess and current accessibility is lgtm, focus popover content with Tab

I think it's better to focus on 

 https://react-spectrum.adobe.com/internationalized/date/
