### ISSUE TITLE
[Feature]: Stepper

### ISSUE THREAD

**Issue by rainbowdog1** [radix-vue/shadcn-vue#303]
### Describe the feature

A stepper with horizontal and vertical orientation. Each step can be marked by different states such as Completed (✅), Failed (❌)...

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Hey thanks for the report, let's track it here

 https://github.com/radix-vue/shadcn-vue/issues/92
