### ISSUE TITLE
[Bug]: Cannot install calendar when not using typescript

### ISSUE THREAD

**Issue by jeshtan** [radix-vue/shadcn-vue#306]
### Environment

```bash
Shadcn Vue version: 0.8.7
```

### Link to minimal reproduction

no link as this bug happen during install calendar via cli

### Steps to reproduce

run `npx shadcn-vue@latest add calendar`

### Describe the bug

Getting unexpected token error

> ⠙ Installing calendar.../<project root>/Calendar.vue.ts: Unexpected token, expected "," (78:312)
> 
>   76 |     }, {})
>   77 | })
>  78 | /* @detype: remove-after-this */[$attrs.mode !== 'time'];[cn(buttonVariants({ variant: 'outline' }), 'h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100')];[handleNav('prev')];[ChevronLeft];[handleNav('next')];[ChevronRight];[DatePicker];[modelValue];[$attrs];[modelModifiers];['none'];[columns];[(_, slot) of vCalendarSlots];[scope];[slot]

### Expected behavior

manage to install calendar component

### Conext & Screenshots (if applicable)

no using typescript

**Comment by lilkimo** [comment]
same issue here

**Comment by Laurenz-Guevara** [comment]
Same issue no TS too

**Comment by sadeghbarati** [comment]
Let's track it here :pray:

https://github.com/radix-vue/shadcn-vue/issues/297
