### ISSUE TITLE
[Feature]: Add support for Sonner variant

### ISSUE THREAD

**Issue by anakin001** [radix-vue/shadcn-vue#307]
Add support for Sonner variant, i.e. destructive

**Comment by sadeghbarati** [comment]
`vue-sonner` still needs to refactor, ~~will try to make PR again to the upstream repo~~ 😢 

https://github.com/xiaoluoboding/vue-sonner/issues/39#issuecomment-1907621342

**Comment by sadeghbarati** [comment]
Thanks for the report let's track it here https://github.com/radix-vue/shadcn-vue/issues/355
