### ISSUE TITLE
[Feature]: Improve the `Installation` section for each components

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#31]
### Describe the feature

Currently in  https://www.shadcn-vue.com/docs/components/avatar.html#installation only shows the CLI installation, however some components has more steps to that. eg `Accordion`.

Let's update all the `Installation` section for components 😁

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by CooperHash** [comment]
in vite+vue project, when run npx shadn-vue@latest add xxx, just add ui dir to /components/ui not included lib dir

**Comment by CooperHash** [comment]
what's that means? like Accordion, manual installation is use `import { AccordionRoot, AccordionContent, AccordionItem, AccordionTrigger } from'radix-vue'` is there any other thing need to be done?

**Comment by zernonia** [comment]
@CooperHash some components has more steps than CLI install.

https://ui.shadcn.com/docs/components/accordion#installation
<img width="782" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/59365435/d2155f90-147d-46f6-84fb-ada779464514">
