### ISSUE TITLE
[Bug]: Installation of Calendar is broken

### ISSUE THREAD

**Issue by DoktorDaveJoos** [radix-vue/shadcn-vue#311]
### Environment

```bash
Node: v16.16.0
NPM: 8.11.0
```

### Link to minimal reproduction

https://www.shadcn-vue.com/docs/components/calendar.html#installation

### Steps to reproduce

Execute this:
`npx shadcn-vue@latest add calendar`

### Describe the bug

Installation of Calendar Component fails with this error message:

`Calendar.vue.ts: Unexpected token, expected ","`

### Expected behavior

`npx shadcn-vue@latest add calendar` installs the Calendar Component properly

### Conext & Screenshots (if applicable)

None

**Comment by sadeghbarati** [comment]
@DoktorDaveJoos  Are you having TypeScript installed in your devDependecies?

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/kv7jhm?file=src%2FApp.vue

**Comment by gregmsanderson** [comment]
I'm finding the same. The Calendar fails to install using the CLI. It's with a JavaScript project (it works fine with TypeScript).

In `components.json` "typescript" is set as false.

I was going through each component, trying to add them ...

```
shadcn-vue $ npx shadcn-vue@latest add avatar
✔ Done.
shadcn-vue $ npx shadcn-vue@latest add badge
✔ Done.
```

... but when it comes to adding the calendar to the non-TypeScript project ...

```
shadcn-vue $ npx shadcn-vue@latest add calendar
⠙ Installing calendar.../path/src/components/ui/calendar/Calendar.vue.ts: Unexpected token, expected "," (77:312)

  75 |     }, {})
  76 | })
> 77 | /* @detype: remove-after-this */[$attrs.mode !== 'time'];[cn(buttonVariants({ variant: 'outline' }), 'h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100')];[handleNav('prev')];[ChevronLeft];[handleNav('next')];[ChevronRight];[DatePicker];[$attrs];[modelValue];[modelModifiers];['none'];[columns];[(_, slot) of vCalendarSlots];[scope];[slot]
```

It looks like it's failing to remove the TypeScript part correctly during the install. The prior components worked and installed.

**Comment by sadeghbarati** [comment]
[shadcn-vue-cli.zip](https://github.com/radix-vue/shadcn-vue/files/14347916/shadcn-vue-cli.zip)

Until next release you guys can download this zip file which contains shadcn-vue CLI .tgz file

Copy .tgz file in root of your project run this command

```bash
pnpm add ./shadcn-vue-0.9.0-calendar.tgz -D
```

And add this to your package.json scripts


```
"scripts": {
  "shadcn-tgz": "shadcn-vue add"
}
```

And then run `pnpm run shadcn-tgz`

**Comment by handhikadj** [comment]
@sadeghbarati please release minor version. this is critical bug
I'm experiencing this
