### ISSUE TITLE
[Bug]: Double scrollbar

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#321]
### Reproduction

none

### Describe the bug

Not sure why, but I seem to have issues with "double scrollbars" (same issue on Chrome and Safari, osX)

https://github.com/radix-vue/shadcn-vue/assets/15458/cd8ce39a-f118-4604-80d1-8ba58cbfa870

### System Info

```bash
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 131.94 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.16.0 - ~/.node/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.1.2
  npmPackages:
    @vueuse/core: 10.7.1 => 10.7.1
    radix-vue: 1.3.0 => 1.3.0
    vue: 3.4.7 => 3.4.7
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@maelp Hi

Can you update `radix-vue` to `v1.4.0`? and update your existing component from `shadcn-vue` CLI

Also, are you using `radix-vue` **scroll-area**? can you share live site again

**Comment by maelp** [comment]
okay I will try this! the component is from the Combobox demo, I will tell you if updating changes something

**Comment by sadeghbarati** [comment]
@maelp any update?

I think there is something wrong with your layout or CSS styles

**Comment by maelp** [comment]
the layout is the one from shadcn (I haven't really modified the components)

do you have any idea what I should be looking for in terms of CSS style for the "double scrollbar"? it seems that Chrome often adds a visible scrollbar each time it thinks the content can be scrolled, but the scrollbar is always visible (and not "just on hover")

**Comment by sadeghbarati** [comment]
@maelp can you share live site?

**Comment by maelp** [comment]
Unfortunately the site where it happens is private, I'll see if I can reproduce on a public site and let you know

**Comment by hrynevychroman** [comment]
It looks like you made some error inside Components layout, 👇 example of what I think you occured:

```html
<div class="scroll-1">
    <div class="scroll-2">
         <div></div>
         <div></div>
         <div></div>
    </div>
    <div></div>
    <div></div>
</div>
```

So you first scroll `scroll-2` div, and when it on bottom, `scroll-1`, can you share your code example screenshot of Components structure?

**Comment by maelp** [comment]
@sadeghbarati @romanhrynevych okay it was a bug on my side, some mistaken CSS, I'm closing the issue it works fine now
