### ISSUE TITLE
[Feature]: Add a default font for shadcn-vue.com

### ISSUE THREAD

**Issue by VoVAllen** [radix-vue/shadcn-vue#332]
### Describe the feature

Thanks for the great project. Both shadcn.com and shadcn-svelte.com used Geist as the default font. I think shadcn-vue should also have one instead of system sans serif to make it a consistent experience on different devices. Currently it doesn't look nice on my device using YaHei as the system font.

![image](https://github.com/radix-vue/shadcn-vue/assets/8686776/4af2eb75-c478-4e98-895c-8ffafdcc880f)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by hrynevychroman** [comment]
I will fix this issue ❤️

**Comment by Daedra22** [comment]
but this is not working in vite
