### ISSUE TITLE
[Bug]: The SelectItem has the wrong left-padding class

### ISSUE THREAD

**Issue by gregmsanderson** [radix-vue/shadcn-vue#335]
### Reproduction

https://www.shadcn-vue.com/docs/components/select.html

### Describe the bug

It seems the "default" style of component has the wrong left padding class ("pl-8") resulting in a big gap to the left of each item in the select:

https://github.com/radix-vue/shadcn-vue/blob/41660d36cdb0d4eb8b22ab1efe815d6a5c1fb4a9/apps/www/src/lib/registry/default/ui/select/SelectItem.vue#L29

I believe that _should_ be "pl-2", like it is for the "new york" style:

https://github.com/radix-vue/shadcn-vue/blob/41660d36cdb0d4eb8b22ab1efe815d6a5c1fb4a9/apps/www/src/lib/registry/new-york/ui/select/SelectItem.vue#L29

### System Info

```bash
System:
 OS: macOS 14.1.1
Binaries:
 Node: 20.11.0 - /usr/local/bin/node
 npm: 10.2.4 - /usr/local/bin/npm
 bun: 1.0.7 - ~/.bun/bin/bun
Browsers:
 Chrome: 121.0.6167.184
 Safari: 17.1
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Thanks for making a PR

But first, take a look at the main `shadcn-ui` default style `SelectItem` 

https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/select.tsx#L121

**Comment by gregmsanderson** [comment]
Ah ... I see the confusion.

The original shadcn-ui has a default style with the check on the _left_ (and a new york style with the check on the _right_). Hence they needed extra padding (`pl-8`) to allow room for that absolutely-positioned check.

Your default style (or at least the demo of it) has the check on the _right_. That's why the padding looks wrong since when the check is on the right, it should be `pl-2`.

Perhaps a better solution then would be for the default style select to have the check on the _left_, as that would match the original styling. It would then keep `pl-8`.

https://www.shadcn-vue.com/docs/components/select.html

**Comment by sadeghbarati** [comment]
@gregmsanderson That was my mistake then cause there were too many copies and pastes 

Can you change `SelectItemIndicator` position to the left?

```diff
- absolute right-2 flex h-3.5 w-3.5 items-center justify-center
+ absolute left-2 flex h-3.5 w-3.5 items-center justify-center
```

**Comment by gregmsanderson** [comment]
@sadeghbarati No problem.

Done!

https://github.com/radix-vue/shadcn-vue/pull/340
