### ISSUE TITLE
[Bug]: (Docs) Table of Contents sidebar not scrollable in the docs

### ISSUE THREAD

**Issue by m-krebs** [radix-vue/shadcn-vue#338]
### Reproduction

None. Isn't library related

### Describe the bug

When viewing the docs on a smaller display, the Table of Contents on the right side, get out of sight.
On the original version of the docs (shadcn/ui), you are able to scroll inside of the sidebar to get to a specific step/point.
This is not the case in the docs of this project. 

### System Info

```bash
Firefox on Windows
```

### Contributes

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by hrynevychroman** [comment]
@m-krebs can you add some screenshots? There is no rightbar on mobile on original library 🤔 

<img width="1139" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/82209198/e9776046-fa8f-4713-a107-e2e4a3985d78">

**Comment by sadeghbarati** [comment]
@romanhrynevych, go to the `Data Table` page, and if you have a small (height) screen, you will notice the issue
