### ISSUE TITLE
[Feature]: Add icon in input component

### ISSUE THREAD

**Issue by valentinhttr** [radix-vue/shadcn-vue#341]
### Describe the feature

Add an optional prop or slot that lets us add an icon to an input and control its positioning.

For example: https://ui.nuxt.com/components/input#icon

A prop seems difficult in vue-shadcn since the icon library is free to choose from, perhaps a slot is more suitable?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by hrynevychroman** [comment]
There is no such example in original library [shadcn-input](https://ui.shadcn.com/docs/components/input#default), but I can take this issue into production, @sadeghbarati what you think, we need this?

**Comment by sadeghbarati** [comment]
Really don't know about this

Cause shadcn duty is to provide low-level primitives with documentation 

So, the user could start things faster

@zernonia wdyt?

**Comment by zernonia** [comment]
Instead of modifying the base component, let's create a `Usage` demo with this implementation. 
Dev who want to have `icon` can copy this and paste it as their component.

**Comment by hrynevychroman** [comment]
@sadeghbarati please assign this issue to me, i will create it soon 🪂
