### ISSUE TITLE
[Bug][@vue/compiler-sfc]: Popover - Failed to resolve extends base type.

### ISSUE THREAD

**Issue by valentinhttr** [radix-vue/shadcn-vue#345]
### Reproduction

https://stackblitz.com/edit/tdkd3r-vztatb?file=src%2FApp.vue

### Describe the bug

By adding the basic popover component :
```
npx shadcn-vue@latest add popover
```

We get the following error:
```ts
[plugin:vite:vue] [@vue/compiler-sfc] Failed to resolve extends base type.
If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @vue-ignore */ before it, for example:

interface Props extends /* @vue-ignore */ Base {}

Note: both in 3.2 or with the ignore, the properties in the base type are treated as fallthrough attrs at runtime.

/home/projects/tdkd3r-vmywib/src/components/ui/popover/PopoverContent.vue
8  |    useForwardPropsEmits,
9  |  } from 'radix-vue'
10 |  import { cn } from '@/utils'
   |    ^^^^^^^^^^^^^^^^^^^^^^^
11 |  
12 |  defineOptions({
/home/projects/tdkd3r-vmywib/src/components/ui/popover/PopoverContent.vue
```

### System Info

```bash
-
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by valentinhttr** [comment]
@zernonia isn't a problem [linked directly to radix-vue](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Popover/PopoverContent.vue#L9C1-L15C2) ?

**Comment by zernonia** [comment]
There's a missing types not being exported, causing this issue. https://github.com/radix-vue/radix-vue/issues/687

Fix is coming soon!

**Comment by valentinhttr** [comment]
Fixed in `radix-vue` 1.4.5

**Comment by Lucklj521** [comment]
> There's a missing types not being exported, causing this issue. [radix-vue/radix-vue#687](https://github.com/radix-vue/radix-vue/issues/687)
> 
> Fix is coming soon!

**Comment by Lucklj521** [comment]
Is this problem fixed now ？

**Comment by Lucklj521** [comment]
> There's a missing types not being exported, causing this issue. [radix-vue/radix-vue#687](https://github.com/radix-vue/radix-vue/issues/687)
> 
> Fix is coming soon!

Has this problem been fixed now ？
