### ISSUE TITLE
[Bug]: Class name duplicated

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#35]
If you inspecting some element, you would notice a duplicated class name mainly due to using `2.` approach mentioned below.

For components in `registry`, you would see 2 different approach for passing the class name into `cn` function. 

1. using `class` props.
```
const props = defineProps<... & { class?: string }>()
...
cn(...., props.class)
```

2. using inherited attributes
```
cn(..., $attrs.class)
```

The reason I'm hesitating is because I don't like to declare `class` props in every component, using `$attrs.class` seems much more intuitive. wdyt??

**Comment by sadeghbarati** [comment]
~~I'm with `$attrs`~~ even though it's not typed yet https://github.com/vuejs/core/pull/7444


However if we extend Props based on HTMLAttributes [like shadcn](https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/new-york/ui/button.tsx#L37C1-L42C1), we will have two class prop when we hit <kbd>Ctrl + Space</kbd>

- One from vue `runtime-dom.d.ts` 
- And one from our `defineProps` 

see this [SFC playground](https://play.vuejs.org/#eNrVVc1S2zAQfhXV0xknTCJD6ck14a/pQKe0TKHtAXNw7E0Q2JJHkkmYTN69K8mxY6Dpoace7ES7q91vv/3x0jsuS/pYgRd6kUolKzXJEz47iD2tYo8o0FU5ijkrSiE1WRIJU7IiUykK4uM1v1Fd4W8OJ5XWgtd6GmwKTRT/Q2P/zLJrE/NUcKVJoWbkwMSMlJaMz0Y9/wzyXJBfQubZG78f8yhwsBEkHjRgwEQDngiJOpjSPFEK85rMhpO8guHe7m7sBc5w08RKSI3PamtwqIiCJoA38FwmwyIp6b0SHClcGvu4ViB/IbESI0tztTCC2LvTulRhEMwSvFYWlImAl0VoDI7e0V26G2RM6cCcaXGPXgZrHzph+ZzxbFiAnMFWb13Toz26937tuKtyIUyEVcxXmJVWyP2UzZ7llIqiZDnIb6VmWJtObgmWZP7ZyrSsoMGb3kH68Ir8fk3FpQQF8hFT2cgRQWmnHl99hQX+b5SFyKq8TvwPyu+gRF4ZjM7spOIZwt6ws2jPbYmwpa7VeKGBq3VSBqhlw9rHHnbk6ZbUW7j7dH+DxbafX5+sUSybUdBPJeBouStn1xdfjjV2+6TSoAbknJvOVywd51AA162uO4fozjzBDhlLKWRIbo5QHqzLNlTT9JZ8wtJDRrTAmUKaHoEghcAzRSaJAguE7gTGDywsNMY1yGmSArmUolSN+WtYkRS8SBJ1GBI3rua8Mq92SGuYW3ZNy8vSMXNqpvJngjM7wAlViyZvc7CJt/bzC9PTjUW31RuSphVPTSlJynuUUsbLSqtwI9DNbb/OBonSleRrzz0Ts+cu9PtNfuZxG6u0NB2QOdN3H2GaVLlWvQymjINlMLLvUa8/aOgKiY/8IZ0W38p6rUuJFaw9ZoCUViliQV7JzcvS/jAlg1RjeR/gaS5kZgjChHzaoltiOEMiipGjf0bpWuVlcdstbCmMDFLBsXlJyMwKtinRxBQd155by1gKH1ezhMxsZn/g8qZW3a/nxYxcpHKhCe5t59qyYH1bSXdBP//8bP/I/Y+N91fukSJXti1Mv01whmuqyeEh8fG76o02yYsC5+QFx6vfzhriMQ==)

Edit: external types error and vue props destructuring error with `class` keyword in `Button.vue` in SFC playground

**Comment by sadeghbarati** [comment]
[Base on so1ve answer in Vue issue (How to import interface for defineProps)](https://github.com/vuejs/core/issues/4294?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDIyNzMxMDA1NTE6MTc3ODkwNDc%3D#issuecomment-1718745105) 

imported external interface should **not be extended** so Vue can resolve the type

We should have an interface like this

```diff
- export interface ButtonHTMLAttributes extends HTMLAttributes {
+ export interface OnlyButtonHTMLAttributes {
  autofocus?: Booleanish
  disabled?: Booleanish
  form?: string
  formaction?: string
  formenctype?: string
  formmethod?: string
  formnovalidate?: Booleanish
  formtarget?: string
  name?: string
  type?: 'submit' | 'reset' | 'button'
  value?: string | string[] | number
}
```
https://github.com/wooorm/html-element-attributes/blob/main/index.js

**Comment by libondev** [comment]
Because the default value of the `inheritAttrs` attribute in the vue component is true, I think the processing of `$attrs.class` can be ignored in components that are not explicitly set to `inheritAttrs: false`😃

**Comment by sadeghbarati** [comment]
That Vue SFC playground sometimes acts inconsistently after editing :sob: for example, it's merge classes even if you use $attrs.class and v-bind="$attrs"

I think we should use **`useAttrs`** to destructure the object to access the `class` key
#### [New SFC playground](https://play.vuejs.org/#eNrVV1tv2zYU/iusMcByYUlpOwyY51zaLkU7LF2xdttDnAdZOnKYSJQgUrYLw/995xxSt8R1C2x72ENskzw8l+87/MjsRi/LMljXMJqN5jquZGlEFqnV6WJk9GIkNJi6PFsomZdFZcROVJCKvUirIhdj3DZulz7idwavamMK5daDsD9JUcY/tfYPLA/avFNlbVoTHjUWCxUXShuR65U4pazm2lRSrc688VvIskL8VVRZ8mQ8aQwLxfuvGntvTGsLldYqNhIziTMZ379R3kTsFkoI2lVkEGTFyhvzGtnvB1skecQtsAZlZuKSvtz2LlywjrIaMKg1C0xUrcCISIu3n65+ZavLDHLaak05yjy0bCD2ODCAOEYGcCTEPJFr/oE/B6jHWaQ1Mrdc+Uv04z87OVmMQvbAxk983/3qb3CuhGPEWThC3KLvd1666DiwDDWBDWyNX0Hi/0CRxQXDhvMOWppiyHDKQYdTUSUjXyosXSa4kEaZBpu2TcTGs6Pdrs/jHnHqLOZhi9JoOrId5OdRGdzpQmF7My0YmBewt2eWKJq7q7Xxi1waml2Mbo0p9SwMVxHuLfNAFqEq81lrdfE8eB6chFIlsA3yO/Q1bTzFmd4edUIGuP8E9ydSm5DGD3yYSGYbdO7ngJ1y1NvQ9OJZ8Oz7xvFwyYagCIjZHvExGhs8lasH6MRFXsoMqt9KavAhShEeq80vPGeqGrqabyG+PzB/10DxoQIN1RpL6dVIh8AuX358j33TW8yLpM5c4V9Y/B3wcNaUozV7VasE0+7ZcbbvmGyUhU/6cmtA6aYoSpTRYPvFCFXl9ZHSu3RfBC96KHaqdVg/zxZVK2bmcwkooHYLHf2XBhVrWRvQU1Q6Ui8tYycF3dpQbdEd/YVPxWVVFdVMXF/gfNjQ5us0vhFvkHpIhClQ5xCmNQiEEFSixTLSwIkET0PyA1tOTSoDVRrFID5URalb80O5Iii4EeXrfCas5NJ4Tx+dZrk0j9woHS47i8xr0pA/Sf+mqCd629ZNAy68s99cUU+3FsNWb0HqlF15QRCw4uhZL9D1DYk1VYNAmbpSjWePYnp2w2TS1kd/9jIpGaZTsZHm9mdIozoz2ksglQoYwTl/nnmTaQvXTIwRP4ST89uzV0clMug8JoCQ1jHmgriK68fU/kGUQWyQ3nv4vCmqhADCgsZBl90OwxGIOI0Y/eMsbas8Jre7lBjCOWVaKGxeMZN0G3BJQUSko+zZGwKpGOP1RHcE3k7jqa074OWJOy8s+zorjMBLwLpmFNg3zwyl/uEj4/hT5j9uPGdL14Qzaq8NfLY46CwHTmg814JS3UIl+eQjDfYaHHTKv97PX6UUkbfdMCQwzWArBix+F1HWlkZxfi7obTUSa3+J4OAmqt6zNlNx7Rr2hvjuczcPbbADFLdPvx63zOeXxHYnag0M5SP9/F/Kzrd2zHTYMo0eMOIz+/U+yrFWzAwvB8P60EDl8b6vH3TOkOFzb76HJ5wb5Nb/UWz8tM4ywe/CVQWg6GWI/dImcqBZKK1WCVxEfuG5lkQoSMmsD8Cq5suz4wGxsVoh6TwNnNrOpQ7lW84y7P414gi7XZvzfv8NDi2++M4v0s6t80QVHnbS7/r93zZfuKA=)

---

### useAttrs (not reactive when destructered and make them reactive with computed or other Vue apis is not good choice cause attrs are readonly proxy)

#### Component
```vue
<script setup lang="ts">
import { useAttrs } from 'vue'
import { cn } from '@/lib/utils'

defineOptions({
  inheritAttrs: false,
})

const { class: className, ...rest } = useAttrs() // not reactive only works on first render
</script>

<template>
  <input type="text" :class="cn('flex h-9 w-full text-green-600', className ?? '')" v-bind="rest">
</template>
```

#### Usage

```vue

<script setup lang="ts">
import Input from './Input.vue'
</script>

<template>
    <Input class="text-red-600"/> <!-- class output: "flex h-9 w-full text-red-600" -->
</template>
```

**Comment by libondev** [comment]
> That Vue SFC playground sometime acts inconsistently 😭
> 
> ```
> <script setup lang="ts">
> import { useAttrs } from 'vue'
> import { cn } from '@/lib/utils'
> 
> defineOptions({
>   inheritAttrs: false,
> })
> 
> const { class: className, ...rest } = useAttrs()
> </script>
> 
> <template>
>   <input type="text" :class="cn('flex h-9 w-full', className ?? '')" v-bind="rest">
> </template>
> ```

Let's try this 👀
 https://play.vuejs.org/#eNp9Uk1PIzEM/StRtNIUiU53xa07uxK74gAHQMAxlyHjaVNSJ0o8pQj1v2OnHxQJ0GiixM/v5dnxqz6PsV4NoKe6yTa5SCoDDVH5Fmd/jKZs9F+DbhlDIvUAmf4H3iMgqT6FparqiUREo/ptUL5mslViHh8IltG3BHxSqvmoYH2bM9/SxgjYjcvRaDXh3GZyIOpTtmED9m5WL3JA9voqYkZbVnIe0k0kF5CpU1UQwVrvw/NViVEa4HQft3OwT5/EF3ktMaNvE2RIKzD6gFGbZkBb+OL+Gta8P4DL0A2es78B7yAHP4jHbdq/ATu2fZRX3F6WLjucPeSLNQHmfVFiVDI3Jd9obrY08avS3+2e1WeFZ3DDXdw/1PePnQz2A1qRVRZHdV1bn09YnQHRT0xJDPlcL4LDUaWqE8E2ssjfQe8QdsZGO57DOSRH50QpT1Xf+sytF1bhvo/MTuNobAq9cRgHUvQSQYyWJqvpfn7YZtV7WKv5+NdPdqPVavzosGPoRys37uo6HqrNGxWWArM=

**Comment by binhntfiber** [comment]
Hi, have we finalize the solution yet?

**Comment by sadeghbarati** [comment]
> Hi, have we finalize the solution yet?

I can refactor all components to `useAttrs` and after Vue 3.4 to [`defineAttrs`](https://github.com/rudyxu1102/rfcs/blob/feat/infer_attrs/active-rfcs/0000-infer-attrs.md#using-defineattrst-in-setup-script)
But before that, I need approval from Vue wizards :raised_hands: @ zernonia

**Comment by olemarius** [comment]
Note that setting `inheritAttrs: false` makes it harder to use e.g. Cypress. The recommended way to select elements for a test is by using data-cy="my-element", then getting it with cy.get('[data-cy="my-element"]').
