### ISSUE TITLE
[Bug]: Vue 3.4.19 adds warning in console when using the Calendar component

### ISSUE THREAD

**Issue by gregmsanderson** [radix-vue/shadcn-vue#350]
### Reproduction

https://www.shadcn-vue.com/docs/components/calendar.html

### Describe the bug

I noticed the console started throwing Vue warnings when I have the Calendar component on the page.

I checked your demo page and noticed that _didn't_ have those warnings: https://www.shadcn-vue.com/docs/components/calendar.html

I then checked the Stackblitz demo which that page links to. That _does_ have the warning in the console (exactly as linked).

So ... what could be happening? The _code_ appears the same in all cases ...

It turns out that I think your site is using Vue 3.4.15 but I'm using 3.4.19 (or "latest", which is what the Stackblitz is also set to use). So something has changed in the latest Vue ...

Sure enough they have added a warning: https://github.com/vuejs/core/blob/main/CHANGELOG.md#features

Unfortunately that new warning does not say exactly why it's happening. I only figured out it was the Calendar component by randomly removing elements:

> [Vue warn] Computed is still dirty after getter evaluation, likely because a computed is mutating its own dependency in its getter. State mutations in computed getters should be avoided.  Check the docs for more details: https://vuejs.org/guide/essentials/computed.html#getters-should-be-side-effect-free

To complicate things, the Calendar component uses v-calendar (rather than radix-vue) so it may be _that's_ the issue. Or it may be the way it is being integrated within the custom component ... _Something_ is wrong but the warning does not give enough info to say exactly what.

![Screenshot 2024-02-19 at 21 20 02](https://github.com/radix-vue/shadcn-vue/assets/10390169/b670362c-ae8c-4269-aae4-c5be7f743c14)

### System Info

```bash
System:
 OS: macOS 14.1.1
Binaries:
 Node: 20.11.0 - /usr/local/bin/node
 npm: 10.2.4 - /usr/local/bin/npm
 bun: 1.0.7 - ~/.bun/bin/bun
Browsers:
 Chrome: 121.0.6167.184
 Safari: 17.1
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Deleted all computed from the Calendar source the warning still exists

The issue is related to the `v-calendar` itself

**Comment by sadeghbarati** [comment]
https://github.com/radix-vue/radix-vue/pull/674

Hopefully, we can replace `v-calendar` with this jewel later, thanks to "Eduard Predescu"

**Comment by bdani0717** [comment]
Same warning happens with the combobox from the example: https://www.shadcn-vue.com/docs/components/combobox.html

"vue": "^3.4.19",
"radix-vue": "^1.4.8",

<img width="1758" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/26284661/b73e9e8b-85e1-4884-91cf-e8c827a5d780">

**Comment by maelp** [comment]
Same error, also when using "range" it seems to send some weird `{}` objects instead of the actual datetime when using useVModel

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/kqgmpy

Tested again in the latest Vue 

The computed warns are gone also I would recommend using the `radix-vue` new Calendar instead of v-calendar
