### ISSUE TITLE
[Bug]: DropdownMenuContent Props not working

### ISSUE THREAD

**Issue by joisun** [radix-vue/shadcn-vue#353]
### Reproduction

https://stackblitz.com/edit/adhkxb-c256pb?file=src%2FApp.vue

### Describe the bug

I want to prop the `align` and `side` to `<DropdownMenuContent>` and `<DropdownMenuSubContent>`, it's not work in my local, but works fine on  stackblitz

**It seems the forwarded value return by `useForwardPropsEmits`  <u>not corrently return props on my machine, but works in stackblitz, it's werid</u>** 

> https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/dropdown-menu/DropdownMenuContent.vue#L26

I try to asign both object in my local codebase, and It works, (not work for `<DropdownMenuSubContent>`)
> src/components/ui/dropdown-menu/DropdownMenuContent.vue
```diff
<template>
  <DropdownMenuPortal>
    <DropdownMenuContent
+      v-bind="forwarded"
-      v-bind="{ forwarded, ...delegatedProps }"
      :class="cn('z-50 min-w-32 overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2', props.class)"
    >
      <slot />
    </DropdownMenuContent>
  </DropdownMenuPortal>
</template>
```
Here below is the output of `forwarded`:

1. my local code base:
![image](https://github.com/radix-vue/shadcn-vue/assets/44388103/405dfb84-aba5-43b4-bf41-a9c4f263eb4c)
![image](https://github.com/radix-vue/shadcn-vue/assets/44388103/fc422ba3-639d-4d81-b472-8831d39f8297)

2.stackblitz
![image](https://github.com/radix-vue/shadcn-vue/assets/44388103/85a7e09e-bb63-4fdd-8f6a-30793121a11b)
![image](https://github.com/radix-vue/shadcn-vue/assets/44388103/4578f5d7-1e2e-405d-82e7-921657cec9ba)

Why would this happen and how should I solve this problem,  thanks.

### System Info

```bash
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 6.16 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.7.1 - /usr/local/bin/pnpm
    bun: 1.0.21 - ~/.nvm/versions/node/v16.20.2/bin/bun
  npmPackages:
    @vueuse/core: ^10.7.2 => 10.7.2 
    radix-vue: ^1.4.7 => 1.4.7 
    vue: ^3.3.11 => 3.4.15
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
default:
- [DropdownMenuContent](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/dropdown-menu/DropdownMenuContent.vue#L32)
- [DropdownMenuSubContent](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/dropdown-menu/DropdownMenuSubContent.vue#L25)

new-york:
- [DropdownMenuContent](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/new-york/ui/dropdown-menu/DropdownMenuContent.vue#L32) 
- [DropdownMenuSubContent](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/new-york/ui/dropdown-menu/DropdownMenuSubContent.vue#L25)

Hi both styles have forwardedProps

Can you remove your `node_modules` folder and your lock files `pnpm.lock` and use [Taze](https://github.com/antfu/taze) to check your package updates and reinstall everything again?

**Comment by jaycethanks** [comment]
it works! thanks a lot!

**Comment by joisun** [comment]
> default:
> 
> * [DropdownMenuContent](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/dropdown-menu/DropdownMenuContent.vue?rgh-link-date=2024-02-20T04%3A20%3A35Z#L32)
> * [DropdownMenuSubContent](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/dropdown-menu/DropdownMenuSubContent.vue?rgh-link-date=2024-02-20T04%3A20%3A35Z#L25)
> 
> new-york:
> 
> * [DropdownMenuContent](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/new-york/ui/dropdown-menu/DropdownMenuContent.vue?rgh-link-date=2024-02-20T04%3A20%3A35Z#L32)
> * [DropdownMenuSubContent](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/new-york/ui/dropdown-menu/DropdownMenuSubContent.vue?rgh-link-date=2024-02-20T04%3A20%3A35Z#L25)
> 
> Hi both styles have forwardedProps
> 
> Can you remove your `node_modules` folder and your lock files `pnpm.lock` and use [Taze](https://github.com/antfu/taze) to check your package updates and reinstall everything again?

it works! thanks a lot!
