### ISSUE TITLE
[Feature]: `Vue Sonner` 1:1 changes of original `Sonner` lib

### ISSUE THREAD

**Issue by sadeghbarati** [radix-vue/shadcn-vue#355]
### Describe the feature

`vue-sonner` still missing some of the original `sonner` lib features, I will try to make PR again to the upstream repository

- [x] Bring changes from original sonner to vue-sonner
- [x] Test it with detypes

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
https://github.com/xiaoluoboding/vue-sonner/pull/54

Thanks for the ports `svelte-sonner` and `sonner`

**Comment by sadeghbarati** [comment]
Tested it with `detypes` still has error with `JS`, cause of multiple and complex `d.ts` files like 

#### `Toaster.vue.d.ts`
```ts
interface example {
  theme: import("./types").Theme;
}
```

It should be fixed after another PR gets merged in `vue-sonner`

**Comment by sadeghbarati** [comment]
`vue-sonner` JS support depends on this PR now https://github.com/radix-vue/shadcn-vue/pull/324

**Comment by sadeghbarati** [comment]
```vue
<script setup>
import { Toaster as Sonner } from "vue-sonner";

const props = defineProps({
  invert: { type: Boolean, required: false },
  theme: { type: String, required: false },
  position: { type: String, required: false }, // union type like 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'top-center' | 'bottom-center'
  hotkey: { type: Array, required: false },
  richColors: { type: Boolean, required: false },
  expand: { type: Boolean, required: false },
  duration: { type: Number, required: false },
  gap: { type: Number, required: false },
  visibleToasts: { type: Number, required: false },
  closeButton: { type: Boolean, required: false },
  toastOptions: { type: Object, required: false },
  class: { type: null, required: false },
  style: { type: null, required: false },
  offset: { type: [String, Number], required: false },
  dir: { type: String, required: false },
  icons: { type: Object, required: false },
  containerAriaLabel: { type: String, required: false },
  pauseWhenPageIsHidden: { type: Boolean, required: false },
  cn: { type: Function, required: false },
});
</script>

<template>
  <!-- Type 'string' is not assignable to type 'Position' (union type) -->
  <Sonner 
    class="toaster group"
    v-bind="props"
    :toast-options="{
      classes: {
        toast:
          'group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground group-[.toaster]:border-border group-[.toaster]:shadow-lg',
        description: 'group-[.toast]:text-muted-foreground',
        actionButton:
          'group-[.toast]:bg-primary group-[.toast]:text-primary-foreground',
        cancelButton:
          'group-[.toast]:bg-muted group-[.toast]:text-muted-foreground',
      },
    }"
  />
</template>

```

**Comment by sadeghbarati** [comment]
@Dunqing Hi

Please check comment above 

`vue-sonner.d.ts` has a type like `Position?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'top-center' | 'bottom-center'`

But `detypes` transform this type to `String`

and I will get this type of error in VSCode

```
Type 'string' is not assignable to type 'Position' (union type)
```

**Comment by zernonia** [comment]
@sadeghbarati  that's weird tho. If `detypes` converted the component to have props `String`, your VSCode shouldn't complain about it when you pass in `position="top-left"`.

**Comment by zernonia** [comment]
@sadeghbarati  hmm I'm wondering why it happened for `vue-sonner`, and not `radix-vue` lol. 🤔

![image](https://github.com/radix-vue/shadcn-vue/assets/59365435/dc6936d1-9cf5-4179-9161-6ab99a52de9b)

**Comment by sadeghbarati** [comment]
https://github.com/radix-vue/shadcn-vue/issues/355#issuecomment-1974775719

I tested this again with fresh Vite (Vue/JS) and it works without TypeScript error
