### ISSUE TITLE
[Bug]: Cannot install Toast

### ISSUE THREAD

**Issue by dasmikko** [radix-vue/shadcn-vue#358]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-k7cybx?file=src%2FApp.vue

### Describe the bug

Trying to install toast in my vue project, that is not using typescript using: `npx shadcn-vue@latest add toast`

```
[@vue/compiler-sfc] Failed to resolve extends base type.
If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @vue-ignore */ before it, for example:

interface Props extends /* @vue-ignore */ Base {}

Note: both in 3.2 or with the ignore, the properties in the base type are treated as fallthrough attrs at runtime.

anonymous.vue
```

Try the command in the reproduction project, and say yes to overwriting.

It installs some files, but some styling seems to be missing, and animations.

### System Info

```bash
System:
    OS: Linux 6.7 Fedora Linux 39 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 37.49 GB / 46.95 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.volta/tools/image/node/20.10.0/bin/node
    Yarn: 3.5.1 - ~/.volta/tools/image/yarn/3.5.1/bin/yarn
    npm: 10.2.3 - ~/.volta/tools/image/node/20.10.0/bin/npm
  Browsers:
    Chrome: 122.0.6261.57
  npmPackages:
    @vueuse/core: ^10.8.0 => 10.8.0 
    radix-vue: ^1.4.7 => 1.4.7 
    vue: 3.4.19 => 3.4.19
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Hi we have a bunch of the same issues so let's track it in this issue

https://github.com/radix-vue/shadcn-vue/issues/355
