### ISSUE TITLE
[Feature]: support vue3 + js(es5)?

### ISSUE THREAD

**Issue by me-v2** [radix-vue/shadcn-vue#360]
### Describe the feature

support vue3 + js(es5)? where find demo or docs?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
@linpan 

`shadcn-vue` is supported `JS` extensions with Dunqing work in CLI, you only need to change "typescript" to false

```diff
{
  "$schema": "https://shadcn-vue.com/schema.json",
  "style": "default",
-  "typescript": true,
+ "typescript": false,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "assets/css/tailwind.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "framework": "nuxt",
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

---

If you are looking to make your app Compatible with older browsers
You can use [`@vitejs/plugin-legacy`](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) to generate legacy bundle for you

**Comment by me-v2** [comment]
shadcn-vue Command  component.   error,  identifier "as", please add test for this component.

**Comment by sadeghbarati** [comment]
@linpan I'm not an expert in `vitest`, `playwright`, or any other testing library

https://twitter.com/tekbog/status/1762238672630423590?t=LWpkgHa5gKwPlLUJO_gBRg&s=19

Feel free to add tests for components and make PR
Can you also update your "Issue Title" cause others would be confused about what the topic of this issue is.

**Comment by sadeghbarati** [comment]
Closing for now 🙏
