### ISSUE TITLE
[Bug]: Cannot select only "time" when using calendar range with mode="time"

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#361]
### Reproduction

None

### Describe the bug

When using this

```
        <Calendar
          v-model.range="model"
          mode="time"
        >
```

the "time" selection is disabled

<img width="170" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/15458/de01e638-46fe-4837-9776-ddf3beb101b7">

### System Info

```bash
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 101.53 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.16.0 - ~/.node/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.1.2
  npmPackages:
    @vueuse/core: 10.8.0 => 10.8.0 
    radix-vue: 1.4.9 => 1.4.9 
    vue: 3.4.19 => 3.4.19
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
You should select a date first then those `select` elements will be usable

**Comment by maelp** [comment]
@sadeghbarati when using "mode=time" there is no date selection

**Comment by sadeghbarati** [comment]
@maelp 

Found this in v-calendar docs

https://vcalendar.io/datepicker/basics.html#time-mode

Your `ref` must be have a value like


`Single Date`
```ts
const date = ref(new Date());
```

`Ranged Date`
```ts
const range = ref({
  start: new Date(),
  end: new Date(),
});
```

---

https://stackblitz.com/edit/srwtxu

**Comment by maelp** [comment]
This works for "single date" but not for "range date" (eg type="range")
