### ISSUE TITLE
[Feature]: Layout components

### ISSUE THREAD

**Issue by prpanto** [radix-vue/shadcn-vue#362]
### Describe the feature

My idea come out from [nuxt ui pro --> DashboardLayout](https://ui.nuxt.com/pro/components/dashboard-layout) component. Something similar to make a layouts fast... 

Components:
1. Layout
2. LayoutPanel
3. LayoutContnet
4. LayoutNavbar
5. LayoutSidebar
6. LayoutSection
7. etc... check nuxt ui pro for more ideas... 

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
@prpanto hey

> Nuxt UI Pro is free in development, but you need a license to use it in production. You can choose between **Solo** and **Team**, both will give you access to the same features and give you a license key required to build your apps. The main difference is the number of developers that can be invited to the private GitHub repository.

We can't do this, we should be aligned with the main shadcn-ui, the duty of `radix-vue` is to bring low and high-level components to the users the rest is on user's shoulders

And `radix-vue` and `shadcn-vue` have most of the components in `nuxt-ui`.
