### ISSUE TITLE
[Bug]: Sonner shows below dialog overlay

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#363]
### Reproduction

None

### Describe the bug

When using sonner component, and showing a notification while a dialog is open, the notification is "below" the overlay, so it is not clickable (cannot close the notification for instance)

https://github.com/radix-vue/shadcn-vue/assets/15458/978d87e9-d302-49f1-ac86-109acbc1ed40

trying to show it in the video: basically I'm adding the "<Toaster>" component below everything in my App.vue, but still, the AlertDialog components are added below it, and therefore the overlay is above (even though I'm adding "zIndex: 100" to both the Toaster and the notification component

### System Info

```bash
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 87.00 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.16.0 - ~/.node/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.1.2
  npmPackages:
    @vueuse/core: 10.8.0 => 10.8.0 
    radix-vue: 1.4.9 => 1.4.9 
    vue: 3.4.19 => 3.4.19
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@maelp 

Hey thanks for repro xd

Where did you put the `Toaster` component?

**Comment by maelp** [comment]
I put it in my App.vue

```
<template>
  <ion-app>
    <ion-router-outlet></ion-router-outlet>
  </ion-app>
  <Toaster></Toaster>
</template>

```

**Comment by sadeghbarati** [comment]
https://www.radix-vue.com/components/dialog.html#disable-close-on-interaction-outside

https://stackblitz.com/edit/t7vaek

Still confuses me why teleport to html xd

```html
<Teleport to="html">
  <Toaster />
</Teleport>
```

**Comment by maelp** [comment]
Thanks, it works with Teleport, perhaps add a comment on the Sonner page so people know that it is possible to do this to show notifications "over" the Dialogs and AlertDialogs?

**Comment by maelp** [comment]
The only case  not handled is if we want a Dialog where clicking outside close the dialog, except if it is to close a notification... is there any way to avoid bubbling-up the event if someone clicks on a notification close button?

**Comment by maelp** [comment]
I tried to add 

```
          $event.preventDefault();
          $event.stopImmediatePropagation();
          $event.stopPropagation();
```

to the click handler of the Toast but it still closes the Dialog if I click on the notification close button

**Comment by maelp** [comment]
ah sorry the page you sent was the wrong link but I see it now thanks!

**Comment by sadeghbarati** [comment]
```vue
 <DialogContent
   @interact-outside="event => {
      const target = event.target as HTMLElement;
      if (target?.closest('[data-sonner-toaster]')) return event.preventDefault()
    }"
  >
  ...
 ```

**Comment by maelp** [comment]
Thanks, just saw it! Might be worth adding it to the documentation too

**Comment by sadeghbarati** [comment]
will be added
