### ISSUE TITLE
[Bug]: either I'm stupid and blind.... but there is no installation directive in the docs :)

### ISSUE THREAD

**Issue by i0FFLINE** [radix-vue/shadcn-vue#365]
### Reproduction

see https://www.shadcn-vue.com/docs/installation.html and https://www.shadcn-vue.com/docs/installation/vite.html

### Describe the bug

There are no instructions on how to install the package. But there is comprehensive information on how to install the companion ones.

### System Info

```bash
Just my eyes, browser and confusion.
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@i0FFLINE Can you have any idea what we should do to improve the `installation` part?

**Comment by sadeghbarati** [comment]
closing for now, will reopen after a good explanation
