### ISSUE TITLE
Dark theme does not work with Nuxt Color Mode

### ISSUE THREAD

**Issue by mr-kelk** [radix-vue/shadcn-vue#366]
Installed Nuxt Color Mode and configured the color switch button 

```<script lang="ts" setup>
const colorMode = useColorMode()
const isDark = computed({
  get() {
    return colorMode.value === 'dark'
  },
  set() {
    colorMode.preference = colorMode.value === 'dark' ? 'light' : 'dark'
  },
})
</script>

<template>
  <div>
    <UIButton variant="ghost" size="icon" @click="isDark = !isDark">
      <Icon :name="isDark ? 'i-heroicons-moon-20-solid' : 'i-heroicons-sun-20-solid'" color="black" />
    </UIButton>
  </div>
</template>
```

but the color doesn't change. How do I configure shadcn-vue to make the dark theme work?

**Comment by mr-kelk** [comment]
In short, sorry, I looked more closely and discovered that I forgot to add to nuxt.config.ts
``` 
colorMode: {
    classSuffix: ""
  },
 ```

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/github-aay4vl?

**Comment by sadeghbarati** [comment]
Someone must land us some help on the dark-mode documentation in Vite and Nuxt :'(

**Comment by AlvesJorge** [comment]
Although this is closed, this should still be added to the documentation.
I get the IDE warning of:
`Object literal may only specify known properties, and 'colorMode' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.ts(2353)` when adding this option though
