### ISSUE TITLE
[Feature]: Drawer (vaul-vue)

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#370]
[Vaul-vue](https://github.com/radix-vue/vaul-vue/releases) should be ready to go now. 🤩

Appreciate the hardwork from @Elliot-Alexander ! 💚

**Comment by Saeid-Za** [comment]
If the base package is available and this issue is not assigned already, I'd be happy to add it to `shadcn-vue`  and add the corresponding documentation.

**Comment by sadeghbarati** [comment]
@Saeid-Za Yeah, the package is stable. Just need a little bit of refactoring, but we can have it in shadcn-vue

**Comment by Saeid-Za** [comment]
Thanks 🙏, is it ok for me to start on this then?
