### ISSUE TITLE
[Bug]: Date range picker is owerflown in mobile screen

### ISSUE THREAD

**Issue by Saeid-Za** [radix-vue/shadcn-vue#375]
### Reproduction

https://stackblitz.com/edit/dmx2uk?file=src%2FApp.vue

### Describe the bug

Currently the Date range picker is owerflown in mobile screens:

![Screenshot_2024-03-04-11-30-24-662_com microsoft emmx](https://github.com/radix-vue/shadcn-vue/assets/65568529/56252d36-58c4-49e9-bb99-cbb266913775)

Here's the same component in `shadcn/ui`
![Screenshot_2024-03-04-11-30-44-410_com microsoft emmx](https://github.com/radix-vue/shadcn-vue/assets/65568529/0f14275d-57a3-4b96-a3c1-160f17149af6)

### System Info

```bash
Not relevent
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by Saeid-Za** [comment]
This issue will be resolved in the near future.

Related Info  - [Here](https://github.com/radix-vue/shadcn-vue/issues/391#issuecomment-1983496837)
> With new Datepicker in radix-vue v1.5.0 we can remove v-calendar

**Comment by sadeghbarati** [comment]
Based on a discussion I had with Zernonia, we will keep it alongside the new calendar
