### ISSUE TITLE
[Feature]: Add missing examples from source

### ISSUE THREAD

**Issue by Saeid-Za** [radix-vue/shadcn-vue#376]
### Describe the feature

There are some missing examples that was recently added to `shadcn/ui`.
I had manually checked the examples and here are the items with new examples:
- [x] Dropdownmenu
- [x] Select
- [x] Skeleton

There is this issue of drifting from new updates when time passes, I'm thinking of an automated way of retrieving the updated file list to manually check and update our source at a later stage, so no updates would be missed.

### Additional information

- [x] I intend to submit a PR for this feature.
- [x] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
@Saeid-Za thanks, Can you add the missing Skeleton example from `shadcn-ui`

https://ui.shadcn.com/docs/components/skeleton#card

**Comment by sadeghbarati** [comment]
Only `Select` scrollable remains feel free to do it in your free time

But keep that in mind you can include all docs changes in one PR

**Comment by Saeid-Za** [comment]
Honestly, I had not planned to do them myself 😅

**Comment by sadeghbarati** [comment]
> I intend to submit a PR for this feature.



sorry xD I saw this as checked lol (in my mind) xdd

**Comment by Saeid-Za** [comment]
This should be enough for now, but the main problem remains, how to get notified of updates from shadcn repo.

**Comment by zernonia** [comment]
This would be interesting feature!! Wonder if there's any GitHub Action that do this 🤔
