### ISSUE TITLE
[Feature]: Customizable Navbar / Customizable Sidebar

### ISSUE THREAD

**Issue by i0FFLINE** [radix-vue/shadcn-vue#381]
### Describe the feature

Unfortunately I didn't see Navbar and normal Sidebar in the components.

Features I would like to see:
- Positioning:;
  - Normal: all props default;
  - Fixed: width 100% for Navbar and customisable for Sidebar;
  - Left/Right: width-compressed Navbar with binding to the side of the screen. OR optional condencing entire Navbar;
  - Absolute: with customizable positioning via properties.
- Content through slots - coding in the root level of component;
- Sidebar collapsing in 3 mode: Expanded, Icons with tooltips only and fully collapsed under hambuger;
- Mobile View;
- CSS via outside (root component) declarations: no colors inside subcomponent - all apps have different color set.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by i0FFLINE** [comment]
That sounded like a challenge.)

**Comment by sadeghbarati** [comment]
> This project's goal is to remain aligned with [shadcn/ui](https://github.com/shadcn-ui/ui). If the feature you are requesting is not in the original shadcn/ui, it will not be considered here.

---

The features you want are available in 

https://vuetifyjs.com/en/components/navigation-drawers/

**Comment by i0FFLINE** [comment]
changed ui to DaisyUI. unsubscribed. thanks all.
