### ISSUE TITLE
[Bug]: Unable to close Combobox with `Esc` key

### ISSUE THREAD

**Issue by MellKam** [radix-vue/shadcn-vue#386]
### Reproduction

https://www.shadcn-vue.com/docs/components/combobox.html

### Describe the bug

You can check that it works with shadcn-ui https://ui.shadcn.com/docs/components/combobox

### System Info

```bash
-
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
~~It is because `vue-sonner` bug~~

after this PR gets released it should be fixed

https://github.com/xiaoluoboding/vue-sonner/pull/57

It was not about the `vue-sonner` bug, will check for the fix

**Comment by sadeghbarati** [comment]
[`PopoverContent`](https://www.radix-vue.com/components/popover.html#content) and [`ComboboxContent`](https://www.radix-vue.com/components/popover.html#content) both have dismissable layers which I don't know its good or not


I like how react-aria handled this for example if set props for PopoverContent it is also applied to to same logically component in the child

@zernonia 

Should I have to **omit** the same PopoverEmits from CommandList in `shadcn-vue`?

**Comment by zernonia** [comment]
Yup I realized this issue. For now we can set `:dismissable="false"` for `ComboboxContent`. In future we can use `ListBox` component instead of combobox.
