### ISSUE TITLE
[Bug]: Unable to install additional components

### ISSUE THREAD

**Issue by LukaszMoskwaCTW** [radix-vue/shadcn-vue#387]
### Describe the bug

I'm using shadcn-vue with Nuxt, my components.json is the following

```json
{
  "$schema": "https://shadcn-vue.com/schema.json",
  "style": "default",
  "typescript": true,
  "tailwind": {
    "config": "tailwind2.config.js",
    "css": "assets/css/tailwind.css",
    "baseColor": "slate",
    "cssVariables": false
  },
  "framework": "nuxt",
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

And when I'm trying to add a new component with 

```
pnpm dlx shadcn-vue@latest add tabs
```

I get the following

![image](https://github.com/radix-vue/shadcn-vue/assets/117134305/4c0ee800-2f49-4d10-b43a-8ca2023e62a8)

This used to work yesterday and I was able to add Button, Textarea, Input and many more without issues. There were no changes to the components.json file

### System Info

```bash
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 197.50 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /opt/local/bin/node
    Yarn: 1.22.19 - /opt/local/bin/yarn
    npm: 8.19.4 - /opt/local/bin/npm
    pnpm: 8.3.1 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - /usr/local/bin/bun
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 16.6
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    nuxt: ^3.10.2 => 3.10.2 
    radix-vue: ^1.4.9 => 1.4.9 
    shadcn-nuxt: ^0.9.0 => 0.9.0 
    vue: ^3.4.19 => 3.4.19
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by youkei-zzz** [comment]
Yes, I also encountered this problem

**Comment by sadeghbarati** [comment]
Yes I think it's related to `c12` (jiti), for now please copy and paste components

**Comment by megaarmos** [comment]
Yup, i'm facing the same problem too

**Comment by MasterShu** [comment]
Yes, I'm facing this problem too.
