### ISSUE TITLE
[Bug]: [vite-node] [plugin:vite:vue] [VITE_ERROR] /components/ui/avatar/AvatarImage.vue

### ISSUE THREAD

**Issue by selemondev** [radix-vue/shadcn-vue#39]
### Environment

```bash
Developement/Production OS: MacOs
Node version: v18.16.1
Package manager: pnpm@8.6.7
Radix Vue version: 0.1.32
Vue version: 3.0.0
Nuxt version: 3.7.1
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-wbuhpq?file=app.vue

### Steps to reproduce

1. Installing a new component using the `shadcn-vue` CLI: npx shadcn-vue@latest add button

2. After the button has been successfully installed, it maps to the wrong path: `@/lib/registry/default/ui/avatar` and then I correct it to: `@/components/ui/avatar`

3. I go ahead and use it in my `app.vue` file as shown below : 

```js
<script setup lang="ts">
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
</script>

<template>
  <Avatar>
    <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
    <AvatarFallback>CN</AvatarFallback>
  </Avatar>
</template>
```

4. When I start my dev server by running `pnpm dev` it throws this error:  

[08:07:23]  WARN  [nuxt] Two component files resolving to the same name UiAvatar:

 - /home/projects/nuxt-starter-4b4eme/components/ui/avatar/index.ts
 - /home/projects/nuxt-starter-4b4eme/components/ui/avatar/Avatar.vue

7. When I navigate to `localhost:3000`, I get the following error: 

500
[vite-node] [plugin:vite:vue] [VITE_ERROR] /components/ui/avatar/AvatarImage.vue

<script setup lang="ts">
import { AvatarImage, type AvatarImageProps } from 'radix-vue'

const props = defineProps<AvatarImageProps>()
</script>

<template>
  <AvatarImage v-bind="props" class="h-full w-full object-cover" />
</template>

at /components/ui/avatar/AvatarImage.vue

### Describe the bug

Whenever I add a new component using the `shadcn-vue` CLI and start up my server, I get the following errors: 

[08:07:23]  WARN  [nuxt] Two component files resolving to the same name UiAvatar:

 - /home/projects/nuxt-starter-4b4eme/components/ui/avatar/index.ts
 - /home/projects/nuxt-starter-4b4eme/components/ui/avatar/Avatar.vue

When I navigate to `localhost:3000`, the whole application has crashed and I get this error: 

500
[vite-node] [plugin:vite:vue] [VITE_ERROR] /components/ui/avatar/AvatarImage.vue

<script setup lang="ts">
import { AvatarImage, type AvatarImageProps } from 'radix-vue'

const props = defineProps<AvatarImageProps>()
</script>

<template>
  <AvatarImage v-bind="props" class="h-full w-full object-cover" />
</template>

at /components/ui/avatar/AvatarImage.vue

### Expected behavior

I should see the output of whichever component I copied. For example, if I copied the `Avatar` component, I should see the avatar UI component rendered in the browser.

### Conext & Screenshots (if applicable)

[08:07:23]  WARN  [nuxt] Two component files resolving to the same name UiAvatar:

 - /home/projects/nuxt-starter-4b4eme/components/ui/avatar/index.ts
 - /home/projects/nuxt-starter-4b4eme/components/ui/avatar/Avatar.vue

**Comment by zernonia** [comment]
@selemondev  this should be due to Nuxt3 autoImport feature, which might messed up the imports.

**Comment by sebastiaanluca** [comment]
> After the button has been successfully installed, it maps to the wrong path: @/lib/registry/default/ui/avatar and then I correct it to: @/components/ui/avatar

I've added shadcn-vue in an existing Vite + Tailwind project, and successfully set up components.json and all steps outlined in the installation guide. However when doing `npx shadcn-vue@latest add select` or any other, it adds the Select component but completely ignores the configured `components.json` in the project root dir.

E.g. `tailwind.cssVariables` would be set to `false`, but the added component and its files would use CSS variables instead of Tailwind classes. Same for the path to the helpers import and any other configured setting.

**Comment by zernonia** [comment]
@selemondev  could you check if this issue still happening? 😁

**Comment by selemondev** [comment]
@zernonia I still get the same error as above but this time in the terminal I get the following error: ` ERROR  Cannot read properties of undefined (reading 'sys') (x4)` and in the browser: 

`[vite-node] [plugin:vite:vue] [VITE_ERROR] /components/ui/avatar/AvatarImage.vue

<script setup lang="ts">
import { AvatarImage, type AvatarImageProps } from 'radix-vue'

const props = defineProps<AvatarImageProps>()
</script>

<template>
  <AvatarImage v-bind="props" class="h-full w-full object-cover" />
</template>`

**Comment by zernonia** [comment]
The new issue seems to be related to https://github.com/radix-vue/shadcn-vue/issues/70

**Comment by selemondev** [comment]
Thanks, it worked. Can we reference that in the docs as a temporary solution until it's fixed so that devs might not have to wonder what's wrong?

**Comment by zernonia** [comment]
Awesome @selemondev ! Could you help contributing by adding that text in Nuxt installation section? 😁

**Comment by selemondev** [comment]
Sure ✨

**Comment by zernonia** [comment]
Can I close this @selemondev  and we will track the Nuxt3 issue you mentioned above [here](https://github.com/radix-vue/shadcn-vue/issues/70)? 😁

**Comment by selemondev** [comment]
OK.

**Comment by ValeronS** [comment]
SOLUTION: you have to install typescript dependency

**Comment by selemondev** [comment]
> SOLUTION: you have to install typescript dependency

We documentated it [here](https://github.com/radix-vue/shadcn-vue/pull/71).
