### ISSUE TITLE
[Feature]: add a color picker component

### ISSUE THREAD

**Issue by lord007tn** [radix-vue/shadcn-vue#390]
### Describe the feature

A color picker component seems needed for some saas products allowing clients to customize their brand.
this is the case for me now and I'm currently using the default 
```
<input name="inputColor" type="color" />
```

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
https://github.com/radix-vue/radix-vue/issues/501

It is already an issue in `radix-vue` please feel free to close this then 👍
