### ISSUE TITLE
[Bug]: Range datepicker not suitable for mobile use

### ISSUE THREAD

**Issue by lord007tn** [radix-vue/shadcn-vue#391]
### Reproduction

https://www.shadcn-vue.com/docs/components/date-picker.html#date-range-picker

### Describe the bug

The range datepicker when opened in the mobile application is not fully presented on the screen 
and i think in mobile we should have a customer one that is a combination of modal and scrollable months 
i already did develop something from scratch in work that supports internationalization also see below 

![image](https://github.com/radix-vue/shadcn-vue/assets/38087431/ecbe94f0-1a45-4feb-aced-21d5da25ff34)
![image](https://github.com/radix-vue/shadcn-vue/assets/38087431/c7dece54-c52f-4acd-8383-89327bc9a885)

i think that's more suitable and more user-friendly for mobile 

the challenge here is we are using `v-calendar` so we need to override the use of it in mobile screens < 768px 

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 10.98 GB / 31.16 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.3 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.7.1 => 10.7.1
    radix-vue: ^1.3.0 => 1.4.6
    vue: ^3.4.11 => 3.4.11
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
With new Datepicker in `radix-vue` v1.5.0 we can remove `v-calendar`

**Comment by lord007tn** [comment]
> With new Datepicker in `radix-vue` v1.5.0 we can remove `v-calendar`

good, but still in mobile seems like it's forced in the ui
mobile users have an established feeling about how calendars and date pickers work

**Comment by sadeghbarati** [comment]
@lord007tn With the new [`radix-vue` Calendar](https://www.radix-vue.com/components/calendar.html) You can style the calendar any way you want


closing this as duplicated of 375
