### ISSUE TITLE
[Feature]: Duration picker

### ISSUE THREAD

**Issue by lord007tn** [radix-vue/shadcn-vue#392]
### Describe the feature

I think that a Duration picker component would be valuable for some people 
already develop something using `dayjs` and our current `Input` component

![image](https://github.com/radix-vue/shadcn-vue/assets/38087431/d2328c0f-2167-4522-b369-a1d75a220345)
i can activate the hours also and everything is returned in seconds as base unit so you can transfer it to whatever format you want

What do you think?

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
With the new `radix-vue` DateField it could be handled more easily

![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/5f7f4253-4446-4e85-9050-be096ba800e2)
