### ISSUE TITLE
[Feature]: Breadcrumb component

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#395]
### Describe the feature

New component on https://ui.shadcn.com/docs/components/breadcrumb

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by Saeid-Za** [comment]
Is it ok if I start on this?

**Comment by sadeghbarati** [comment]
Sure Buddy ❤️
