### ISSUE TITLE
[Bug]: Some StackBlitz New-York demos are using the incorrect icon library

### ISSUE THREAD

**Issue by jtotty** [radix-vue/shadcn-vue#403]
### Reproduction

https://stackblitz.com/run?file=src%2FApp.vue

### Describe the bug

When running component demos on StackBlitz with the `new-york` style option, it throws the following error: `[plugin:vite:import-analysis] Failed to resolve import "lucide-vue-next" from "src/App.vue". Does the file exist?`

Issue: Some of the `new-york` demos are still trying to use Lucide icons instead of Radix.

### System Info

```bash
Running on the Stackblitz demo clicked via the Shadcn/vue documentation site.
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Hi, can you save your Stackblitz (will fork afterward)

or Hit the fork button then share the link?

**Comment by sadeghbarati** [comment]
- `default` ---> `lucide-vue-next`

https://stackblitz.com/edit/rbpkhk

---

- `new-york` ---> `@radix-icons/vue`

https://stackblitz.com/edit/fd1u3y

**Comment by jtotty** [comment]
Do you still want my Stackblitz?

**Comment by sadeghbarati** [comment]
If it's ok, nope

**Comment by jtotty** [comment]
Ok, no problem.

Further info: the `new-york` demo for the `Alert` component is trying to use Lucide instead of radix. I'm not sure what other ones there are. I can check for you if you'd like and post the list here?

**Comment by sadeghbarati** [comment]
Thanks. List it, please. I'll check

**Comment by jtotty** [comment]
I've checked every StackBlitz `new-york` demo for each component.

**List of demos using the Lucide icons instead of Radix (items without sub items means all demos for that component)**
- Alert
- Button
    - Loading
    - Icon
    - With Icon
- Card
    - Card Demo
- Carousel
    - Plugin
- Collapsible
- Combobox
    - All demos apart from the Combobox Responsive
- Command
- Data Table
- Date Picker
- Dialog
    - Custom Close Button
- Drawer
- Dropdown Menu
    - Demo (first only)
- Hover Card
- Navigation Menu
- Toggle
- Toggle Group

---

**Naturally, I found a handful of other errors:**
- Form - Auto Animate (missing `@formkit/auto-animate/vue`)
- Sonner (missing `vue-sonner`)
- Toast
    - Demo, Simple, and With Title are (missing  `@/components/ui/toast/use-toast`)
    - With Action and Destructive - the toast does not appear when clicking the button
    
---

  I'd be more than happy to update them for you. (Not sure how to do so with Stackblitz)
