### ISSUE TITLE
[Bug]: ComboBox not working due to DialogScrollContent

### ISSUE THREAD

**Issue by a1danw** [radix-vue/shadcn-vue#406]
### Reproduction

Use any ComboBox example

### Describe the bug

Uncaught SyntaxError: Unexpected identifier 'as' (at DialogScrollContent.vue:70:47)

### System Info

```bash
"vite": "^5.0.11",
"radix-vue": "^1.5.2",
"tailwindcss": "^3.4.1",
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by a1danw** [comment]
I removed the type assertion inside DialogScrollContent which has fixed the issue

**Comment by abhinavxd** [comment]
Worked for me as well.
