### ISSUE TITLE
[Docs]: Adding Detailed Contribution Guide

### ISSUE THREAD

**Issue by Saeid-Za** [radix-vue/shadcn-vue#409]
### Describe the feature

There are several patterns used across this repository, which can make contributing difficult for newcomers without a guide. It's better to have a dedicated and detailed contribution guide to attract more contributors.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
It's worth adding this, too

![312352720-ab3d8ea8-0796-4604-99c2-03249b41ae4c](https://github.com/radix-vue/shadcn-vue/assets/17789047/c6696ad8-9c78-46d7-9e56-50c17ab9146d)
