### ISSUE TITLE
[Bug]: Popover in Tags Input with Combobox doesn't close when clicking outside.

### ISSUE THREAD

**Issue by BroccoliBasti** [radix-vue/shadcn-vue#410]
### Reproduction

https://stackblitz.com/edit/cku9c3?file=src%2FApp.vue

### Describe the bug

When using the Tags Input with Combobox the popover doesn't close when you click outside of it, nor can it be closed by any other means. This issue is also present in the documentation page for Tags Input:
![Popover issue](https://github.com/radix-vue/shadcn-vue/assets/100607489/fe238b01-11bd-44ed-b326-5cb1537f1a96)

### System Info

```bash
Tested in the latest versions of both Brave and Firefox.
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@BroccoliBasti Hey just use `dismissable` on `CommandList`


For some reason, we decided to make the default `dismissable` prop in `CommandList` to **false**, until the new `Listbox` component arrives at the `radix-vue`


The reason was `Popover` already had `DismissableLayer` and `CommandList` also had the same functionality too

**Comment by Flowko** [comment]
@sadeghbarati any news about this ? since Listbox component was released

**Comment by letovsk1y** [comment]
@sadeghbarati any updates? 
ListBox released, `dismissable` now deprecated and removed at 2.0.0 version of radix vue

**Comment by sadeghbarati** [comment]
@Flowko sorry for late response
@letovsk1y 

https://stackblitz.com/edit/5stbzq?file=src%2FApp.vue

Popover + Listbox is more recommended for now

Hope v2 land soon then we can use these component without worrying about these problems
