### ISSUE TITLE
[Feature]: Programmatic Tooltip / Popover

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#416]
### Describe the feature

Not sure if that's a shadcn or a Radix-vue question, but I'm implementing a line graph in d3 and when the user hovers on a point {clientX, clientY} I'd like to show a tooltip / popover below / above, taking into account the available space on screen (so that it doesn't go "out of the screen" like the regular shadcn tooltip/popover)

What would be the best way for me to do this?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by Saeid-Za** [comment]
Hello ! 
I've encountered similar problem a while ago, here's my solution.
Since we have no access to d3 chart `point` in our `Trigger` component, we'll need to do some manual work here.

`menu.ts` -> Menu Composable, storing element position on the screen.

```ts
type PointType = { 
	// Type Your Point Here
}

export function useMenu() {
	const isOpen = ref(false)
	const position = ref({ left: "0px", top: "0px" })
	const selectedNode = ref<PointType | null>(null)

	function openMenu(event: MouseEvent, newData?: PointType) {
		selectedNode.value = newData
		position.value = { left: `${event.x}px`, top: `${event.y}px` }
		isOpen.value = true
	}

	function closeMenu() {
		isOpen.value = false
	}

	return {
		position,
		selectedNode,
		isOpen,
		openMenu,
		closeMenu,
	}
}
```

The usage: 

```vue
<script setup lang="ts">
import type { Selection } from "d3"

const menu = useMenu()

function registerHoverEvent(node: Selection<any, any, any, any>) {
  node.on("mouseenter", (event: MouseEvent, context) => {
	  tooltip.openMenu(event, context.data)
  })
  
  node.on("mouseleave", () => {
	  tooltip.closeMenu()
  })
}


// Register Hover Event on your d3 instance.
</script>

<template>
	<Popover v-model:open="menu.isOpen.value">
		<PopoverTrigger
			class="fixed"
			:style="menu.position.value" />

		<PopoverContent
			class="w-80"
			:align-offset="-10"
			:side-offset="30">
		</PopoverContent>
	</Popover>
</template>
```

> taking into account the available space on screen (so that it doesn't go "out of the screen" like the regular shadcn tooltip/popover)

I think the `Popover` itself take the available space into account using [`Floating UI`](https://floating-ui.com/). this is done in `radix-vue` scope.
