### ISSUE TITLE
[Feature]: Addressing the limitations for [RTL] layouts out of the box

### ISSUE THREAD

**Issue by omar-labana** [radix-vue/shadcn-vue#421]
### Describe the feature

I'm building a couple of multilingual projects that require some reactive layout direction and most of the time to keep things localized I find myself replacing many of the classes like `pl-` & `pr-` with inline padding `ps-`. Also, some of the components like `<Carousel>` will be completely unusable on right-to-left layouts and it would scroll in the other direction(with slides being replaced with whitespace) despite using the radix-ui config provider, has anyone been through the same issue? would it be acceptable to submit a pr covering these challenges?

### Additional information

- [X] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
We have PR https://github.com/radix-vue/shadcn-vue/pull/379 (change directional properties to logical properties)

The reason we hold it, we must see what other's opinions are

Also, you are right that `Carousel` does not respect `radix-vue` ConfigProvider `dir`

**Comment by sadeghbarati** [comment]
Let's track it here

https://github.com/radix-vue/shadcn-vue/issues/357
