### ISSUE TITLE
[Bug]: Select Component Overflowing outside HTML Tag

### ISSUE THREAD

**Issue by setyawannn** [radix-vue/shadcn-vue#422]
### Reproduction

https://github.com/setyawannn/bug-shadcn-vue

### Describe the bug

I wanna build admin dashboard with fixed sidebar and navbar, the main content is the one off scrollable but i got error when using select in shadcn-vue but if i change to input or default select from html nothing happened, the details of the error my page is overflowing but when i inspect in browser the overflowing is outside of HTML Tag

![Screenshot (83)](https://github.com/radix-vue/shadcn-vue/assets/99939488/f5c305bb-b736-4e9d-815b-7e14aa67e153)

### System Info

```bash
Nuxt 3
Google Chrome
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
I tested your site, search for 

```
mx-auto w-screen h-screen flex flex-col bg-slate-50 dark:bg-slate-900
```

and replaced with

```
mx-auto w-screen min-h-screen flex flex-col bg-slate-50 dark:bg-slate-900
```

problem is you are using `h-screen`, you need to use min-height instead `min-h-screen`

Also I see many warning while running the dev command use manual nuxt module it's easier to configure

**Comment by setyawannn** [comment]
it doesn't work in my code, i think the size of the desktop are different
