### ISSUE TITLE
[Feature]: Using the Combobox element of radix-vue

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#423]
### Describe the feature

It seems that shadcn reimplements its Combobox element, although radix-vue defines one, why is that?

Wouldn't it be better to use the radix-vue element, which seems to have more capabilities (eg set its own searchFilter, etc)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by maelp** [comment]
This might also solve https://github.com/radix-vue/shadcn-vue/pull/368 if we use the GCombobox instead(?)

**Comment by sadeghbarati** [comment]
`shadcn-vue` has `Command` components which are based on `Combobox` components from `radix-vue` it only has a different name

and `shadcn-vue`, Combobox is also mixed with `Command` and `Popover` components


I was confused too, but I think after `Listbox` things should be clear up
