### ISSUE TITLE
[Bug]: CommandList size

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#425]
### Reproduction

Not needed

### Describe the bug

The code includes a max-h-[300px] in https://github.com/radix-vue/shadcn-vue/blob/8982ec3862b42777192edd7926506a31b02d9dfc/apps/www/src/lib/registry/default/ui/command/CommandList.vue#L22

but it's not clear why?

I wanted to do a kind of "search panel" taking the whole screen using a Command and CommandList, and was wondering why it had a limited size, any reason?

### System Info

```bash
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 94.13 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.16.0 - ~/.node/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 123.0.6312.58
    Safari: 17.1.2
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
There is no reason, I just copied the TailwindCSS classes from shadcn-ui 😄 

https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/command.tsx#L65
