### ISSUE TITLE
[Bug]: `shadcn-nuxt` when the `buildDir` is changed an error is thrown `ENOENT: no such file or directory, stat 'PROJECT_PATH/.nuxt/tsconfig.json'`

### ISSUE THREAD

**Issue by samk-dev** [radix-vue/shadcn-vue#429]
### Reproduction

https://stackblitz.com/edit/github-gxjekn?file=nuxt.config.ts

### Describe the bug

when changing the `buildDir` from `nuxt.config.ts` the cli throws an error when generating new components `ENOENT: no such file or directory, stat 'PROJECT_PATH/.nuxt/tsconfig.json'`.

<img width="652" alt="Screenshot 2024-03-23 at 11 24 05" src="https://github.com/radix-vue/shadcn-vue/assets/33263129/2e71eb10-c98c-4167-90e5-2ef45ca239d5">

### System Info

```bash
- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.11.1`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `devtools`, `app`, `modules`, `shadcn`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.11.4`, `shadcn-nuxt@0.10.2`
- Build Modules:    `-`
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [x] I am willing to submit a PR with failing tests

**Comment by samk-dev** [comment]
I have found the cause of the issue :)

In `packages/cli/src/utils/get-config.ts` on line `71` the `buildDir` is being accessed with static string`.nuxt`

```ts
let tsConfigPath = path.resolve(
    cwd,
    config.framework === 'nuxt' ? '.nuxt/tsconfig.json' : './tsconfig.json',
  )
```

I will check later if I have time to try to pass the `buildDir` from maybe `components.json` or `nuxt.config` as it's only affecting Nuxt?

Thanks

**Comment by zernonia** [comment]
As Nuxt will generate a custom `tsconfig.json` in `.nuxt` folder, thus we are referencing that. Can you help check if `.nuxt` folder exist in your project? 😁

**Comment by samk-dev** [comment]
Hey @zernonia 

When the `buildDir` is changed from `nuxt.config` the `.nuxt` dir changes it's name to that value here's the [docs](https://nuxt.com/docs/api/nuxt-config#builddir) 

```js
export default defineNuxtConfig({
  buildDir: '.dist' // .nuxt dir will be renamed to .dist
})
```

in `packages/cli/src/utils/get-config.ts` the static `.nuxt` should be changed to pull a dynamic value from somewhere, it could be from `components.json`

```js
const nuxtBuildDir = // we can get it from components.json if the option is added there
let tsConfigPath = path.resolve(
    cwd,
    // change this
    config.framework === 'nuxt' ? '.nuxt/tsconfig.json' : './tsconfig.json',
    // to something like this
    config.framework === 'nuxt' ? '${nuxtBuildDir}/tsconfig.json' : './tsconfig.json',
  )
```

sorry I couldn't do the contribution I am a little bit busy.

**Comment by samk-dev** [comment]
@zernonia I have submitted a pr to resolve this issue [pr](https://github.com/radix-vue/shadcn-vue/pull/447) let me know if anything need to be modified
