### ISSUE TITLE
[Bug]: StackBlitz, shadcn-nuxt – Error: Cannot load native addon because loading addons is disabled

### ISSUE THREAD

**Issue by bogdan0083** [radix-vue/shadcn-vue#433]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-8bnktk?file=package.json

### Describe the bug

Right now it's not possible to create reproduction on `StackBlitz` and use `shadcn-nuxt` as a dependency. It throws error: 

```
[11:56:05]  ERROR  Error while requiring module shadcn-nuxt: Error: Cannot load native addon because loading addons is disabled: /home/projects/nuxt-starter-8bnktk/node_modules/@oxc-parser/binding-linux-x64-musl/parser.linux-x64-musl.node


[11:56:05]  ERROR  Cannot load native addon because loading addons is disabled: /home/projects/nuxt-starter-8bnktk/node_modules/@oxc-parser/binding-linux-x64-musl/parser.linux-x64-musl.node
```

Basically it's because `oxc-parser` dependency uses native addons under the hood, but [WebContainers don't support it](https://developer.stackblitz.com/platform/webcontainers/troubleshooting-webcontainers#cannot-load-native-addon)

### System Info

```bash
(taken from stackblitz repro):

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    nuxt: ^3.11.1 => 3.11.1 
    shadcn-nuxt: ^0.10.2 => 0.10.2
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by Saeid-Za** [comment]
It seems that there is an official [wasm](https://www.npmjs.com/package/@oxc-parser/wasm) release. we could swap the native one with wasm.

More Info [Here](https://github.com/oxc-project/oxc/issues/301#issuecomment-1918667617).

**Comment by Saeid-Za** [comment]
There is an issue with `wasm` release. I've opened an issue [here.](https://github.com/oxc-project/oxc/issues/2828)

**Comment by kelvinsekx** [comment]
Commenting to keep me updated on the progress.

**Comment by sadeghbarati** [comment]
@kelvinsekx Hi, you can subscriber to the issue with this button instead of notifying others 🙏 

![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/99b6428c-b654-42c1-928d-e11765a941f6)

**Comment by Saeid-Za** [comment]
The upstream issue is resolved, I think we could go forward using wasm build.
