### ISSUE TITLE
[Bug]:  use Select or Popver find:  Cannot destructure property 'name' of '_ref' as it is undefined.

### ISSUE THREAD

**Issue by jilongsong** [radix-vue/shadcn-vue#438]
### Reproduction

s

### Describe the bug

![a66581ef2a262cfb76743884f265058e](https://github.com/radix-vue/shadcn-vue/assets/135537059/b2c1690a-3ba5-475b-a0c7-1a23e8aa91b9)

![8de7a1fb91f8afeeef677c4e86ce955a](https://github.com/radix-vue/shadcn-vue/assets/135537059/d4c6d1e7-b10a-44aa-9ec6-ae8b209598b8)

### System Info

```bash
"devDependencies": {
    "@intlify/unplugin-vue-i18n": "^0.11.0",
    "@originjs/vite-plugin-federation": "^1.3.3",
    "@types/node": "^18.0.0",
    "@types/serialize-javascript": "^5.0.1",
    "@vitejs/plugin-vue": "^5.0.3",
    "@vue/test-utils": "^2.0.2",
    "@vue/tsconfig": "^0.1.3",
    "autoprefixer": "^10.4.19",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.38",
    "sass": "^1.54.8",
    "svgo": "^3.0.2",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.3.2",
    "vite": "^5.0.4",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-svg-icons": "^2.0.1",
    "vue-tsc": "^1.8.24"
  }

"vue": "^3.4.0",
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
@jilongsong  can you share a minimal reproduction with this issue? This looks oddly specific issue that you are having, and we need input from you on how to re-create this issue

**Comment by jilongsong** [comment]
This is an issue with the Vue version. I upgraded it to the same version as the radix Vue and it was resolved
