### ISSUE TITLE
[Bug]: Slider range selection: second SliderThumb missing

### ISSUE THREAD

**Issue by andrashann** [radix-vue/shadcn-vue#443]
### Reproduction

https://stackblitz.com/edit/v9flpn?file=src%2FApp.vue

### Describe the bug

Building on the the example code given for `Slider`, if we have an array for the model value, e.g. `const modelValue = ref([12,60])` with `v-model="modelValue"`, a range shows up, which can be dragged on both ends, but there is no SliderThumb present.
<img width="265" alt="No second SliderThumb" src="https://github.com/radix-vue/shadcn-vue/assets/7822872/b9e4b2d2-c8e5-489e-9593-62348102b320">

### System Info

```bash
(note: I ran this on StackBlitz)

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    radix-vue: ^1.5.3 => 1.5.3 
    shadcn-vue: latest => 0.10.2 
    vue: latest => 3.4.21
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
In order to show the 2nd thumb, you need to add another `SliderThumb`.  https://stackblitz.com/edit/v9flpn-aotck7?file=src%2Fcomponents%2Fui%2Fslider%2FSlider.vue
