### ISSUE TITLE
[Documentation] Add Reminder to Include Tailwind Generated CSS Rule

### ISSUE THREAD

**Issue by catnaut** [radix-vue/shadcn-vue#445]
(Apologies for any language barriers; English is my second language.)

As someone relatively new to front-end development, I recently encountered an issue when following instructions to add "shad-cn" to my project. Instead of starting from a template repository, I created my project using "pnpm create vue." Unfortunately, the styles didn't display correctly, and it took me some time to realize that I had omitted to import the Tailwind CSS generated rule. This problem caused quite a bit of confusion for me.

I'm suggesting the addition of a reminder within the documentation to include the Tailwind generated CSS rule. This simple addition would greatly benefit users like myself who might overlook this crucial step, especially newcomers to front-end development.

Thank you for considering this enhancement to the documentation.

**Comment by hrynevychroman** [comment]
@catnaut you just moved all css styles to `src/style.css` am I right?

**Comment by sadeghbarati** [comment]
@catnaut what about we creating boilerplates for radix-vue and shadcn-vue projects?

**Comment by catnaut** [comment]
> @catnaut you just moved all CSS styles to `src/style.css` am I right?

Yes, I fix the import and all going right.

**Comment by catnaut** [comment]
@sadeghbarati @romanhrynevych 
In the documentation, the following command is recommended:
```
npm create vite@latest my-vue-app -- --template vue-ts
```
However, the `vue-ts` template uses `/src/style.css` as the global CSS file, while `shadcn-vue` initialization uses `/src/assets/index.css` as the default setting.

In my opinion, it would be better to align the default option with the official template (either by keeping everything simple or by clearly indicating the difference in options).

![image](https://github.com/radix-vue/shadcn-vue/assets/127472258/e2500af5-c5f9-443b-835f-44a3bd143164)
[Here's a guide on installing Tailwind CSS using `./style.css` ](https://tailwindcss.com/docs/guides/vite#vue)

**Comment by sadeghbarati** [comment]
In this PR https://github.com/radix-vue/shadcn-vue/pull/505, we changed the installation steps about `assets/index.css`

Also, I'll speak to other maintainers for making boilerplates like this 
https://github.com/dishait/tov-template

But for `shadcn-vue`
