### ISSUE TITLE
[Bug]: Using `cssVariables: false` causing Tailwind classes to be wrong for Calendar

### ISSUE THREAD

**Issue by antonreshetov** [radix-vue/shadcn-vue#456]
### Reproduction

none

### Describe the bug

Steps to reproduce

1. Run `npx shadcn-vue@latest init`
2. Select "No" for the question: "Do you want to use CSS variables for colors?"
3. Run `npx shadcn-vue@latest add calendar`
4. Use `Calendar` component

Utility classes option not working at all

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 90.19 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.87
    Chrome Canary: 125.0.6395.0
    Edge: 113.0.1774.35
    Safari: 17.2.1
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    radix-vue: ^1.6.1 => 1.6.1 
    vue: ^3.4.15 => 3.4.18
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
This is the hard part cause in `transform-css-vars.ts` we only look up for classes in `<template>` section not in `<style>`

Try new calendar after it gets merged it's really nicer

**Comment by sadeghbarati** [comment]
I believe it's preferable to disregard `v-calendar` since it hasn't received updates in the past six months
