### ISSUE TITLE
[Bug]: When adding components from npx

### ISSUE THREAD

**Issue by bsayat** [radix-vue/shadcn-vue#457]
### Reproduction

I'm trying to add shadcn components using CLI

### Describe the bug

I create nuxtjs app and install shadcn using installation guide in docs. There is my components.json file

````
{
  "$schema": "https://shadcn-vue.com/schema.json",
  "style": "new-york",
  "typescript": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "assets/css/tailwind.css",
    "baseColor": "zinc",
    "cssVariables": true
  },
  "framework": "nuxt",
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
````
After I start adding components, but get error while installing this components

1. Form `Command failed with exit code 1: yarn add vee-validate @vee-validate/zod zod`
2. Calendar `Command failed with exit code 1: yarn add @vueuse/core v-calendar@next`
3. Input `Command failed with exit code 1: yarn add @vueuse/core`
4. Sonner `Command failed with exit code 1: yarn add vue-sonner`
5. Textarea `Command failed with exit code 1: yarn add @vueuse/core `

using `yarn` to add deps

### System Info

```bash
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 7.37 GB / 15.51 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    bun: 1.0.35 - /usr/local/bin/bun
  Browsers:
    Chrome: 123.0.6312.105
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@bsayat Hey it should be fixed after this PR get released 

BTW you are using yarn and npm commands together?

**Comment by sadeghbarati** [comment]
- Tested with new CLI PR changes adding components is working for me with `yarn` in normal Windows 11 (not WSL) or macOS,

- I also tested with `npx shadcn-vue@latest init` and `add`
 it has a bug in `init` command which sometimes not installing the deps correctly but adding `form` is working for me with `yarn v1.22.21`

**Comment by bsayat** [comment]
@sadeghbarati hello, I fixed it, just used npm. I will try today reinstall components with yarn. Thanks for your prompt response.

**Comment by bsayat** [comment]
@sadeghbarati i tried to install via yarn and it works. thx guys!
