### ISSUE TITLE
[Bug]: Form default values not displayed in dialog component

### ISSUE THREAD

**Issue by A-kirami** [radix-vue/shadcn-vue#459]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-kztmwi?file=src%2FApp.vue

### Description
Default values are not displaying in forms within the dialog component after the first opening.

### Steps to reproduce
1. Click to open the dialog.
![image](https://github.com/radix-vue/shadcn-vue/assets/66513481/7aa0e674-ad4a-46fa-820c-04f1c9e41325)
2. Close the dialog.
3. Open the dialog again.
![image](https://github.com/radix-vue/shadcn-vue/assets/66513481/a00e42c9-4136-4b7e-a7d2-8292f9340768)

### Expected behavior
The default values within the form should remain visible upon subsequent openings of the dialog.

### System Info

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    radix-vue: ^1.6.1 => 1.6.1 
    vue: ^3.4.21 => 3.4.21
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@A-kirami Hi

in Dialogs it's better to use the vee-validate `Form` component

https://stackblitz.com/edit/vitejs-vite-4h9oqf

If you want to use `useForm` composable instead, you need to create a custom hard-coded form component based on your form fields

**Comment by A-kirami** [comment]
> @A-kirami Hi
> 
> in Dialogs it's better to use the vee-validate `Form` component
> 
> [stackblitz.com/edit/vitejs-vite-4h9oqf](https://stackblitz.com/edit/vitejs-vite-4h9oqf)

Thank you for the prompt response and solution! 

I would like to suggest adding documentation about this issue and its resolution to the project's documentation. It would be helpful for users who might encounter similar issues in the future.

**Comment by A-kirami** [comment]
> @A-kirami Hi
> 
> in Dialogs it's better to use the vee-validate `Form` component
> 
> [stackblitz.com/edit/vitejs-vite-4h9oqf](https://stackblitz.com/edit/vitejs-vite-4h9oqf)
> 
> If you want to use `useForm` composable instead, you need to create a custom hard-coded form component based on your form fields

Sorry, I'm not quite sure what a custom hard-coded form component is. Could you provide documentation or a demo? Thanks!

**Comment by sadeghbarati** [comment]
@A-kirami Sure will update stackblitz

**Comment by sadeghbarati** [comment]
@A-kirami https://stackblitz.com/edit/vitejs-vite-b87ysk

**Comment by A-kirami** [comment]
> @A-kirami [stackblitz.com/edit/vitejs-vite-b87ysk](https://stackblitz.com/edit/vitejs-vite-b87ysk)

Thank you for providing the demo! This resolves the issue for me.
