### ISSUE TITLE
[Bug]: Incorrect Hierarchy between Dialog Component and Sonner Component

### ISSUE THREAD

**Issue by A-kirami** [radix-vue/shadcn-vue#462]
### Reproduction

https://stackblitz.com/edit/vitejs-vite-lsu39t

### Describe the bug

When using toast in a dialog, the toast list does not automatically expand when the mouse hovers over the toast.

If the window is resized smaller, it can be observed that the mouse can click through the toast to the buttons in the dialog.

![toast](https://github.com/radix-vue/shadcn-vue/assets/66513481/4d0f63f3-5da3-4a59-95af-fdd6da828c93)

### System Info

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    radix-vue: ^1.6.2 => 1.6.2 
    vue: ^3.4.21 => 3.4.21
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/jmdup2

- https://www.radix-vue.com/components/dialog#disable-close-on-interaction-outside
- https://reka-ui.com/docs/components/dialog#content (interactOutside emit)

RadixVue (RekaUI) and also RadixUi `Dialog` and `DismissableLayer` have certain limitations when integrating with third-party modal libraries, you'll need to address these limitations yourself
