### ISSUE TITLE
[Feature]: Config in components.json for UI folder alias

### ISSUE THREAD

**Issue by jonathanwilke** [radix-vue/shadcn-vue#465]
### Describe the feature

Hey folks,

amazing work you are doing here! The "original" shadcn library has a config in the components.json for the UI folder alias, which would be really helpful to have here too.

https://ui.shadcn.com/docs/components-json#aliasesui

The changes for this could probably be copied easily from the original PR: 

https://github.com/shadcn-ui/ui/pull/2266/files

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
We already added alias features based on that shadcn-ui PR

can you test it in Stackblitz and confirm if its working or not? thanks

**Comment by jonathanwilke** [comment]
Also for the UI folder ? I can't find anything about that in the docs.

**Comment by jonathanwilke** [comment]
Oh damn, it's already working. Amazing! ✨

Maybe we need to just adjust the docs then?

**Comment by sadeghbarati** [comment]
Sure PR welcome

**Comment by jonathanwilke** [comment]
https://github.com/radix-vue/shadcn-vue/pull/466
