### ISSUE TITLE
[Feature]: Countdown Component

### ISSUE THREAD

**Issue by rainbowdog1** [radix-vue/shadcn-vue#473]
### Describe the feature

It would be cool to have a countdown component, that works by setting a datetime for when its due.
I can see myself using it when I am building a site and don't want to leave it empty, or when its under maintenance.

Something like this (without the background etc.) :
![image](https://github.com/radix-vue/shadcn-vue/assets/63544394/594824cc-ffa1-4f5e-83d1-548fcbc5dcba)

### Additional information

- [ ] I have already implemented and/or tested this feature.
- [ ] I intend to submit a PR for this feature.

**Comment by sadeghbarati** [comment]
> This project's goal is to remain aligned with [shadcn/ui](https://github.com/shadcn-ui/ui). If the feature you are requesting is not in the original shadcn/ui, it will not be considered here.


Will be opened if we spot it in main shadcn-ui


You can get ideas from these project to build your own countdown in Vue

- https://github.com/fengyuanchen/vue-countdown
- https://github.com/coskuncay/vue3-flip-countdown
