### ISSUE TITLE
[Bug]: Theme not loading in Nuxt3

### ISSUE THREAD

**Issue by ghost** [radix-vue/shadcn-vue#480]
### Reproduction

In tailwinds.css it shows an error on @tailwind base; as "Unknown at rule tailwind.css 

### Describe the bug

Following the install instructions on the website, the theme css does not load within my Nuxt 3 app.

Am using node v20.10.0

### System Info

```bash
In tailwinds.css file, it shows an error on @tailwind base; as "Unknown at rule tailwind.css 

base, components and utilities are viewed as UnknownAtRules

This may be a Nuxt 3 specific issue, but having followed install to the letter, the above 3 are not loading.
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Working here can you send repro?

https://stackblitz.com/edit/github-zkz4pv

**Comment by sadeghbarati** [comment]
Will reopen after reproduction 🙏
