### ISSUE TITLE
[Bug]: Calendar doesn't style properly in fresh install

### ISSUE THREAD

**Issue by Jeroenvb3** [radix-vue/shadcn-vue#485]
### Reproduction

I tried (stackblitz.com couldn't execute the init command)

### Describe the bug

After doing a complete fresh install of shadcn-vue with Vite (https://www.shadcn-vue.com/docs/installation/vite.html) with all the default recommended settings. I started using the example Calendar component code, but it doesn't show it properly styled.
![image](https://github.com/radix-vue/shadcn-vue/assets/10132938/f31d015e-21e2-4828-9998-5df92579b396)

There are no errors in the console or in the network tab.

The code is directly the example code of the first item of the Calendar component (https://www.shadcn-vue.com/docs/components/calendar.html).

```
<script setup lang="ts">
import { type Ref, ref } from 'vue'
import { type DateValue, getLocalTimeZone, today } from '@internationalized/date'
import { Calendar } from '@/components/ui/calendar'

const value = ref(today(getLocalTimeZone())) as Ref<DateValue>
</script>

<template>
  <Calendar v-model="value" :weekday-format="'short'" class="rounded-md border" />
</template>
```

The same issue appears for the Command component code:
![image](https://github.com/radix-vue/shadcn-vue/assets/10132938/115247b1-42b3-403b-bd63-ff35bf1617f0)

### System Info

```bash
Binaries:
    Node: 18.19.1 - /run/current-system/sw/bin/node
    npm: 10.2.4 - /run/current-system/sw/bin/npm
npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    radix-vue: ^1.7.0 => 1.7.0 
    vue: ^3.4.21 => 3.4.21
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Download this Stackblitz which configured `TailwindCSS` properly

https://stackblitz.com/edit/vitejs-vite-gi6ym2
