### ISSUE TITLE
[Bug]: Tabs set orientation="vertical" not working

### ISSUE THREAD

**Issue by qianmoQ** [radix-vue/shadcn-vue#492]
### Reproduction

None

### Describe the bug

<img width="1484" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/20521442/d355e877-ac7f-49ac-b6ca-0bd6938ee56c">
Code

```vue
<script setup lang="ts">
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
</script>

<template>
  <Tabs default-value="account" orientation="vertical">
    <TabsList >
      <TabsTrigger value="account"> Account </TabsTrigger>
      <TabsTrigger value="password"> Password </TabsTrigger>
    </TabsList>
  </Tabs>
</template>

```

### System Info

```bash
Microsoft Edge
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by chachew** [comment]
So this doesn't even seem to work with Radix-vue, which is what shadcn-vue is using under the hood.

**Comment by selemondev** [comment]
> So this doesn't even seem to work with Radix-vue, which is what shadcn-vue is using under the hood.

I have gone 2 steps behind and tested Radix UI and Shadcn UI as well. In both libraries, the `orientation='vertical'` prop doesn't work. You can check out the comment [here](https://github.com/radix-ui/primitives/issues/2837) .

**Comment by sadeghbarati** [comment]
@zernonia Hey please transfer this issue to `radix-vue` then

**Comment by zernonia** [comment]
@sadeghbarati  @qianmoQ  as per the comment here https://github.com/radix-ui/primitives/issues/2837#issuecomment-2054088663, you need to style your own base on the `data-attributes`. This props only handles the keyboard behavior. So it's not relevant to `radix-vue`. You may check the prop description for `orientation` [here](https://www.radix-vue.com/components/tabs.html)


We can extend the styling and cater for the orientation in `shadcn-vue` 😁

**Comment by qianmoQ** [comment]
> @sadeghbarati @qianmoQ as per the comment here [radix-ui/primitives#2837 (comment)](https://github.com/radix-ui/primitives/issues/2837#issuecomment-2054088663), you need to style your own base on the `data-attributes`. This props only handles the keyboard behavior. So it's not relevant to `radix-vue`. You may check the prop description for `orientation` [here](https://www.radix-vue.com/components/tabs.html)
> 
> We can extend the styling and cater for the orientation in `shadcn-vue` 😁

![image](https://github.com/radix-vue/shadcn-vue/assets/20521442/76f86ba1-53e4-47eb-88bb-cd3848dd60b0)
https://www.radix-vue.com/components/tabs#root
There is a problem with the documentation. The documentation describes the layout of tabs.

**Comment by dnefi** [comment]
Is there any update? It still doesn't work.

**Comment by qianmoQ** [comment]
> Is there any update? It still doesn't work.

Please see https://github.com/devlive-community/shadcn-ui-vue-admin/pull/31
it like

![image](https://github.com/user-attachments/assets/699c0b59-d4f4-4747-963d-ca8b1ea484e0)
![image](https://github.com/user-attachments/assets/05ee9421-7486-4101-9e9f-4a8b8494ca17)

**Comment by sadeghbarati** [comment]
> shadcn-ui 
I think `orientation` prop is mainly used to manage things like [keyboard navigations](https://www.radix-ui.com/primitives/docs/components/tabs#keyboard-interactions).


> shadcn-svelte 
The orientation is for accessibility purposes

Style it however you want
