### ISSUE TITLE
[Bug]: Cannot install drawer when not using typescript

### ISSUE THREAD

**Issue by Gattermeier** [radix-vue/shadcn-vue#494]
### Reproduction

no link because this is happening during installing via cli

### Describe the bug

run `npx shadcn-vue@latest add drawer`

getting unexpected error:
`Installing drawer...[error] ENOTDIR: not a directory, stat '[PATH]/node_modules/vaul-vue/dist/index.d.ts/tsconfig.json'`

### System Info

```bash
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 123.0.6312.124
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    radix-vue: ^1.6.2 => 1.6.2 
    vue: ^3.4.21 => 3.4.21
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Let's track it here please https://github.com/radix-vue/shadcn-vue/issues/430
