### ISSUE TITLE
[Feature]: is there any chance that can shadcn works with nx monorepo and Nuxt 3 as library for multi projects

### ISSUE THREAD

**Issue by ielb** [radix-vue/shadcn-vue#495]
### Describe the feature

is there any chance that can shadcn works with nx monorepo and Nuxt 3 as library for multi projects

### Additional information

- [ ] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by Matheun** [comment]
Have a look at the following:

https://github.com/radix-vue/shadcn-vue-nuxt-layer

this should get you started, i got a working nuxt layer monorepo working with pnpm, so with nx shouldnt be that different

**Comment by sadeghbarati** [comment]
Related issue about monorepo https://github.com/radix-vue/shadcn-vue/issues/210#issuecomment-1859259820
