### ISSUE TITLE
vaul vue Drawe, datepicker in popover or datepicker in another dialog inside Drawer

### ISSUE THREAD

**Issue by eugenewere** [radix-vue/shadcn-vue#498]
### Reproduction

 0.8.7 

### Describe the bug

[Bug]: vaul vue drawer cant work with  datepicker on popover azin is not clickable and also datepicker in dialog it auto closes drawer on click outside

### System Info

```bash
System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 887.51 MB / 11.57 GB
    Container: Yes
    Shell: 3.7.0 - /bin/fish
  Binaries:
    Node: 21.6.2 - /usr/bin/node
    pnpm: 8.15.2 - /usr/bin/pnpm
  npmPackages:
    @vueuse/core: ^10.7.2 => 10.7.2 
    nuxt: ^3.9.3 => 3.9.3 
    radix-vue: ^1.5.1 => 1.5.1 
    shadcn-nuxt: ^0.8.7 => 0.8.7 
    vue: ^3.3.12 => 3.4.15 
  operamini
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Duplicated of https://github.com/radix-vue/vaul-vue/issues/37

**Comment by sadeghbarati** [comment]
Let's track it in upstream issue
