### ISSUE TITLE
[Bug]: Datepicker month selector is broken in some of the demos

### ISSUE THREAD

**Issue by JustinBordage** [radix-vue/shadcn-vue#500]
### Reproduction

N/A, read the description

### Describe the bug

Step 1) Navigate to the demo website: "https://www.shadcn-vue.com/docs/components/date-picker.html"

Part 1 - Date range picker
2) Go to the "Date Range Picker" section
3) Observe that the next month button works, but the previous month button does not.

Part 2 - Independent month date picker
2) Go to the "Date Range Picker with Independent Months" section
3) Observe that the date picker on the right side, both of the "month buttons" navigate to the next month (The icon reflects this as well)

Side note: I don't have it installed in any of my projects **_yet_**, I simply noticed this from the demo website, which I speculated was running the latest code from the repo. I tested this 5 minutes ago from the time of writing this bug report, so the repro steps/observations mentioned above are not stale.

#### --- Edit ---
I played around with the code a bit the issue with the "Date Range Picker with Independent Months" variant seems to be a relatively simple fix of just altering the code snippet from the demo (at line 222 for the event handler & line 224 for the icon).

However, the issue with the "Date Range Picker" variant appears to be deeper. So far I haven't been able to find the handler which manages that logic which leads me to suspect that, that issue lies somewhere within the Radix-Vue dependency.

#### --- Edit 2 ---
Just found the handler in radix-vue, changed the part in my node_modules that I suspected was causing the issue, did a temp-patch with "npx patch-package", and tested it again, and it worked. Can't really describe where it is since the modification I made was in transpiled code, but I can at least confirm that the issue lies with the `radix-vue` dependency.

#### --- Edit 3 ---
Found the broken code in the radix-vue repo: 
https://github.com/radix-vue/radix-vue/blob/a605a6fe1552341479e02233dcba28095bbf2a6b/packages/radix-vue/src/Calendar/useCalendar.ts#L138

The `nextPage` function has `grid.value = newGrid` (Line 149) while the `prevPage` function does not. The patch I did in "Edit 2" would have been the equivalent of adding `grid.value = newGrid` to `prevPage` function in the same relative position within that function.

### System Info

```bash
Browser:
  - Chrome v123.0.6312.106
  - Chrome v124.0.6367.61
OS:
  - Windows 10
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by Aniruddha775** [comment]
I am willing to submit a PR to fix this issue

**Comment by sadeghbarati** [comment]
~~@Aniruddha775, sure, go ahead 👍~~ Thanks for your interest btw, but

I spoke with @epr3 he will push a fix in `radix-vue` 💯

**Comment by JustinBordage** [comment]
Just make sure to fix the "Independent month date picker" as well, since that issue was independent of the radix-vue bug.

**Comment by epr3** [comment]
@JustinBordage the issue with the second month having 2 next buttons was fixed in this PR: https://github.com/radix-vue/shadcn-vue/pull/501

**Comment by JustinBordage** [comment]
@epr3 Oh I didn't see that it had been split into a different issue, my bad.

**Comment by epr3** [comment]
@JustinBordage NP
