### ISSUE TITLE
[Bug]: Daterange picker breaks if the start and end dates are undefined on initialization

### ISSUE THREAD

**Issue by kilobyte2007** [radix-vue/shadcn-vue#504]
### Reproduction

https://stackblitz.com/edit/qxmgvy?file=src%2FApp.vue

### Describe the bug

Go to the stackblitz example and try selecting a range. It works the first time but if you want to then select a different range, the picker breaks and there are errors in the console.

This seems to work fine in radix-vue - here's a reproduction in radix - https://stackblitz.com/edit/t2w8kc?file=src%2FApp.vue

### System Info

```bash
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 108.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - ~/.npm-packages/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.3.1 - ~/.npm-packages/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 17.0
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    radix-vue: ^1.7.0 => 1.7.0 
    vue: ^3.4.23 => 3.4.23
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Works fine if you identify the Calendar System with `placeholder` prop

https://stackblitz.com/edit/qxmgvy-qrztqu

cc @epr3 🙏

**Comment by kilobyte2007** [comment]
Hey @sadeghbarati, thanks a lot! That actually helps. But I think it's still a bug. For example it works fine for the simple calendar.
