### ISSUE TITLE
[Bug]: shadcn-vue  Depends on vulnerable versions of lodash.template

### ISSUE THREAD

**Issue by annettedorothea** [radix-vue/shadcn-vue#508]
### Reproduction

npm audit

### Describe the bug

run 
`npm audit`
and you get result:
`# npm audit report

lodash.template  *
Severity: high
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
No fix available
node_modules/lodash.template
  shadcn-vue  *
  Depends on vulnerable versions of lodash.template
  node_modules/shadcn-vue

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.`

Could you please update lodash?

### System Info

```bash
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 70.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
  Browsers:
    Chrome: 124.0.6367.61
    Safari: 17.4.1
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    radix-vue: ^1.7.1 => 1.7.1 
    shadcn-vue: ^0.10.3 => 0.10.3 
    vue: ^3.4.23 => 3.4.23
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
Thanks for pointing that out @annettedorothea ! Realized that we didnt enable Depandabot in this repo. After enabling it we see that indeed there's vulnerability https://github.com/radix-vue/shadcn-vue/security/dependabot/19

**Comment by jornhd** [comment]
Please prioritize this issue!
