### ISSUE TITLE
[Feature]: Add tailwind `prefix` option to components.json

### ISSUE THREAD

**Issue by sadeghbarati** [radix-vue/shadcn-vue#509]
### Describe the feature

Current CLI doesn't support prefix option

Related [PR](https://github.com/radix-vue/shadcn-vue/pull/324) and [Discussion](https://github.com/radix-vue/shadcn-vue/discussions/444)

We welcome any help 💚 

This link might be helpful before prefix support https://github.vue.tailwind-prefix.cbass.dev/ thanks to Tobias Schenk for sharing

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Released on [v0.11.0](https://github.com/unovue/shadcn-vue/releases/tag/v0.11.0)
