### ISSUE TITLE
[Feature]: Form Component

### ISSUE THREAD

**Issue by ahmedmayara** [radix-vue/shadcn-vue#51]
### Describe the feature

Add the `Form` component like shadcn/ui

Link : https://ui.shadcn.com/docs/components/form

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by orenmizr** [comment]
isn't vee validate the closest vue's vesion of  react-hook-form  :)  might cut the development time.

**Comment by zernonia** [comment]
Any win with this @ahmedmayara ? Yup @orenmizr .. I suggested Veelidate previously as well, as it allows custom validation using `zod` and etc too if needed
