### ISSUE TITLE
[Bug]: .astro files is not in tailwind config (Selected Astro in installation)

### ISSUE THREAD

**Issue by AmrTamer23** [radix-vue/shadcn-vue#517]
### Reproduction

none

### Describe the bug

After all the installing steps in Astro, The project becomes a mess, found out that the tailwind config that installation added is not including `.astro` in content.

### System Info

```bash
Need to install the following packages:
envinfo@7.12.0
Ok to proceed? (y) y

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 1.69 GB / 7.66 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.3/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v21.7.3/bin/npm
    bun: 1.1.5 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 124.1.65.114
    Chrome: 124.0.6367.78
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0
    radix-vue: ^1.7.2 => 1.7.2
    vue: ^3.4.23 => 3.4.23
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
@AmrTamer23  can you share the `tailwind.config.js` after the installations?

By right it should have `.astro` ext being included in content

```
 content: [
      './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
    ]
```

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/github-b7mtnz

Tested Astro, it's fine if you follow `shadcn-vue` Astro installation steps respectively

**Comment by AmrTamer23** [comment]
I apologize for not checking in earlier. I installed it using Astro installation once more, and it worked. It's possible that I missed the option the first time, or it was fixed before I opened the issue, but either way, fantastic work!
