### ISSUE TITLE
[Bug]: `Input` value not showing at the start, then it can not be edited

### ISSUE THREAD

**Issue by Grolicek** [radix-vue/shadcn-vue#518]
### Reproduction

[CodeSandbox](https://codesandbox.io/p/devbox/shadcn-vue-inputdemo-forked-zmld6p?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvhsnjcc0008356eq88alebh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvhsnjcc0003356eydoh9ryr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvhsnjcc0005356et0c2p3s7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvhsnjcc0007356ejlnx1k5k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvhsnjcc0003356eydoh9ryr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvhsnjcc0002356ea3ay8snj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A42%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A42%257D%255D%257D%255D%252C%2522id%2522%253A%2522clvhsnjcc0003356eydoh9ryr%2522%252C%2522activeTabId%2522%253A%2522clvhsnjcc0002356ea3ay8snj%2522%257D%252C%2522clvhsnjcc0007356ejlnx1k5k%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvhsnjcc0006356egff7isa4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvhsnjcc0007356ejlnx1k5k%2522%252C%2522activeTabId%2522%253A%2522clvhsnjcc0006356egff7isa4%2522%257D%252C%2522clvhsnjcc0005356et0c2p3s7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvhsnjcc0004356e7rt6forh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clvhsnjcc0005356et0c2p3s7%2522%252C%2522activeTabId%2522%253A%2522clvhsnjcc0004356e7rt6forh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Describe the bug

When using `Input` component and setting its value I would expect it work as the other shadcn/ui (here is [link](https://ui.shadcn.com/docs/components/dialog) for expected result). A.k.a. its value would be set at the beginning and it can be edited afterwards by the user. But this is not the current behaviour. Instead at the beginning empty input is shown to the user and when user tries to edit the `Input` value it instantly changes to value set in code and sticks to that, therefore user can't change it.

### System Info

```bash
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 2.18 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
Binaries:
    Node: 18.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.6.0 - /usr/local/bin/npm
npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    radix-vue: ^1.7.2 => 1.7.2 
    shadcn-vue: latest => 0.10.4 
    vue: latest => 3.4.25
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by subordon** [comment]
Data binding should using `v-model` or `modelValue`

**Comment by zernonia** [comment]
You should use `defaultValue` for the inital default value @Grolicek .

```
  <Input type="email" placeholder="Email" default-value="mail@example.com" />
```
