### ISSUE TITLE
[Bug]: Loss of values already inputed in the internal form of <Collapsible> component when toggle hidden/display

### ISSUE THREAD

**Issue by trojanyao** [radix-vue/shadcn-vue#522]
### Reproduction

https://stackblitz.com/edit/ahqsji

### Describe the bug

Reproduce steps:

1. Type something in "Username" field.
2. Click "Toggle" button to collapse the <Collapsible> component.
3. Then click "Toggle" button again to expand <Collapsible> component.
4. The value already inputed in "Username" field was lost, which is not as expected.

<img width="638" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/22811809/06c3ac37-87c5-4d33-a2a4-9065363c100f">

### System Info

```bash
  System:
    OS: macOS 10.15.7
    CPU: (20) x64 Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz
    Memory: 145.77 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.5 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 15.6.1
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
You need to add `keepValue` props for your `FormField` to make it not reset the values to undefined.
[read more](https://vee-validate.logaretm.com/v4/guide/components/nested-objects-and-arrays#paths-creation-and-destruction)

We can improve this in our `Form` docs in case anyone run into this issue 😁

**Comment by trojanyao** [comment]
Thanks. It solved the issue.
