### ISSUE TITLE
[Bug]: Long delay for datepicker opening when browser "device mode" is tablet/mobile

### ISSUE THREAD

**Issue by max-fletcher** [radix-vue/shadcn-vue#530]
### Reproduction

https://github.com/max-fletcher/nuxt_boilerplate

### Describe the bug

I am testing using my own boilerplate( https://github.com/max-fletcher/nuxt_boilerplate ) that uses Nuxt 3. Feel free to ask me for specifics if need be. I implemented a Datepicker component in the "/posts" page(near the bottom). I noticed that in desktop mode, its working fine, but a bit sluggish. But when I pressed the "toggle device toolbar" button on chrome devtools to get a mobile/tablet view, clicking on the "Datepicker" causes the datepicker box to pop up way too slow. I couldn't find a way to override/fix this behaviour.

### System Info

```bash
Framework - Nuxt 3
OS - Windows 10(64 bit)
Browser - Chrome Version 124.0.6367.119(64-bit)
NPM as package manager
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
https://stackblitz.com/github/max-fletcher/nuxt_boilerplate

Your reproduction is too complex also your layout is not good

![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/f37effed-f1f4-4ab5-89ba-2c275e31bc29)


Can you test shadcn-vue Date Picker in `Toggle device toolbar` it's working good
Disable `Nuxt Devtools` and test it again

**Comment by sadeghbarati** [comment]
Closing, for now, will open after a minimal repro so that we can reproduce the problem
Cause `shadcn-vue` examples work well on my `Mobile` and `Toggle device toolbar`

**Comment by zealouscreations** [comment]
Note to @sadeghbarati or whoever this may concern:

I've ran into this same issue and narrowed it down to this happening only when the devtools are open in the browser. So the DatePicker components are triggering way too many reactive loops. You can see this by going into the Vue Devtools panel and use the Timeline->Performance monitor to watch all the events that fire when you click on elements in the components.

This is very disappointing that there is so much overhead happening in the background. I really like the DateRangePicker component, but it's unusable in development when I need to have devtools open. And it also makes me wonder what it's doing to performance in production - even though it does react faster it might potentially not work well on smaller devices like mobile phones. I recommend the devs look into optimizing this (and potentially) other components.
