### ISSUE TITLE
[Bug]: Installation page on docs is showing 404 not found

### ISSUE THREAD

**Issue by brenodanyel** [radix-vue/shadcn-vue#532]
### Reproduction

Open the docs > click "Installation" in the left sidebar

### Describe the bug

![image](https://github.com/radix-vue/shadcn-vue/assets/89032856/7671ef4b-004a-4280-a605-e273237e9bd3)

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 1.19 GB / 15.39 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
Not reproducible @brenodanyel . Can you provide more context, or perhaps video?

**Comment by sadeghbarati** [comment]
Can't repro even though I have bad net
