### ISSUE TITLE
ques: Are there any plans to add it to Nuxt Modules?

### ISSUE THREAD

**Issue by shinGangan** [radix-vue/shadcn-vue#535]
### Context

Hi maintainer team, thank you for creating a very nice library.

Are there any plans to add `shandcn-nuxt` module as well?
If you plan to add it, I will create a PR (I want you to focus on developing Radix Vue, Shadcn-vue, etc.)

I am asking this question considering that there is a roadmap such as "We plan to add the necessary features after development is completed."

### Note

radix-vue has already been added.

https://nuxt.com/modules/radix-vue

**Comment by shinGangan** [comment]
Hi @zernonia , I would be happy if you could reply when you have a time. 🙏

**Comment by sadeghbarati** [comment]
I don't fully understand what you're looking for, but we have `shadcn-nuxt` module, which automatically imports shadcn-vue components

**Comment by shinGangan** [comment]
Hi @sadeghbarati , I didn't explain enough, sorry...

<br />

Nuxt has an excellent CLI called Nuxt CLI (called Nuxi).
By using the Nuxi command, you can add modules as follows. Below is an example of adding Radix-vue Nuxt module.

```sh
npx nuxi module add radix-vue
```

By using the Nuxi command, installation and addition to nuxt.config will be completed automatically. It is possible to significantly reduce the installation steps for users.

You can also search for modules. (Below is an example of adding Radix-vue Nuxt module).

```sh
% npx nuxi@latest module search radix-vue
✔ Found 1 Nuxt module matching radix-vue for Nuxt 3.0.0

- Name               radix-vue                             
- Homepage           https://www.radix-vue.com/
- Compatibility      nuxt: ^3.0.0
- Repository         https://github.com/radix-vue/radix-vue
- Description        Vue port of Radix UI Primitives. An open-source UI component library for building high-quality, accessible design systems and web apps.
- Package            radix-vue
→ Install            npx nuxi module add radix-vue
- Stars              2.6K
- Monthly downloads  181.7K
```

**Comment by shinGangan** [comment]
The current documentation causes the installation to fail and this PR is incomplete as is.

- radix-vue/shadcn-vue#493

This procedure will not work properly unless you add `shadcn-nuxt` to your Nuxt modules.

**Comment by sadeghbarati** [comment]
> This procedure will not work properly unless you add `shadcn-nuxt` to your Nuxt modules.

After running `npx nuxi@latest module add shadcn-nuxt`

![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/2aa0cf4f-4683-4b4f-9f0b-9ae0974ef6ca)

**Comment by shinGangan** [comment]
Ah, I mistakenly thought it couldn't be installed because it didn't come up in the search. Thank you for teaching me. 🙏

```sh
% npx nuxi@latest module search shadcn-nuxt
ℹ No Nuxt modules found matching query shadcn-nuxt for Nuxt 3.0.0 
```

Can I add module information to the [Nuxt Modules repo](https://github.com/nuxt/modules) so that it can be searched in the Nuxt CLI and Nuxt Modules page(https://nuxt.com/modules)?

**Comment by zernonia** [comment]
Yes you may create a ticket on Nuxt Modules for that @shinGangan  😁

I see the question has been resolved right? Can we close this then? 😁

**Comment by shinGangan** [comment]
@zernonia , @sadeghbarati 

> I see the question has been resolved right? Can we close this then? 😁

Yes, thank you very much for answering my question carefully.
Since the question has been resolved, there is no problem in closing this issue. 🙆
