### ISSUE TITLE
Feature(Docs): Add a SelectMenu for user's framework

### ISSUE THREAD

**Issue by MuhammadM1998** [radix-vue/shadcn-vue#538]
### Describe the feature

Adding a SelectMenu with the frameworks as options (Vue, Nuxt, Astro, ...) and adjusting the components code accordingly would simplify copying the code a lot. It can be added besides 'Components Path' and 'Utils Path' in the current code config side menu

Example for the Button component: 
- User selects 'Vue'. Will render the existing code
```vue
<script setup lang="ts">
import { Button } from '@/components/ui/button'
</script>

<template>
  <Button>Button</Button>
</template>
```

- User selected 'Nuxt'. Will remove the import as the component is auto imported
```vue
<template>
  <UiButton>Button</UiButton>
</template>
```

Maybe it's a nitpick because ultimately we have only two options. Vue in Vue, Laravel, Astro projects and Nuxt. But I created an issue as I might try to implement it If I had the time 😁

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by dogukanoksuz** [comment]
In NuxtJs we can already import without writing Ui in front of components.
![image](https://github.com/radix-vue/shadcn-vue/assets/32539161/ccd4ab2b-1ab3-4b38-9cd0-738f5f1f274e)

Are you sure you imported shadcn-nuxt plugin on `nuxt.config.ts` file?

```
{
 modules: ['shadcn-nuxt'],
 shadcn: {
    /**
     * Prefix for all the imported component
     */
    prefix: '',
    /**
     * Directory that the component lives in.
     * @default "./components/ui"
     */
    componentDir: './components/ui'
  },
}
```

**Comment by MuhammadM1998** [comment]
@dogukanoksuz I know about the prefix thanks but it's just an example about how the import can be removed in Nuxt not the component name

**Comment by dogukanoksuz** [comment]
> @dogukanoksuz I know about the prefix thanks but it's just an example about how the import can be removed in Nuxt not the component name

You dont need to copy imports when you install plugin. Just copy component code and it works.

**Comment by sadeghbarati** [comment]
@dogukanoksuz, let me clarify what @MuhammadM1998's goal is.

The current documentation uses imports in markdown, as shown in the image:

![image](https://github.com/radix-vue/shadcn-vue/assets/17789047/5df5af87-e354-4946-923e-e14f835f2b3c)

As the title suggests, it's a feature for users to select their framework of choice. For instance, if a user selects `Nuxt`, those imports should be removed from the markdown code

**Comment by sadeghbarati** [comment]
https://twitter.com/Ignace_Maes/status/1800464315604213964?s=19

Vue docs toggle CAPI & OAPI is idea to handle this 💯

**Comment by MuhammadM1998** [comment]
You're right I thought of it then saw shadcn-docs already handles `componentsPath` & `utlisPath` in in `ComponentPreview` component which is basically the same idea as this. What to do you think?

**Comment by sadeghbarati** [comment]
If the `ComponentPreview` way is simpler, then let's go with shadcn-docs way

**Comment by MuhammadM1998** [comment]
I wanted to start with cli's internal refactors first & loading components config by nuxt module but it seem they would need some time . I will give this a try asap!

**Comment by sadeghbarati** [comment]
> I wanted to start with cli's internal refactors first & loading components config by nuxt module but it seem they would need some time . I will give this a try asap!


@MuhammadM1998 

I'll take care of this then, if I could 

Can you share the shadcn-docs way? Thanks

**Comment by MuhammadM1998** [comment]
@sadeghbarati I still need to think about it. I'll ping you when I get to something

**Comment by zernonia** [comment]
@MuhammadM1998  I think this is abit extra tho.. User can simply remove tho import right? Maybe 1 or 2 second max per component copied?

**Comment by MuhammadM1998** [comment]
@zernonia less steps is always better imo 😁 It gets tedious as one component may have multiple `.vue` files. But it's up to you guys of course.

**Comment by sadeghbarati** [comment]
> I think this is abit extra tho..

Yeah, I'm thinking again this can cause confusion for new devs, 
Let's keep it as is 

@MuhammadM1998 Feel free to close the issue if you don't worked on it
