### ISSUE TITLE
[Feature]: Implementation of virtual scroll on listing components (combobox like)

### ISSUE THREAD

**Issue by dogukanoksuz** [radix-vue/shadcn-vue#539]
### Describe the feature

Combo-boxes with big data lists causes freezing on browser.  Is there manual support for virtual lists?

https://github.com/radix-vue/shadcn-vue/assets/32539161/d2478d0a-4b38-4fa8-a70c-0d41e2ffbf45

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Can you try new Listbox and see if it happens?

https://stackblitz.com/edit/5stbzq

**Comment by dogukanoksuz** [comment]
https://github.com/radix-vue/shadcn-vue/assets/32539161/eabf5187-177d-495d-b26f-10938c34ff99

It's still too slow with big lists. On naive-ui (https://www.naiveui.com/en-US/os-theme/components/select) it comes with virtual scrolling by default and handles it well. @sadeghbarati

**Comment by sadeghbarati** [comment]
@dogukanoksuz Can you fork and send me you Stackblitz link thanks

**Comment by sadeghbarati** [comment]
@dogukanoksuz Check it again https://stackblitz.com/edit/5stbzq

**Comment by dogukanoksuz** [comment]
Thanks I'll update my combobox and select components according to this example. Featuring this example on the website might be great idea.
