### ISSUE TITLE
[Bug]: Theme page is not functional 

### ISSUE THREAD

**Issue by fadamakis** [radix-vue/shadcn-vue#54]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.shadcn-vue.com/themes.html

### Steps to reproduce

1. Go to the themes page
2. Open the copy code modal

### Describe the bug

The modal opens with the following content and the code is missing:
Copy and paste the following code into your CSS file.

### Expected behavior

A code snippet should be visible
Refer to shadcn-ui https://ui.shadcn.com/themes

### Conext & Screenshots (if applicable)

![Screenshot 2023-09-16 at 11 08 44](https://github.com/radix-vue/shadcn-vue/assets/1003546/1d34f6c6-d1fe-4513-91dc-411f86716107)

**Comment by zernonia** [comment]
Fixed 😁

**Comment by fadamakis** [comment]
@zernonia Thanks! But only works on dark mode for me. Light mode has dark text on dark background.
![Screenshot 2023-09-18 at 15 37 30](https://github.com/radix-vue/shadcn-vue/assets/1003546/c3aa58be-2e4b-4a07-ac86-ddc3acd51db9)

**Comment by anonimusprogramus** [comment]
@fadamakis  code text color problem has been fixed [here](https://github.com/radix-vue/shadcn-vue/pull/125)
