### ISSUE TITLE
[Feature]: Add contribution guide

### ISSUE THREAD

**Issue by fadamakis** [radix-vue/shadcn-vue#55]
### Describe the feature

A contribution guide similar to the one in shadcn-ui would be helpful.
https://github.com/shadcn-ui/ui/blob/main/CONTRIBUTING.md

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks @fadamakis ! Added https://github.com/radix-vue/shadcn-vue/blob/dev/CONTRIBUTING.md
