### ISSUE TITLE
[Bug]: Pagination component directory not created in latest release

### ISSUE THREAD

**Issue by pdjsh** [radix-vue/shadcn-vue#563]
### Reproduction

I don't have the time to create this, close the issue if you think reproduction is necessary

### Describe the bug

I tried installing pagination component by using the @latest tag and it passes successfully but the pagination component is never added to my project.

I tried running this command on my Arch Linux desktop machine and on my MacOS machine, and it behaves the same way on both machines. The command passes successfully but the code is never added to the project.

Once I replace @latest with @0.10.4 the component is created successfully

### System Info

```bash
System:
    OS: Linux 6.8 Arch Linux
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 15.66 GB / 30.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.9.2 - ~/.local/share/pnpm/pnpm
  Browsers:
    Brave Browser: 124.1.65.130
    Chromium: 124.0.6367.201
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0
    nuxt: ^3.11.2 => 3.11.2
    radix-vue: ^1.7.2 => 1.7.2
    shadcn-nuxt: ^0.10.2 => 0.10.2
    vue: ^3.4.21 => 3.4.23
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
If you are in **Nuxt/JS** project this issue is related 

https://github.com/radix-vue/shadcn-vue/issues/291#issuecomment-1901788144
