### ISSUE TITLE
[Bug]: Updated date picker does not let user choose month and year

### ISSUE THREAD

**Issue by codebycab** [radix-vue/shadcn-vue#565]
### Reproduction

https://www.shadcn-vue.com/docs/components/date-picker.html

### Describe the bug

The updated Date Picker component does not let user change month and year quickly (the only way to change it is to use the arrows) making using this component for a birthday date picker not possible.
I assume this is a bug, not intended behavior.

### System Info

```bash
Bug present in demos in the shadcn-vue website
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
If you play with `radix-vue` Calendar component you will notice there are features to build your own style to select `Month` and `Year` 

Also, there is a demo in Calendar link which has the feature you want

https://www.shadcn-vue.com/docs/components/calendar.html#month-year-selects

**Comment by codebycab** [comment]
Right, so that's intended behavior then?
I'm asking this because the website uses the birthday use case as an example (last example in the docs page), with no customization.

**Comment by sadeghbarati** [comment]
> so that's intended behavior then

Yes, so you could build your own style for `month` and `year` selection

**Comment by codebycab** [comment]
Gotcha, thank you
