### ISSUE TITLE
[Docs]: the broken navigation links for the code examples under the "Form" tab

### ISSUE THREAD

**Issue by JiuRanYa** [radix-vue/shadcn-vue#566]
### Reproduction

https://www.shadcn-vue.com/examples/forms/appearance.html

### Describe the bug

I create a pr #553 few days before.

Is there anyone follow up this?

Just go https://www.shadcn-vue.com/examples/forms/appearance.html and click `view code`, also get the incorrect href.

### System Info

```bash
none
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
@JiuRanYa  can you attached a video showcasing the case above? We really can't figure out what's wrong and what is the fix is for, and cant' replicate the issue you are having.

**Comment by JiuRanYa** [comment]
@zernonia Thanks for your reply.

Except for the "Profile" tab, all code examples under the "Form" tab on the official website have incorrect navigation links pointing to a wrong `email` address.

All under the "Form" tab on the official website should navigate to the 'form' dirs.

**Comment by zernonia** [comment]
Again @JiuRanYa .. we understand but we can't reproduce the issue!! Can you please send a video to showcase please?

**Comment by JiuRanYa** [comment]
hah, here, I don't know if you can understand:)

https://github.com/radix-vue/shadcn-vue/assets/58846658/e362df15-18a6-4940-9e87-4e2faa9ec2bb

**Comment by zernonia** [comment]
Thanks for the video @JiuRanYa ! I finally understand the problem lol!!!

**Comment by JiuRanYa** [comment]
ohhhh，Maybe I'm not explaining this very well. Sorry about that！
