### ISSUE TITLE
[Feature]: Inertia Support

### ISSUE THREAD

**Issue by joshuadempsey** [radix-vue/shadcn-vue#57]
### Describe the feature

Is there any plans on the roadmap to support Laravel/Inertia + VueJS? I've seen lots of people waiting for this, and I'm sure support would massively push adoption 👍🏻 

Currently there's lots of TS errors unfortunately 👎🏻 

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by fusigabs** [comment]
+1

**Comment by zernonia** [comment]
Hey @joshuadempsey ! I've added a Laravel installation step [here](https://www.shadcn-vue.com/docs/installation/laravel.html). Could you help me verify if it works? And if not I would really appreciate your help in providing the correct setup step.

Also, when you mentioned TS errors, what was it ya? Could you provide more context? Maybe screenshot?

**Comment by drehimself** [comment]
@zernonia The `tailwind.config.js` file has to accommodate `.vue` and `.ts` files as well.

I added this line to the `content` array and it worked within Inertia/Vue 3 Typescript:

```
'./resources/js/**/*.{vue,js,ts,jsx,tsx}',
```

Really loving shadcn-vue, thanks for all your hard work 💪

**Comment by zernonia** [comment]
Thanks for verifying it @drehimself !! Really appreciate it! 🚀
I've updated the docs, and thus closing the issue as `complete` ya!

We can reopen this ticket if needed 😁


PS: Thanks for the kind words! ❤️
