### ISSUE TITLE
[Feature]: remove the need for multiple <script> tags from a single component.

### ISSUE THREAD

**Issue by RazorSiM** [radix-vue/shadcn-vue#572]
### Describe the feature

The `FormItem` component currently exports the `FORM_ITEM_INJECTION_KEY`. This adds the need of having a second `<script>` tag in the component that fights with some linting defaults from Eslint (specifically, nuxt and antfu eslint config packages).

Beside that, I think exporting from a ts module is cleaner solution than exporting from a vue component :smile:. 

The proposed solution is to have an `injectionKeys.ts` file in the `form` folder to export all the needed injection keys.

I already tested the code, everything is working as expected.

### Additional information

- [X] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
I agree with the suggestion @RazorSiM ! When we first introduced the `FormItem` we adapted the pattern similar to how `radix-vue` provide and inject the context. However for the case of `shadcn-vue`, where you own the component file, which might cause linting error.

Yup let's move those keys to it's appriopriate file 😁

**Comment by RazorSiM** [comment]
PR opened, feel free to review :)
