### ISSUE TITLE
[Bug]: HTML expects colspan instead of col-span

### ISSUE THREAD

**Issue by tribakzero** [radix-vue/shadcn-vue#579]
### Reproduction

Copy/Paste data-table.md example notice how the no-results text won't span the whole table width

### Describe the bug

Using the data-table template example shows "no results" message in a single column instead of a full row. This is due to the colspan HTML attribute been used here as col-span.

# Screenshots
![Screenshot 2024-05-27 at 6 34 32 p m](https://github.com/radix-vue/shadcn-vue/assets/6462719/6d5e75e2-b98f-44ff-be0b-2324fd7f607f)
![Screenshot 2024-05-27 at 6 34 16 p m](https://github.com/radix-vue/shadcn-vue/assets/6462719/47fc2cef-f173-4fe8-ad86-f2e44425242c)

### System Info

```bash
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M3
    Memory: 71.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  Browsers:
    Chrome: 125.0.6422.112
    Safari: 17.2
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0 
    radix-vue: ^1.7.4 => 1.8.0 
    vue: ^3.4.21 => 3.4.27
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by tribakzero** [comment]
Have the one-liner change, but can't push branches to the project.

**Comment by zernonia** [comment]
@tribakzero  you can fork the repo and push the changes to the forked repo, and create a merge request here

**Comment by zernonia** [comment]
Fixed in https://github.com/radix-vue/shadcn-vue/commit/f48d1d4f4c1e0dbe92fb0ba726aff628e94c7f61
