### ISSUE TITLE
[Bug]: when adding  stepper getting: Invalid configuration found in components.json

### ISSUE THREAD

**Issue by dimaaash** [radix-vue/shadcn-vue#580]
### Reproduction

Cloned, installed https://github.com/saymenghour/vue3-enterprise-boilerplate project. Tried to add to it the shadcn-ui stepper via npx shadcn-ui@latest add stepper

### Describe the bug

When trying to add a stepper to vue3 project ( which is under using shadcn )

```
npx shadcn-ui@latest add stepper
```
its telling me:

```
Invalid configuration found in /vue3-enterprise-boilerplate/components.json.
```

Contents of components.json

```
{
  "$schema": "https://shadcn-vue.com/schema.json",
  "style": "new-york",
  "typescript": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "src/assets/styles/main.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "framework": "vite",
  "aliases": {
    "components": "@/lib/shadcn",
    "utils": "@/lib/utils"
  }
}
```

Thank you!

### System Info

```bash
px envinfo --system --npmPackages vue,@vueuse/core,radix-vue,nuxt,shadcn-vue,shadcn-nuxt,unplugin-auto-import --binaries --browsers:

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 51.03 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
  Browsers:
    Chrome: 125.0.6422.112
    Safari: 16.5.2
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.10.0 
    radix-vue: ^1.7.4 => 1.8.2 
    vue: ^3.4.27 => 3.4.27
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Hey @dimaaash 

I see you using `shadcn-ui` CLI, not `shadcn-vue` CLI

and we still don't have stepper component yet

shadcn-ui is for React
shadcn-vue is for Vue

**Comment by dimaaash** [comment]
Thanks @sadeghbarati  

I was a little confused as to which library to use. 

> shadcn-ui is for React
shadcn-vue is for Vue

Thank you for clarification. 

Will try to mimic stepper with something custom.
