### ISSUE TITLE
[Bug]: Examples > forms 404 error

### ISSUE THREAD

**Issue by onurusluca** [radix-vue/shadcn-vue#583]
### Reproduction

https://www.shadcn-vue.com/examples/forms.html

### Describe the bug

Forms example gives 404 error
https://www.shadcn-vue.com/examples/forms.html

### System Info

```bash
No need. Not local.
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Related PR https://github.com/radix-vue/shadcn-vue/pull/553

**Comment by zernonia** [comment]
Fixed in https://github.com/radix-vue/shadcn-vue/commit/e54e06bb989bb2359e4ab2684926a1db52245718
