### ISSUE TITLE
[Bug]: Responsive Dialog removes scroll after resize

### ISSUE THREAD

**Issue by AlexXanderGrib** [radix-vue/shadcn-vue#584]
### Reproduction

https://www.shadcn-vue.com/docs/components/drawer.html

## Reproduction steps
1. Open https://www.shadcn-vue.com/docs/components/drawer.html
2. Scroll to Responsive Dialog
3. Open devtools, resize window to width 500px
4. Click "Edit profile"
5. Resize window to width 800px
6. Close dialog
7. Scroll is gone

## Simple fix
```javascript
watch(isOpen, open => {
  if (!open) {
    document.body.removeAttribute('style');
  }
});
```
## Related
radix-vue/vaul-vue#51

### System Info

```bash
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 3.71 GB / 15.41 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 20.5.1 - /usr/bin/node
    Yarn: 3.6.1 - /usr/bin/yarn
    npm: 10.2.5 - /usr/bin/npm
    pnpm: 8.15.1 - /usr/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.112
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
Issue should be fixed in https://github.com/radix-vue/vaul-vue/releases/tag/vaul-vue%400.2.0 😁
