### ISSUE TITLE
[Bug]: CustomEvent is not defined

### ISSUE THREAD

**Issue by EugeneTsydenov** [radix-vue/shadcn-vue#587]
### Reproduction

https://codesandbox.io/p/github/EugeneTsydenov/nuxt-messager/messager?file=%2FREADME.md&workspaceId=896e1493-a13c-4929-93d0-929dedaa586d

### Describe the bug

There is a problem in the components: ScrollArea and Checkbox when used together with nuxt. On pages where these components are used, the error 500 CustomEvent is not defined appears. I know that this is an ssr problem, but are there ways to solve this problem without using rendering on the client (I am not satisfied with this behavior)?

### System Info

```bash
system
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@EugeneTsydenov CodeSandbox link said `Unable to access this workspace`

Can you create a Stackblitz instead? and tell us what is your radix-vue version

Closing for now will reopen after reproduction link

**Comment by EugeneTsydenov** [comment]
@sadeghbarati 
Radix-vue version 1.8.0. I apologize sandbox does not open probably because I have a private repository

**Comment by sadeghbarati** [comment]
@EugeneTsydenov Can you try with the latest radix-vue?

1.8.3

**Comment by EugeneTsydenov** [comment]
@sadeghbarati Everything worked, thank you very much
