### ISSUE TITLE
[Feature]: jalali calander/date-picker

### ISSUE THREAD

**Issue by mehrabix** [radix-vue/shadcn-vue#588]
### Describe the feature

Hi, I need to use calander or date picker in a persian app which needs to be jalali calander but at this moment shadcn just supports gregorian.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
@mehrabix Hi 


Current Calendar or DatePickers are based on 

React Aria and Internationalized Date packages

It's has support for 13 Calendar System, including Jalali/Khorshidi 

Check radix-vue and @internationalized/date documentation 

https://www.radix-vue.com/components/calendar.html#calendar-with-locale-and-calendar-system-selection

https://react-spectrum.adobe.com/internationalized/date/index.html

**Comment by mehrabix** [comment]
Thanks @sadeghbarati it works for me.

**Comment by sadeghbarati** [comment]
Great, feel free to close the issue 🙌
