### ISSUE TITLE
[Feature]: add "blocks request" page

### ISSUE THREAD

**Issue by euotiniel** [radix-vue/shadcn-vue#591]
### Describe the feature

To suggest

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
We don't accept "blocks request" at the moment as the "blocks" will be references from `ui.shadcn`. Do feel free to add your suggestion [here](https://github.com/shadcn-ui/ui/discussions/new?category=blocks-request) 😁
