### ISSUE TITLE
[Feature](add block):  profile dashboard

### ISSUE THREAD

**Issue by euotiniel** [radix-vue/shadcn-vue#592]
### Describe the feature

An administrator profile for a dashboard

![320275561-0fd12027-f9c5-45cf-aa65-fc6e83f26108](https://github.com/radix-vue/shadcn-vue/assets/93485038/3c35c7b7-bd2c-492f-930b-2f89f984b4b2)

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Please create the suggestion here 😁
https://github.com/shadcn-ui/ui/discussions/new?category=blocks-request
