### ISSUE TITLE
DatePicker not getting min-value

### ISSUE THREAD

**Issue by IsaqjonovII** [radix-vue/shadcn-vue#604]
Hello, I wanted to give a calendar min value like this

```
<Calendar v-model="selectedDate" initial-focus :min-value="nextWeek" />
```

But it showing type error and not working.
`Type 'Date' is not assignable to type 'DateValue | undefined'.ts-plugin(2322)`

Here is my code: 

```
const sevenDaysFromNow = computed(() => {
  const date = new Date();
  return new Date(date.setDate(date.getDate() + 7));
});
```

How can I fix it?

**Comment by sadeghbarati** [comment]
Are you using @internationalized/date DatePicker or v-calendar DatePicker?

Can you share a demo or reproduction in Stackblitz or Codesandbox

Closing for now will reopen after repro
