### ISSUE TITLE
[Bug]: Javascript has empty props/emits

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#62]
Since `v0.1.6`, we've introduce [detype](https://github.com/cyco130/detype) to purge off all types related code in components.
However this leads to components having empty props/emits declarations.

Unfortuantely this would required a huge refactors on all the components.

**Comment by Dunqing** [comment]
I think it would be much easier if it was possible to transform types to `defineProps`/`defineEmit` parameters.

**Comment by zernonia** [comment]
Yeah that's the plan. I rmb seeing Vue source code to have this transform utils.

**Comment by Dunqing** [comment]
I'm looking at [vuejs/core](https://github.com/vuejs/core) to see if there's a way to accomplish this. So far, it seems to work. It's going to take some time.
