### ISSUE TITLE
[Feature]: Command component highlighted value on change callback

### ISSUE THREAD

**Issue by HuakunShen** [radix-vue/shadcn-vue#635]
### Describe the feature

It seems like the current command component doesn't support highlighted value on change callback. 

e.g. get highlighted item when pressing up and down arrow to switch between the items.

The react shadcn provides a `onValueChange` props callback, implemented with cmdk.

Shadcn-vue's underlying `ComboboxRoot` from radix-vue doesn't provide this option.

https://github.com/radix-vue/radix-vue/issues/744

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by yakir-reznik** [comment]
i'm not quite sure how to implement this feature but if you need a quick and easy solution i would suggest you wrap the <Command> component with your own <div ref="el"> and use a mutation observer to detect when the highlighted child changes.
Highlighted children have a "data-highlighted" attribute on them.

**Comment by HuakunShen** [comment]
My PR https://github.com/radix-vue/radix-vue/pull/1048 implemented this feature in radix-vue.
It's published in radix-vue v1.9.0. For now I replace shadcn's radix-vue dependency verison with v1.9.0.
Shadcn-vue just need to upgrade its default radix-vue version to v1.9.0
