### ISSUE TITLE
[Bug]: Missing `DrawerPortal`, `DrawerTrigger`, `DrawerClose` in auto-import components

### ISSUE THREAD

**Issue by brokuka** [radix-vue/shadcn-vue#653]
### Reproduction

https://github.com/radix-vue/shadcn-vue/tree/dev/apps/www/src/lib/registry/default/ui/drawer

### Describe the bug

Missing `Drawer` components: `DrawerClose` and `DrawerTrigger` as showing in [demo](https://www.shadcn-vue.com/docs/components/drawer#usage)

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 3.86 GB / 15.92 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE    
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD    
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD       
    pnpm: 8.14.3 - C:\Program Files\nodejs\pnpm.CMD     
  npmPackages:
    nuxt: ^3.12.3 => 3.12.3 
    radix-vue: latest => 1.9.0 
    shadcn-nuxt: latest => 0.10.4
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by brokuka** [comment]
The error was that the components were not imported automatically. Need to manually import.

**Comment by brokuka** [comment]
Here's what nuxt says about usage `npm packages components` ([link](https://nuxt.com/docs/guide/directory-structure/components#npm-packages)).

Example of usage:

```
// ~/modules/create-component.ts
import { addComponent, defineNuxtModule } from 'nuxt/kit'

export default defineNuxtModule({
  setup() {
    addComponent({
      export: 'DrawerPortal',
      name: 'UiDrawerPortal',
      filePath: 'vaul-vue',
    })

    addComponent({
      export: 'DrawerClose',
      name: 'UiDrawerClose',
      filePath: 'vaul-vue',
    })

    addComponent({
      export: 'DrawerTrigger',
      name: 'UiDrawerTrigger',
      filePath: 'vaul-vue',
    })
  },
})

```

**Comment by sadeghbarati** [comment]
Some of the components were directly exported from the main `vaul-vue` entry

https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/drawer/index.ts#L1

because there was no need to create another component around those components

---

To solve missing auto-import components you need to use `shadcn-nuxt` module to take care of this issue
or use the `manual module` way and add those components to auto-import scan with `addComponent` with `nuxt/kit`

**Comment by brokuka** [comment]
> shadcn-nuxt

`shadcn-nuxt` is installed but, and components path is default, but I still don't understand how to fix it
