### ISSUE TITLE
[Feature]: ScrollTop() method on scrollarea

### ISSUE THREAD

**Issue by iplanwebsites** [radix-vue/shadcn-vue#655]
### Describe the feature

It's useful to scroll a `ScrollArea` to the top when it's content change. There doesn't seem to be any `scrollTop` method and I didn't had any luck adding one since radix doesn't expose one neither. Maybe you managed to set it directly from the parent using nested `refs`?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
https://github.com/radix-vue/radix-vue/issues/1095
