### ISSUE TITLE
[Bug]: SelectTrigger Component Why can't nested components trigger click events

### ISSUE THREAD

**Issue by WJjack** [radix-vue/shadcn-vue#656]
### Reproduction

<SelcectTrigger><ChevronDown class="w-4 h-4 opacity-50" @click="click" /></SelectTrigger>

### Describe the bug

I want to extend the search function to the Select component, but the nested input field of the SelectTrigger component does not get focus

### System Info

```bash
shadcn-vue
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Can you send a Stackblitz? If you want to search why you don't use `Combobox` or `Listbox` 

Please read the `radix-vue` docs carefuly

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/5stbzq?file=package.json (Listbox and TagsInput with search)

https://www.radix-vue.com/components/tags-input.html#with-combobox (Combobox and TagsInput)

**Comment by WJjack** [comment]
thank you.

**Comment by Uhasith** [comment]
> https://stackblitz.com/edit/5stbzq?file=package.json (Listbox and TagsInput with search)
> 
> https://www.radix-vue.com/components/tags-input.html#with-combobox (Combobox and TagsInput)

Is this work inside Dialog Modals ? @sadeghbarati
