### ISSUE TITLE
[Bug]: PopoverClose as-child doesn't work

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#660]
### Reproduction

None

### Describe the bug

I'm trying to add a Popover on a button for a quick input, and I want a button which the user can click to do the update action and close the popover

I'm naively trying to add PopoverClose from radix-vue and

```
<PopoverClose as-child><Button @click="myAction">Save</Button></PopoverClose>
```

but this doesn't show the button

any idea?

Otherwise if I just add a regular button without PopoverClose, how can I control the fact that the popover closes as the user clicks?

### System Info

```bash
None
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@maelp Hi, please provide us with a repro 

Did you use `PopoverClose` inside the `Popover` component?

based on Provide/Inject functionality, `PopoverClose` will only works when it's inside `Popover`

**Comment by maelp** [comment]
Yes it was insideBasically how would you go about adding a Button inside a Popover which closes the Popover and also runs a custom action?On 16 Jul 2024, at 17:45, Sadegh Barati ***@***.***> wrote:﻿
@maelp Hi, please provide us with a repro
Did you use PopoverClose inside the Popover component?
based on Provide/Inject functionality, PopoverClose will only works when it's inside Popover

**Comment by sadeghbarati** [comment]
@maelp 

https://stackblitz.com/edit/f6j6mu?file=src%2FApp.vue

It's working, chain functions working even with `asChild` prop

**Comment by maelp** [comment]
Weird I had literally the same code as you

**Comment by sadeghbarati** [comment]
You should check the `Button.vue` source, maybe you need to use `inheritAttrs: false`, and add `$attrs` to the button element,

Or perhaps it would be nice if you share your demo and the source

**Comment by maelp** [comment]
Hey @sadeghbarati thanks! This is my Button code, how would you change it?

```
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Primitive, type PrimitiveProps } from "radix-vue";
import { type ButtonVariants, buttonVariants } from ".";
import { GIcon, cn } from "@ui";

// We added "icon" for convenience
export interface Props extends PrimitiveProps {
  variant?: ButtonVariants["variant"];
  size?: ButtonVariants["size"];
  icon?: string;
  class?: HTMLAttributes["class"];
}

const props = withDefaults(defineProps<Props>(), {
  as: "button",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="
      cn(
        buttonVariants({ variant, size }),
        'flex',
        'gap-1',
        'items-center',
        props.class
      )
    "
  >
    <GIcon :icon="icon" v-if="icon !== undefined"></GIcon>
    <slot />
  </Primitive>
</template>
```

**Comment by maelp** [comment]
Seems similar to https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/button/Button.vue

**Comment by sadeghbarati** [comment]
@maelp I thought you changed `Button.vue` source 🤔 

`$attrs` will automatically attached to the first child of the template so there is no need to do `inheritAttrs: false` and set `$attrs`  with v-bind

**Comment by sadeghbarati** [comment]
In that case, can you share your source code or invite me to your private repo for test?

**Comment by maelp** [comment]
@sadeghbarati I shared it just in the message above

**Comment by sadeghbarati** [comment]
That is `shadcn-vue` button source link.

Can you share (Your) reproduction?

**Comment by maelp** [comment]
Yes I meant my Button code is here, haven't yet done the reproduction with my code as it requires a few libs, but if I manage to do it I'll share

```
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Primitive, type PrimitiveProps } from "radix-vue";
import { type ButtonVariants, buttonVariants } from ".";
import { GIcon, cn } from "@ui";

// We added "icon" for convenience
export interface Props extends PrimitiveProps {
  variant?: ButtonVariants["variant"];
  size?: ButtonVariants["size"];
  icon?: string;
  class?: HTMLAttributes["class"];
}

const props = withDefaults(defineProps<Props>(), {
  as: "button",
});
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="
      cn(
        buttonVariants({ variant, size }),
        'flex',
        'gap-1',
        'items-center',
        props.class
      )
    "
  >
    <GIcon :icon="icon" v-if="icon !== undefined"></GIcon>
    <slot />
  </Primitive>
</template>
```

**Comment by maelp** [comment]
Also I checked and my Popover, PopoverContent etc implementations are exactly the ones from latest shadcn-vue

**Comment by maelp** [comment]
Hmmmm I updated my dependencies and this seems to have solved the bug, not sure why

**Comment by sadeghbarati** [comment]
Updated the Stackblitz with your `Button.vue` source it still working 

Added a `<div>` before the slot with `v-if` condition

https://stackblitz.com/edit/f6j6mu

---

Possible ways to fix this issue

- update deps
- remove node_modules
- remove packageManager cache
