### ISSUE TITLE
[Bug]: The requested module '/_nuxt/components/ui/navigation-menu/index.js' does not provide an export named 'NavigationMenuIndicator'

### ISSUE THREAD

**Issue by ricky11** [radix-vue/shadcn-vue#661]
### Reproduction

unable to do so.

### Describe the bug

When following the Nuxt installation steps and installing the navigation menu here: 
https://www.shadcn-vue.com/docs/components/navigation-menu.html

when i run npm run serve, the following is shown in the browser.

The requested module '/_nuxt/components/ui/navigation-menu/index.js' does not provide an export named 'NavigationMenuIndicator'

### System Info

```bash
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 2.60 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 107.1.45.131
    Chrome: 126.0.6478.127
    Edge: 126.0.2592.102
    Safari: 16.1
  npmPackages:
    nuxt: ^3.12.3 => 3.12.3 
    radix-vue: ^1.9.1 => 1.9.1 
    shadcn-nuxt: ^0.10.4 => 0.10.4 
    vue: latest => 3.4.31
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@ricky11 Are you using `shadcn-nuxt` (Nuxt Module) or not?

Can you provide a minimal reproduction?

https://nuxt.new/s/v3
