### ISSUE TITLE
Toast Error in VILT Stack  Navigating to a page from other page while the toast was still open [Bug]: 

### ISSUE THREAD

**Issue by nehry-micto** [radix-vue/shadcn-vue#666]
### Reproduction

n/a

### Describe the bug

Calling a toast then navigating to other page while the toast was still open giving an error.
I think it was because the toast was still there but the parent component was unmounted?
I'm using Laravel, Inertia, Vue and TailwindCSS. Is there a work around for this?

This is the AuthenticationLayout.vue where I added toast component
![Screenshot 2024-07-18 090535](https://github.com/user-attachments/assets/d2ceecb1-a08e-4128-8716-3b2163eed1a1)
The error I encountered while the toast was open, then navigating to other page.
![Screenshot 2024-07-18 085923](https://github.com/user-attachments/assets/55fc5c85-ee9b-4dc7-ba2b-1fbda3504b35)
![Screenshot 2024-07-18 090020](https://github.com/user-attachments/assets/712e6078-a448-480b-9ffd-ad4c8a726550)

### System Info

```bash
Brave Browser
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by seergiue** [comment]
Same issue here

**Comment by sadeghbarati** [comment]
Can you guys provide a minimal reproduction with Stackblitz?

**Comment by nehry-micto** [comment]
I have created a temporary solution, I added an event handler from inertia https://inertiajs.com/events, it listen if you navigated to other page, then I added a function that calling the dispatch to remove the toast.

use-toast.js
```javascript
function removeAllToast() {
    dispatch({ type: actionTypes.REMOVE_TOAST });
}
export { toast, useToast, removeAllToast };
```

AuthLayout.vue
```javascript
let removeStartEventListener = router.on("start", (event) => {
    removeAllToast();
});

onUnmounted(() => {
    removeStartEventListener();
});
```

**Comment by augmnt** [comment]
@nehry-micto you can also do the following and use the `useToast().dismiss()` so you don't have to create an additoinal function.

```js
let removeStartEventListener = router.on("start", (event) => {
  useToast().dismiss()
});

onUnmounted(() => {
    removeStartEventListener();
});
```

**Comment by sadeghbarati** [comment]
`<Toaster>` component must be used in app-wide components like **layouts**, it should not be placed in pages/routes components

**Comment by stefanocurnis** [comment]
> `<Toaster>` component must be used in app-wide components like **layouts**, it should not be placed in pages/routes components

I have it in my Layout, but with Inertia layouts are unmounted and remounted everytime you click.
