### ISSUE TITLE
[Feature]: providing changelog

### ISSUE THREAD

**Issue by Dunqing** [radix-vue/shadcn-vue#67]
### Describe the feature

I think providing a changelog gives a better idea of the differences between versions

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks for the suggestion @Dunqing ! I've adde [changelogithub](https://github.com/antfu/changelogithub)  😁
