### ISSUE TITLE
[Bug]: Example Select Bug

### ISSUE THREAD

**Issue by ProgrammerZ** [radix-vue/shadcn-vue#673]
### Reproduction

https://www.shadcn-vue.com/examples/cards

### Describe the bug

There is a Select bug on the Cards Example page
![bug](https://github.com/user-attachments/assets/9579613c-3f59-436f-bdf2-9d839894f445)

### System Info

```bash
NA
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
`shadcn-ui` is using `tailwind-merge` **v1** but we are using **v2**


```ts
// v2
console.log(twMerge('flex', 'line-clamp-1')) // line-clamp-1
```



[JSPM Playground](https://jspm.org/sandbox#H4sIAAAAAAAAA42TXW/aMBSG7/srTr0LWgknUO1iYwkq61DVbpmqMjbt0o0PxNQfkW1Ioep/n3FIJSpV2kXk2Md+z+PX52Sn3JR+WyNUXsnxSdYNyPj4BCBT6BmUFbMOfU7WfkE/kRjwwkscz3UceZa289cjminMyUZgUxvrCZRGe9RBohHcVznHjSiRxkkfhBZeMEldySTmw5AgS1uC7MHwbVQ9pTQMALezuwKuUaNl3li4UXt9KFgdo1MuPMzvf4zCfXztRmm67LYmK1erRJj0w/zi9+rv9dfHb8XAbme729l8WH2f6mJ3pe920839bj7ws8fPw+LnzW7wq5hMrhYWm+VqMgk5KN3jQOZKK2oPe+9yIiKFYnX05jmiHBYdGR0WwpJnQjZCc6rQLjFEyCsme+XTtRodb7y8SD4mg5QL59OHteYSqVq5JHwkKr+ctF+WtlR7iINnMJ1BYfhaIswqoRy0VBBYHdRGbhdCSne4VXcp5ra6BGfL/D0+dFRFVer2qpfDZDjoCN/Ewrnw/NY4Z6xYCp0Tpo3eKrN2ZPyWWAr9CBZlTlqJOvwbxglUFhfv0vy3W2mX5+j12lTx6aDz5xl8U+zV4AUW1ijoHSfptUIAaQp/rPAYHBUaWqlQ7Tx0FFrsQ6hR5oCBw5qFOkQIhiM0wldhkQSPCTDvrXhYh5jR4CvsVFrIJKYJ/eOMxESa5dmB7Ky3kPjU60MvuIa0lEzVdNg7P/9yVApZ2vZQaKnY2/8A4OyYPfMDAAA=)

---

I'll fix the style
