### ISSUE TITLE
[style]: improve styles for component stepper in mode light

### ISSUE THREAD

**Issue by gerzon05** [radix-vue/shadcn-vue#675]
in the light mode of the stepper component the icon in the menu below to be executed has a color error

![image](https://github.com/user-attachments/assets/223a1880-9173-48ed-b724-e2690844eb6b)

I can solve it.

**Comment by sadeghbarati** [comment]
Thanks go for it please 

Also, you can use this doc for inspiration

https://ui-thing.behonbaker.com/components/stepper

`ui-thing` is also based on `radix-vue`
