### ISSUE TITLE
[Bug]: v-bind syntax error in RangeCalendarHeading.vue for Vue

### ISSUE THREAD

**Issue by matteokocken** [radix-vue/shadcn-vue#679]
### Reproduction

Reproduction

### Describe the bug

There's a syntax error in the RangeCalendarHeading.vue component when used with Vue. The component uses React's prop spreading syntax (:heading-value) which is not compatible with Vue.

Current Behavior

The following error is thrown:

```
[plugin:vite:vue] v-bind is missing expression.
/path/to/RangeCalendarHeading.vue:23:11
21 |      v-bind="forwardedProps"
22 |    >
23 |      <slot :heading-value>
   |             ^
24 |        {{ headingValue }}
25 |      </slot>
```

Expected Behavior
The component should use Vue's v-bind directive for prop spreading.
Steps to Reproduce

Use the RangeCalendar component in a Vue project
Attempt to render the component
Observe the error in the console

Proposed Solution
Change the following line in RangeCalendarHeading.vue:
From:

```
<slot :heading-value>
```

```
<slot v-bind:heading-value="headingValue">
```

### System Info

```bash
System:
    OS: macOS 14.4
    CPU: (11) arm64 Apple M3 Pro
    Memory: 177.00 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - ~/.nvm/versions/node/v22.3.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v22.3.0/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.4
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
`:heading-value` is new Vue shorthand binding props

Make sure you are using latest `Volar` and `Vue` please
