### ISSUE TITLE
[Feature]: Need Chart 

### ISSUE THREAD

**Issue by MahediAmin** [radix-vue/shadcn-vue#69]
### Describe the feature

Need chart like  shadcn react in theme page

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Yes @MahediAmin . The PR for unovis/vue is almost done. It will be track here.https://github.com/radix-vue/shadcn-vue/issues/33  Thanks!
