### ISSUE TITLE
[Bug]: Sonner - can't update gap value

### ISSUE THREAD

**Issue by kikky7** [radix-vue/shadcn-vue#694]
### Reproduction

In code below

### Describe the bug

Overriding offset and duration works, gap doesn't. It stays 14px, which is the default.

Also, is there a way to change the gap between expanded toasts?

```
<Toaster position="top-right" offset="1rem" :gap="8" :duration="10000" />
```

### System Info

```bash
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 66.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.3/bin/npm
    pnpm: 8.9.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.88
    Safari: 17.5
  npmPackages:
    @vueuse/core: ^10.11.0 => 10.11.0 
    radix-vue: ^1.9.1 => 1.9.1 
    vue: ^3.4.0 => 3.4.31
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
I submitted a PR to `vue-sonner` which will resolve this issue

https://github.com/xiaoluoboding/vue-sonner/pull/78

It has some strange error which I couldn't find the problem

**Comment by sadeghbarati** [comment]
VueSonner version `1.2.1` will resolve this
