### ISSUE TITLE
[Feature]: Command

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#7]
### Describe the feature

https://ui.shadcn.com/docs/components/command

Realized it requires `cmdk` component.
We could use https://github.com/xiaoluoboding/vue-command-palette

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by wasimTQ** [comment]
@zernonia I'd like to start from here

**Comment by zernonia** [comment]
@wasimTQ  sure! I'm not sure how extensive, and easy to style `vue-command-pallete`. You may give it a try.
But I would most likely leaning into developing `Combobox` in [Radix Vue](https://github.com/radix-vue/radix-vue/issues/343)

**Comment by wasimTQ** [comment]
Sure. I'll give it a try. I was planning to work on this or the theming. But I hope this will be a pretty good challenge for me

**Comment by wasimTQ** [comment]
Then I'll start off with Combobox first. Thank you for the suggestion

**Comment by wasimTQ** [comment]
@zernonia Are you working on this atm?

**Comment by zernonia** [comment]
@wasimTQ  not yet.. but was about to 😂 maybe you can help with the [theming](https://github.com/radix-vue/shadcn-vue/issues/26)?

**Comment by wasimTQ** [comment]
Sure. But I think it's a bit too much for me to start my first contribution.
I'll give it a shot. 
If you find anything more beginner friendly, please share it with me

**Comment by k11q** [comment]
I found the command component has some accessibility issues. I dont think you need command component for it, you essentially need a searchbox/autocomplete for it,

Maybe these can serve as reference aswell
https://ariakit.org/components/combobox
https://ariakit.org/examples/combobox-multiple

**Comment by zernonia** [comment]
Yup @khairulhaaziq ! that's why I mentioned the combobox ticket above in my comment 😁
