### ISSUE TITLE
[Bug]: Open Select = unvisible all scroll

### ISSUE THREAD

**Issue by nikolos89** [radix-vue/shadcn-vue#703]
### Reproduction

https://www.shadcn-vue.com/docs/components/select.html

### Describe the bug

https://www.shadcn-vue.com/docs/components/select.html#examples

after install this component - in my app invisible my right scroll, in moment select=open.

how fix is it ?

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12450H
    Memory: 5.66 GB / 15.71 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.11.0 => 10.11.0
    radix-vue: ^1.9.2 => 1.9.2
    vue: ^3.4.31 => 3.4.31
```

And how can I keep track of the status of the list being open or closed in order to rotate checkerDown?

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
You can use `<SelectContent :bodyLock="false">` prop on the `SelectContent` to prevent body scroll lock (unvisible scroll)

**Comment by nikolos89** [comment]
great, it worked!
