### ISSUE TITLE
[Feature]: I think we should suggest in nuxt installation guide that usage of `shadcn-nuxt` is optional

### ISSUE THREAD

**Issue by gigabites19** [radix-vue/shadcn-vue#712]
### Describe the feature

auto-imports in nuxt are highly subjective, I think it'd be better if docs mentioned that adding `shadcn-nuxt` module is not necessary and should only be done if you plan to use auto-imports.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
It's kinda necessary 

see these issues

- https://github.com/radix-vue/shadcn-vue/issues/172#issuecomment-1810247248
- https://github.com/radix-vue/shadcn-vue/issues/173#issuecomment-1812155845
