### ISSUE TITLE
[Bug]: Tags input not getting styled

### ISSUE THREAD

**Issue by laraib07** [radix-vue/shadcn-vue#718]
### Reproduction

too much setup

### Describe the bug

Copy pasting the demo code of TagsInput but this is how it looks:

<img width="359" alt="Screenshot 2024-08-17 at 4 46 41 PM" src="https://github.com/user-attachments/assets/199c3897-100e-4ee2-9703-2d0b664578db">

### System Info

```bash
System:
    OS: macOS 11.7.10
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 29.95 MB / 4.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 127.1.68.141
    Safari: 16.6.1
  npmPackages:
    @vueuse/core: ^10.9.0 => 10.9.0
    radix-vue: ^1.6.1 => 1.8.0
    vue: ^3.4.21 => 3.4.27
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Hi, you don't even share what part of `TagsInput` you want to customize then how can we help you?

Add more context and simple reproduction, it's not that hard, closing for now will reopen after repro

https://antfu.me/posts/why-reproductions-are-required


---

If you are using TailwindCSS, just adjust the code you get from `shadcn-vue` registry
