### ISSUE TITLE
[Bug]: Incorrect Installs, mismatch in component content  

### ISSUE THREAD

**Issue by orenmizr** [radix-vue/shadcn-vue#74]
### Environment

```bash
"radix-vue": "^0.2.3",
    "tailwind-merge": "^1.14.0",
    "tailwindcss-animate": "^1.0.7",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.0.0",
"@nuxtjs/tailwindcss": "^6.8.0",

linux.
```

### Link to minimal reproduction

https://github.com/radix-vue/

### Steps to reproduce

follow docs's install for a button and add it via the cli. 

### Describe the bug

followed the docs. 
1. when installing a button  there is a difference between the copy code from site and the button via the add cli. 
2. when you add the code via cli its adds on my linux extra quotes which makes the component unusable until manually corrected. 

``
"'Button'" instead of "Button"
``

### Expected behavior

1. valid code. that compiles. 
2. to match the content that is manually. (looking at the classes i saw different sets)

**Comment by zernonia** [comment]
@orenmizr  at which line that it added extra single quote ya? In `@/components/button/index.ts`?

**Comment by orenmizr** [comment]
it was all the files that were added via the cli (linux machine). instead of correcting it, ended up copying from the "copy to clipboard" in the docs. the import were valid but i don't think the button cli version the web version were 100% the same - i saw classes that were different. 

i will add it again to a greenfield project and test it. (in that project, i use pugjs plus i had naive-ui install as well)

**Comment by orenmizr** [comment]
in a clean project. it worked well. no extra quotes '""'   also the button rendered correct. the only thing i might have done differently is choose css variables this time. other than that, can't really explain. you can close this - if i figure out the issue i will open a specific one. (no pugjs in the clean nuxt project also might be related)

**Comment by SGDS-SyL** [comment]
Any update on this? Facing the same issue as well
