### ISSUE TITLE
[Bug]: number field component is not installing by cli and no manual installation is available.

### ISSUE THREAD

**Issue by AmrTamer23** [radix-vue/shadcn-vue#741]
### Reproduction

None

### Describe the bug

number field component is not installing by cli and no manual installation is available.

![image](https://github.com/user-attachments/assets/3baba0f7-50de-4e9f-849c-93e8e0051876)

![image](https://github.com/user-attachments/assets/2acf14cc-6642-446f-a833-f2be242a3fd7)

### System Info

```bash
No System info is needed
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Are you using Nuxt with JS?

for manual installation just check this path and copy it

https://github.com/radix-vue/shadcn-vue/tree/dev/apps/www/src/lib/registry/default/ui/number-field

**Comment by sadeghbarati** [comment]
If you are using Nuxt without TS check this issue

https://github.com/radix-vue/shadcn-vue/issues/291#issuecomment-1901788144

**Comment by AmrTamer23** [comment]
I just realized that the installation was done outside the project directory even I ran the command inside the project, this is certainly a bug, and yes I use Nuxt with typescript and have a seperate ts config file with type check and restrict options is on in Nuxt config.
