### ISSUE TITLE
[Feature]: UNO CSS Support

### ISSUE THREAD

**Issue by theDeal** [radix-vue/shadcn-vue#745]
### Describe the feature

I propose adding support for UNO CSS in shadcn-vue. UNO CSS is a utility-first CSS framework that combines the best of Tailwind CSS and Windi CSS. It offers excellent tree-shaking capabilities, a flexible utility API, and a small footprint, making it a perfect fit for modern Vue.js projects. Integrating UNO CSS into shadcn-vue would enable developers to take advantage of its performance optimizations and concise syntax while building UI components. This would enhance the overall developer experience and improve performance, particularly in large-scale applications.

Additional Context
Including UNO CSS in shadcn-vue could involve adding pre-configured utilities and ensuring that the existing components are fully compatible with UNO CSS classes. This would allow developers to seamlessly use UNO CSS out of the box or extend the framework according to their project needs. Moreover, documentation and examples should be provided to guide developers in leveraging UNO CSS within shadcn-vue.

Thank you for considering this feature request. I believe it would greatly benefit the shadcn-vue community by providing more flexibility and efficiency in styling Vue.js applications.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
@theDeal This issue already exists, and it should be on the roadmap in the future, right now other maintainers focus on v2 of `radix-vue` and `Vue 3.5`

https://github.com/radix-vue/shadcn-vue/issues/34

**Comment by theDeal** [comment]
Thanks for clarification
