### ISSUE TITLE
[Bug]: Alert-dialog doesn't working in nuxt

### ISSUE THREAD

**Issue by maphstay** [radix-vue/shadcn-vue#754]
### Reproduction

Install alert dialog and button component

### Describe the bug

after install alert dialog component, we face import errors in two files:
- AlertDialogAction.vue
- AlertDialogCancel.vue

the error is from this line in both files: 
import { buttonVariants } from 'src/components/ui/button';

the message error:
Cannot find module 'src/components/ui/button' or its corresponding type declarations.

errors printscreen:
![image](https://github.com/user-attachments/assets/a22d930f-8c81-4037-8e10-8edd31930ec2)

Solution:
if we just update the import to this way (using @), the issue is solved !
import { buttonVariants } from '@/components/ui/button';

### System Info

```bash
System:
    OS: Linux Ubuntu 22.04.4
  Binaries:
    Node: 20.16.0
    yarn: 1.22.18
  npmPackages:
   "@vueuse/core": "^10.10.0",
   "radix-vue": "^1.7.3",
   "nuxt": "^3.12.4",
   "vue": "^3.4.21",
   "shadcn-nuxt": "^0.10.4",
   "shadcn-vue": "^0.10.4",
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Check this Stackblitz and download the project 

https://stackblitz.com/edit/github-btreug?file=nuxt.config.ts,app.vue

---

Please follow the Nuxt installation steps carefully https://www.shadcn-vue.com/docs/installation/nuxt.html

**Comment by maphstay** [comment]
> Check this Stackblitz and download the project
> 
> https://stackblitz.com/edit/github-btreug?file=nuxt.config.ts,app.vue
> 
> Please follow the Nuxt installation steps carefully https://www.shadcn-vue.com/docs/installation/nuxt.html

I found the missing param that solve this issue, it is this line in components.json file:
"tsConfigPath": ".nuxt/tsconfig.json",

I've never seen about this param before in any documentation, it is really important to say about.

Thank you for your answer.
