### ISSUE TITLE
[Bug]: Two component files resolving to the same name <component name> (Nuxt 4)

### ISSUE THREAD

**Issue by onurusluca** [radix-vue/shadcn-vue#763]
### Reproduction

Sorry, tried but can't get StackBlitz or CodeSandbox working.

### Describe the bug

Even with TypeScript installed as a dependency, with Nuxt 4, getting this error. 
[This was resolved before](https://github.com/radix-vue/shadcn-vue/issues/39) with Nuxt 3 versions by installing TypeScript.

Reproduction: 
I am sorry I wasn't able to add a reproduction. If someone can share, it'd be much appreciated.
[Use Nuxt 4](https://nuxt.com/docs/getting-started/upgrade#upgrading-nuxt), add [Shadcn-vue](https://www.shadcn-vue.com/docs/installation/nuxt.html), pnpm dev.

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor     
    Memory: 9.54 GB / 31.93 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.10.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (128.0.2739.42)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vueuse/core: ^11.0.3 => 11.0.3
    nuxt: 3.13.1 => 3.13.1
    radix-vue: ^1.9.5 => 1.9.5
    shadcn-nuxt: ^0.10.4 => 0.10.4
    vue: ^3.5.4 => 3.5.5
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by onurusluca** [comment]
Of course just after 5 minutes of posting the question, I find the answer. :D

Fix:
```
  shadcn: {
    prefix: "",
    componentDir: "./app/components/ui",  // Change to new directory
  },
```
Change your componentDir to new components directory, It was `componentDir: "./components/ui"` before.

Just an FYI: I had to change some of my imports that are outside of the "app" folder because now @ or ~ points to "app" not "/".

**Comment by thiagolcks** [comment]
Thank you @onurusluca ! I was facing the same problem, I didn't realized that @ do not work here.

**Comment by DesertCookie** [comment]
What did you to about the `/libs/utils.ts` containing the `cn` function? Did you figure out how to move that into the new `app` directory?

**Comment by Nisthar** [comment]
@onurusluca is the `add` command adding components into the right folder for you? have you changed anything in the `.nuxt/tsconfig.json` file or no?

**Comment by onurusluca** [comment]
> @onurusluca is the `add` command adding components into the right folder for you? have you changed anything in the `.nuxt/tsconfig.json` file or no?

I don't think I changed anything no. Check parent folders. Once I was surprised to find out components folder was created in the folder that has the parent of the project. Something like C:/Codes/<it was here>/projects/my-project.

**Comment by onurusluca** [comment]
> What did you to about the `/libs/utils.ts` containing the `cn` function? Did you figure out how to move that into the new `app` directory?

Just change the libs directory to where you put the file. Same as the answers to this post.

**Comment by Theiaz** [comment]
> Of course just after 5 minutes of posting the question, I find the answer. :D
> 
> Fix:
> 
> ```
>   shadcn: {
>     prefix: "",
>     componentDir: "./app/components/ui",  // Change to new directory
>   },
> ```
> 
> Change your componentDir to new components directory, It was `componentDir: "./components/ui"` before.
> 
> Just an FYI: I had to change some of my imports that are outside of the "app" folder because now @ or ~ points to "app" not "/".

This did not work for me, but it worked using [aliases](https://nuxt.com/docs/api/nuxt-config#alias).

> ```
>   shadcn: {
>     prefix: "",
>     componentDir: "~/app/components/ui",  // use ~or @ to reference srcDir
>   },
> ```

**Comment by Psycarlo** [comment]
I am using a monorepo and

```ts
import tailwindcss from '@tailwindcss/vite'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const currentDir = dirname(fileURLToPath(import.meta.url))

export default defineNuxtConfig({
  ...,
  shadcn: {
    prefix: '',
    componentDir: join(currentDir, './app/components/ui')
  },
})
```

does not work: `Failed to resolve component: UiButton`

**Comment by gomiunik** [comment]
any update on this? neither solution works. Upgraded from nuxt3, get a ton of warning about two component files. tried 
* componentDir: "./app/components/ui",
* componentDir: "@/components/ui",
* componentDir: "~/components/ui",
* componentDir: "~~/app/components/ui",

and still nothing.

**Comment by jshrssll** [comment]
Still getting this error and plenty of these too

``` WARN  Overriding TableFooter component. You can specify a priority option when calling addComponent to avoid this warning.```

Tried all of the above nuxt config suggestions, none work.

**Comment by xak2000** [comment]
The first solution above worked for me with Nuxt 3.18.1 with `future.compatibilityVersion` set to `4` and `shadcn-nuxt` 2.1.0.

It stopped working after I upgraded to Nuxt 3.21.1 (the flag `future.compatibilityVersion` is still set to `4`, so the new directory structure is used).

What worked for me is adding [ignore](https://nuxt.com/docs/4.x/api/nuxt-config#ignore) rule into `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  // ...
  ignore: ['app/components/ui/**'],
  // ...
})
```

All components inside `app/components/ui/**` should be registered by the `shadcn-nuxt` module anyway.

I think it should be also possible to add this rule into [.nuxtignore](https://nuxt.com/docs/4.x/directory-structure/nuxtignore). Whatever works for you best.

I suspect this solution should work with Nuxt 4.x too as Nuxt 4 does support `ignore` and `.nuxtignore` options.
