### ISSUE TITLE
[Bug]: Extra ] bracket in cn class in DialogScrollContent component after dialog installation

### ISSUE THREAD

**Issue by Dominik221** [radix-vue/shadcn-vue#772]
### Reproduction

1. Install `shadcn-vue`. 
2. Install `npx shadcn-vue@latest add dialog`
3. Run the application and observe the error message related to the extra closing bracket.

### Bug description

After installing the Dialog component from the shadcn-vue package, an unnecessary closing bracket ] is generated at the end of the class string inside the :class attribute for DialogScrollContent.

The problematic code looks like this:

`:class="
cn(
  'relative z-50 grid w-full max-w-lg my-8 gap-4 border border-border bg-background p-6 shadow-lg duration-200 sm:rounded-lg md:w-full',
  props.class
)]"`

### System Info

```bash
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
  Browsers:
    Brave Browser: 128.1.69.168
    Chrome: 128.0.6613.138
    Safari: 18.0
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
Fixed on [v0.11.0](https://github.com/unovue/shadcn-vue/releases/tag/v0.11.0)
