### ISSUE TITLE
[Bug]: Dark mode not working

### ISSUE THREAD

**Issue by ezekel** [radix-vue/shadcn-vue#78]
### Environment

```bash
Development OS: Windows 10 
Node version: v16.19.0
Package manager: npm@8.19.2
Shadcn Vue version:shadcn-vue@0.1.9
Vue version: ^3.3.4
```

### Link to minimal reproduction

none

### Steps to reproduce
```
<template>
  dark
  <DashBoard/>
</template>
```

### Describe the bug

Hi, I noticed a strange behavior.

In my index.html, I manually added the class dark. Then, I ran npm run dev, expecting it to enable dark mode. However, the background remained white, indicating that dark mode was not working.

```
<!DOCTYPE html>
<html lang="en" class="dark">
```

To resolve this, I added the text 'dark' after an HMR (Hot Module Replacement) update. After this change, dark mode started working, and the background turned dark. I'm not sure what went wrong, but it seems I had to add the 'dark' text to my template.

App.vue

```
<template>
  dark
  <DashBoard/>
</template>
```

### Expected behavior

The dark mode should work if I add a dark class to the HTML tag

**Comment by zernonia** [comment]
Hi @ezekel .. this seems like some `tailwind.config` issue, rather than `shadcn-vue`'s. Could you perhaps check that you 
 have `darkMode: 'class` in `tailwind.config.js`? 😁

Or at least provide a minimal repo?

**Comment by ezekel** [comment]
Yes, I have that in my tailwind.config

I just changed this class from
```
.dark{
}
```

to 
```
 :root[class~="dark"]{

}

```

and it works.

I followed this link

https://github.com/shadcn-ui/ui/issues/313#issuecomment-1676513456

**Comment by zernonia** [comment]
Nice find @ezekel ! Perhaps we can fix it in our `style.css` too 😁
Wanna help by creating a PR?

**Comment by selemondev** [comment]
May I be assigned to handle this issue, @zernonia ?

**Comment by sadeghbarati** [comment]
@ezekel 

If you are using `@vueuse/core` [**useDark**](https://vueuse.org/core/useDark/) in `Vite` or `Nuxt` 
Check comment below 👇 By mio :0

---

If you using `Nuxt` [**@nuxtjs/color-mode** ](https://color-mode.nuxtjs.org/) is recommended

**Comment by miosenpai** [comment]
This is because `shadcn-vue` implements dark theme with CSS variables under `@layer base` and Tailwind removes [unused CSS in its own layers](https://tailwindcss.com/docs/adding-custom-styles#removing-unused-custom-css). One way to address this is to just safelist `dark`, for example:
```ts
// nuxt.config.ts
tailwindcss: {
  viewer: false,
  config: {
    safelist: [
      'dark'
    ]
  }
},
```

**Comment by antonreshetov** [comment]
Why is this still not fixed?

**Comment by sadeghbarati** [comment]
> Why is this still not fixed?


There is no bug here

We just keep this open until we add Dark mode documentation

**Comment by zernonia** [comment]
As there's no generalized solution for this case.. it really depends on which framwork you use. Thus as @sadeghbarati  mentioned, we will be adding docs regarding Dark mode https://github.com/radix-vue/shadcn-vue/issues/236

**Comment by antonreshetov** [comment]
> As there's no generalized solution for this case.. it really depends on which framwork you use.

Well, you can make a separate solution for each framework. When initializing through `npx shadcn-vue@latest init`, not so many of them are supported. Or simply change the style description as written here https://github.com/radix-vue/shadcn-vue/issues/78#issuecomment-1735793695
