### ISSUE TITLE
[Bug]: Drawer is not actually a drawer

### ISSUE THREAD

**Issue by alectrocute** [radix-vue/shadcn-vue#781]
### Reproduction

https://codesandbox.io/p/devbox/shadcn-vue-drawerdemo-725z9h

### Describe the bug

The `Drawer` component isn't really a drawer. It's a mobile dialog replacement. This is confusing when the developer is trying to find a typical drawer that opens from the left or right, assumes the shadcn-vue has that functionality for its `Drawer` component (because why wouldn't it?), do a ton of research into the vendor child components just to realize it's a pop-up-from-bottom only drawer. At the very least, we should add more details to the [`Drawer` doc](https://www.shadcn-vue.com/docs/components/drawer.html) to say that this is purely a dialog alternative for mobile.

### System Info

```bash
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.95 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 9.10.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 129.0.6668.59
    Chrome Canary: 122.0.6180.0
    Safari: 17.6
  npmPackages:
    @vueuse/core: ^10.11.1 => 10.11.1 
    radix-vue: ^1.9.4 => 1.9.4 
    vue: ^3.4.27 => 3.4.37
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by MuhammadM1998** [comment]
I think what you're searching for is the [Sheet component](https://www.shadcn-vue.com/docs/components/sheet.html)?

**Comment by zernonia** [comment]
We are following the component design (and it's naming) as the main [Shadcn UI](https://ui.shadcn.com/docs/components/drawer). Thus closing this as not planned
