### ISSUE TITLE
[Bug]: Focus issue in dialog when typing in input and chaning dynamically a list

### ISSUE THREAD

**Issue by ghost** [radix-vue/shadcn-vue#783]
### Reproduction

https://stackblitz.com/edit/8caksq-roy6na?file=src%2FApp.vue

### Describe the bug

Hello,

I am encountering an issue with a dialog component while using Vite, Vue 3.

### Context

- I have a `dialog` that contains a list.
- This list updates dynamically each time I type in an input field.
- However, sometimes the dialog itself gains focus(we can see the black border of the dialog-content), which removes focus from the input field, causing typing to stop.

### Investigation

- I checked the `dialog` element in the browser console and noticed that it has a `tabindex="-1"` attribute.
- If I manually remove this attribute from the `dialog` element in the console, the issue no longer occurs.

### Question
Is there a way to disable or prevent the `tabindex="-1"` from affecting the focus on the input field within the dialog?

### Important
I attempted to reproduce this issue with a simple demo on [StackBlitz](https://stackblitz.com/edit/8caksq-roy6na?file=src%2FApp.vue), but I was **unable** to replicate the bug in that environment. My local development project is more complex with `Form` etc...

Thanks for your help!

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1345U
    Memory: 16.66 GB / 31.64 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.98)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @vueuse/core: ^11.0.3 => 11.1.0
    radix-vue: ^1.9.5 => 1.9.5
    vue: ^3.5.4 => 3.5.6
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
I can't reproduce it on Stackblitz,

You need to find the re-rendering cause, use the new https://devtools.vuejs.org/ or with previous Vue devtools 

With highlight render option

**Comment by ghost** [comment]
### Issue Update
I’ve tested the setup on a more advanced StackBlitz environment that closely resembles my local setup (though it's impossible to replicate exactly), and I’m still unable to resolve the unknown bug.

As a temporary solution (or possibly a permanent one), I’ve set the `tabindex` value to `null` in Shadcn to override the one set by Radix. 
```
:tabindex="null"
```
I’m not sure why Radix has a tabindex (even `-1`, which prevents tabbing) on a `<div>` that cannot be focused by default.

This is my current workaround.
