### ISSUE TITLE
[Bug]: Form and FormField not in registry?

### ISSUE THREAD

**Issue by blazmrak** [radix-vue/shadcn-vue#789]
### Reproduction

https://nuxt.new

### Describe the bug

From the docs it seems like the components should be included when adding the form module, but they are missing from the registry. 

https://www.shadcn-vue.com/registry/styles/default/form.json
https://www.shadcn-vue.com/registry/styles/new-york/form.json

Are these two components provided somewhere else?

### System Info

```bash
/
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by blazmrak** [comment]
Nevermind, I'm beyond stupid

**Comment by andrewbroberg** [comment]
@blazmrak What was it in the end? As I believe I may be beyond stupid as well, but haven't figured out why yet lol

**Comment by blazmrak** [comment]
@andrewbroberg it is exported from the index. Just reuses the component from the ~component library~ vee-validate.

```javascript
// index.ts
export { Field as FormField, Form } from 'vee-validate'
```

**Comment by andrewbroberg** [comment]
@blazmrak 🤦thanks!
