### ISSUE TITLE
[Bug]: project created via `pnpm` installs components on project root folder 

### ISSUE THREAD

**Issue by boonyasukd** [radix-vue/shadcn-vue#80]
### Environment

```bash
Development/Production OS: WSL on Windows 11 Pro Version `10.0.22621 Build 22621`
Node version: `20.5.1`
Package manager: `pnpm@8.7.0`
Shadcn Vue version: `@latest`
Vue version: `3.3.4`
CSS framework: `tailwindcss@3.3.3`
Client OS: Windows 11 Pro Version `10.0.22621 Build 22621`
Browser: Firefox `117.0.1`
```

### Link to minimal reproduction

n/a

### Steps to reproduce

Attempting to create a new project via `pnpm` to create `my-vue-app` project as a Typescript/Vue project:

```console
me@pc:~$ pnpm create vite
✔ Project name: … my-vue-app
✔ Select a framework: › Vue
✔ Select a variant: › TypeScript

Scaffolding project in /home/b0nyb0y/dev/projects/my-vue-app...

Done. Now run:

  cd my-vue-app
  pnpm install
  pnpm run dev

```

Then, after editing `tsconfig.json`, and `vite.config.ts` (as shown in attached screenshot):

```console
me@pc:~$ cd my-vue-app
me@pc:~$ pnpm add -D -E tailwindcss postcss autoprefixer @types/node
me@pc:~$ pnpm dlx tailwindcss init -p
Created Tailwind CSS config file: tailwind.config.js
Created PostCSS config file: postcss.config.js
```

Then I initialized `shadcn-vue` and add a `<Button>`...

```console
me@pc:~$ pnpm dlx shadcn-vue@latest init
✔ Would you like to use TypeScript (recommended)? … yes
✔ Which framework are you using? › Vite
✔ Which style would you like to use? › Default
✔ Which color would you like to use as base color? › Slate
✔ Where is your Tailwind CSS file? … src/assets/index.css
✔ Would you like to use CSS variables for colors? … no / yes
✔ Where is your tailwind.config.js located? … tailwind.config.js
✔ Configure the import alias for components: … @/components
✔ Configure the import alias for utils: … @/lib/utils
✔ Write configuration to components.json. Proceed? … yes

✔ Writing components.json...
✔ Initializing project...
✔ Installing dependencies...

Success! Project initialization completed.

me@pc:~$ pnpm dlx shadcn-vue@latest add button
✔ Ready to install components and dependencies. Proceed? … yes
✔ Done.
```

### Describe the bug

The last two steps where I initialized `shadcn-vue` and add `<Button>` component, a folder `@` is added to the root of the project. When the last command is executed, all the code for `<Button>` is also put in this `@` folder.

From the way `tsconfig.json` and `vite.config.ts` are configured, I expect all the code in this `@` folder to be in `./src/components` (or `./src/lib`) so that Typescript can find and transpile the code.

While running `pnpm run dev`, when `<Button>` is used in `App.vue`, the page failed to load. Only when I copied all files from `./@` folder to `./src` folder that the page loads correctly again.

### Expected behavior

Expecting the commands provided in documentation to work without having to manually copying folders around.

### Conext & Screenshots (if applicable)

![image](https://github.com/radix-vue/shadcn-vue/assets/8109816/58f35d95-7588-4ca9-8c34-4503a59fcdb2)

**Comment by boonyasukd** [comment]
With further testing, it was found that, creating a new project via `npm` also yield the same result: `/lib/utils.ts` and `/components/ui/*` are installed in `@` folder.

I tried to use actual folder paths instead of aliases (`src/components` and `src/lib`) when calling `init` command, the files are placed in their rightful places, but the `import` statement inside component will break, since it expects an aliased path.

**Comment by zernonia** [comment]
@boonyasukd does the monorepo have multiple `tsconfig.json` files? I'm suspecting that the CLI doesn't capture the correct `tsconfig` that you have setup with the `path` alias

**Comment by boonyasukd** [comment]
@zernonia The project isn't part of a monorepo, unfortunately. It's placed in my `~/dev/projects`, which has no `tsconfig.json`. All other repos (`~/dev/projects/*`) have their own `tsconfig.json`, of course, but I doubt `shadcn-vue` will look into them.

**Comment by boonyasukd** [comment]
@zernonia Tested on another machine. Repeating the same steps as above to create a `vite`/`typescript` project, I got the same result (`/@` folder at project root). This time I tested it on `macOS`. I'm starting to think the problem isn't on my end:

```bash
Development/Production OS: `macOS Big Sur` (MB Pro 13-inch, mid 2014)
Node version: `20.7.0`
Package manager: `pnpm@8.7.6`
Shadcn Vue version: `@latest`
Vue version: `3.3.4`
CSS framework: `tailwindcss@3.3.3`
Client OS: `macOS Big Sur` (MB Pro 13-inch, mid 2014)
Browser: Firefox `117.0.1`
```

![image](https://github.com/radix-vue/shadcn-vue/assets/8109816/986f6265-a26d-413b-9b64-d89cf1e852c1)

**Comment by boonyasukd** [comment]
It was a stupid mistake on my part. `baseUrl` & `paths` needs to be inside `compilerOptions`. I found it the roundabout way of running a local copy shadcn-vue-cli, only to realize that `tsconfig.json` is being read correctly.
