### ISSUE TITLE
[Bug]: Override warnings with fresh install on Nuxt 3

### ISSUE THREAD

**Issue by IllustrisJack** [radix-vue/shadcn-vue#818]
### Reproduction

https://www.shadcn-vue.com/docs/installation/nuxt

### Describe the bug

On a fresh install of Nuxt 3 & shadcn-vue i am getting Nuxt 3 warnings about Nuxt 3 auto-import `addComponent`

For every X component installed
```
WARN  Overriding X component. You can specify a priority option when calling addComponent to avoid this warning.                                                                          19:53:17  
```

Seems like the nuxt module is missing that priority option here https://github.com/unovue/shadcn-vue/blob/f9615d3657f895f18763d62ecf45cd0e5cc8041d/packages/module/src/module.ts#L89

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 4.51 GB / 15.96 GB
  Binaries:
    Node: 20.9.0 
    Yarn: 1.22.11
    npm: 10.1.0 
    pnpm: 8.10.2
  Browsers:
    Chrome: 129.0.6668.101
    Edge: Chromium (129.0.2792.89)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @vueuse/core: ^11.1.0 => 11.1.0
    nuxt: ^3.13.0 => 3.13.2
    radix-vue: ^1.9.7 => 1.9.7
    shadcn-nuxt: ^0.10.4 => 0.10.4
    vue: latest => 3.5.12
```

### Contributes

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by SwartZCoding** [comment]
Same issue here. If someone know how to fix this :)

**Comment by IllustrisJack** [comment]
> Same issue here. If someone know how to fix this :)

My fix should work for now check https://github.com/unovue/shadcn-vue/pull/838 if you want to apply manually before a possible merge
