### ISSUE TITLE
[Feature]: Publish v0.11.0 of shadcn-nuxt

### ISSUE THREAD

**Issue by GazEdge** [radix-vue/shadcn-vue#830]
### Describe the feature

shadcn-nuxt is currently published to 0.10.4.

shadcn-vue is currenty published to 0.11.0

Please can shadcn-nuxt be published to 0.11.0. I can see in source code that packages/module does appear to have been updated inline with 0.11.0 changes.

Is there some blocker/reason as to why published package has not been updated?

Happy to help move along, but cant currently see what would be stopping publishing

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Hi 👋 

The last npm publish `v0.11.2` was 5 days ago so this issue can be resolved
