### ISSUE TITLE
[Feature]: Replace iconify icons with `radix-icons/vue` for NewYork style

### ISSUE THREAD

**Issue by zernonia** [radix-vue/shadcn-vue#84]
### Describe the feature

Using iconify icons causing some confusion after installing `new-york` style, and hard to setup because it requires a few deps and configuration on `vite.config`. Thus changing the icons into newly published https://www.npmjs.com/package/radix-icons would solved that issue

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by SamantaTarun** [comment]
Could you please brifely describe it over here?

**Comment by sadeghbarati** [comment]
Probably good to add in the docs

The difference between `Icon packages` with `Icon tools` like


### PureCSS icons
- [`@iconify/tailwind`](https://iconify.design/docs/usage/css/tailwind/)
- [`egoist/tailwindcss-icons`](https://github.com/egoist/tailwindcss-icons)
- [`@unocss/preset-icons`](https://github.com/unocss/unocss/tree/main/packages/preset-icons#readme)

### Icon Components

- [`iconify-icon`](https://iconify.design/docs/iconify-icon/) (Web component)
- [`unplugin-icons` ](https://github.com/unplugin/unplugin-icons)


---

https://iconly-and-iconify.vercel.app (Custom iconset with unocss-preset-icon)
[source](https://github.com/sadeghbarati/iconly-and-iconify)
