### ISSUE TITLE
[Bug]: Calendar

### ISSUE THREAD

**Issue by QQOQ** [radix-vue/shadcn-vue#859]
### Reproduction

https://vite.new

### Describe the bug

The code import { buttonVariants } from '@/lib/registry/default/ui/button' exists in the file components/ui/calendar/CalendarPrevButton.vue created by running npx shadcn-vue@latest add calendar, but the path @/lib/registry/default/ui/button does not exist.

### System Info

```bash
vue3
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by zernonia** [comment]
@QQOQ  Please provide minimal reproduction. Couldn't replicate this
