### ISSUE TITLE
[Bug]: TooltipContent: Missing Required Attribute Warnings in IntelliJ IDEA

### ISSUE THREAD

**Issue by ghost** [radix-vue/shadcn-vue#863]
### Reproduction

Can't really have a reproduction

### Describe the bug

Hi, I wanted to report a minor issue that I encountered while working with the `TooltipContent` component.

### Description
When using the `TooltipContent` component from `shadcn-vue`, IntelliJ IDEA 2024.2.4 (Ultimate Edition) displays 9 warnings for missing required attributes, even though the component functions correctly without explicitly setting these attributes.

### Warnings:
![warn](https://github.com/user-attachments/assets/3691adba-13f3-4d42-a2d7-8ad9fbbf8664)

### Steps to Reproduce:
1. Use the `TooltipContent` component in a Vue project.
2. Open the project in IntelliJ IDEA 2024.2.4 (Ultimate Edition).
3. Observe the warnings related to missing attributes.

### Expected Behavior:
No warnings should be shown if these attributes are optional and have default values handled internally by the component.

### Actual Behavior:
Warnings are displayed for missing required attributes.

### Additional Information:
Is there a way to configure IntelliJ IDEA to avoid these warnings, or should the component's TypeScript definitions be updated to reflect the optional nature of these attributes?

### Environment:
- **shadcn-vue version:** Don't know where find version
- **IntelliJ IDEA version:** 2024.2.4 (Ultimate Edition)
- **Vue version:** 3.5.4

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1345U
    Memory: 16.57 GB / 31.64 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.98)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @vueuse/core: ^11.0.3 => 11.2.0
    radix-vue: ^1.9.5 => 1.9.8
    vue: ^3.5.4 => 3.5.12
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
@SAntoineS Never used other IDEs for Vue but VSCode

Here is my current setup for Vue

- **Enable** built-in TypeScript
- **Remove** TypeScript Vue Plugin (Volar) (deprecated)
- **Remove** Volar and **Reinstall** the latest version again
- **Enable** Volar `hybridMode`

**Comment by AverageCakeSlice** [comment]
I'm having this issue in Webstorm as well, going to try installing vue-tsc and related dependencies as dev dependencies, as this resolved some other type errors I was having recently in a different project. I'll report back with my findings.
