### ISSUE TITLE
[Bug]: Doc VitePress code color is not defined

### ISSUE THREAD

**Issue by HZooly** [radix-vue/shadcn-vue#865]
### Reproduction

https://www.shadcn-vue.com/docs/cli.html

### Describe the bug

Lines of txt instructions are white colored, on white background.
It seems that `--shiki-light` is not defined.
<img width="285" alt="image" src="https://github.com/user-attachments/assets/14564f20-495b-4b38-9f91-e119773b5024">

https://github.com/unovue/shadcn-vue/blob/be888c80b66528b50c7e89715cd4636059f24145/apps/www/.vitepress/theme/style.css#L136

### System Info

```bash
Arc Browser, also tested with Chrome
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
The Shiki theme is working for me, both `light` and `dark` mode

Maybe you need to clear the browser cache with <kbd>ctrl + shift + r</kbd>

**Comment by HZooly** [comment]
Indeed it is working now, I don't know what happened, I've tested in incognito and another broswer.
