### ISSUE TITLE
[Bug]: Button missing svg classnames

### ISSUE THREAD

**Issue by brianle1301** [radix-vue/shadcn-vue#871]
### Reproduction

Use any icon with button and it will appear that the icon is larger than intended

### Describe the bug

The button component is misisng the following classnames: `[&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0`

### System Info

```bash
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 70.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - ~/Library/pnpm/node
    npm: 10.8.1 - ~/Library/pnpm/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Edge: 130.0.2849.80
    Safari: 18.0
  npmPackages:
    @vueuse/core: ^11.2.0 => 11.2.0 
    radix-vue: ^1.9.9 => 1.9.9 
    vue: ^3.4.27 => 3.4.34
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
Hi PR welcomed 🙏
