### ISSUE TITLE
[Bug]: how can i disabled outside click close dialog

### ISSUE THREAD

**Issue by ozdemirmelihahmed** [radix-vue/shadcn-vue#887]
### Reproduction

https://www.shadcn-vue.com/docs/components/dialog

### Describe the bug

i want to close when i click outside the dialog

### System Info

```bash
shadcn-nuxt
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by gaao** [comment]
https://www.shadcn-vue.com/docs/components/dialog 这个链接里的例子是可以点击对话框外部关闭的，我想知道怎么在点击外部的时候不关闭对话框

**Comment by Grinch3214** [comment]
https://www.shadcn-vue.com/docs/components/alert-dialog.html

**Comment by sadeghbarati** [comment]
Hi, You can use [`AlertDialog`](https://www.shadcn-vue.com/docs/components/alert-dialog.html)

or You can use [`DialogContent`](https://www.radix-vue.com/components/dialog#content) emits and prevent them like

```vue
<DialogContent @pointerDownOutside.prevent @escapeKeyDown.prevent>
   ...
</DialogContent>
```
