### ISSUE TITLE
[Question] Is all this compatible with Astro + Vue?

### ISSUE THREAD

**Issue by Wdits** [radix-vue/shadcn-vue#90]
Hey i'm using astro.build right now and i was wondering if this is compatible, do i just have to install like it's nuxt? ty :)

**Comment by zernonia** [comment]
Hey @Wdits ! The installation steps should be similar to https://ui.shadcn.com/docs/installation/astro .. just replace `React` with `Vue`, and `shadcn-ui` to `shadcn-vue` should do the tricks 😁

Perhaps we could also include the steps in our docs

**Comment by selemondev** [comment]
May I be assigned to handle this issue, @zernonia ?

**Comment by sadeghbarati** [comment]
Thank You @selemondev 🤝
