### ISSUE TITLE
[Bug]: Tailwind tw-p-0 Class Not Removing Padding as Expected

### ISSUE THREAD

**Issue by Us3r-gitHub** [radix-vue/shadcn-vue#903]
### Reproduction

https://github.com/Us3r-gitHub/Playground-Nuxt

### Describe the bug

When setting the padding to zero using the Tailwind class [tw-p-0](https://github.com/Us3r-gitHub/Playground-Nuxt/blob/main/app/pages/index.vue#L3) (with a custom prefix tw-), the padding does not disappear as expected.

### Steps to Reproduce:
1. Apply the Tailwind padding class [tw-p-0](https://github.com/Us3r-gitHub/Playground-Nuxt/blob/main/app/pages/index.vue#L3).
2. Observe that the padding remains on the element, even though it should be removed.

### Expected Behavior:
The padding should be completely removed, meaning there should be no space around the content of the element.

### Actual Behavior:
The padding remains visible.

### Screenshot
![image](https://github.com/user-attachments/assets/42a6ffa0-9da9-453b-8627-333be5adf99c)

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 8.11 GB / 23.85 GB
  Binaries:
    Node: 20.16.0 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - E:\Program Files\nodejs\yarn.CMD
    npm: 10.8.1 - E:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - E:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.6 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.98)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    nuxt: ^3.14.159 => 3.14.159
    radix-vue: ^1.9.9 => 1.9.9
    shadcn-nuxt: ^0.11.2 => 0.11.2
    vue: latest => 3.5.12
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by Soviut** [comment]
This is due to class priority.

Either remove the other `tw-p-6 tw-pt-0`.

Or prefix your override class with `!` to add an `!important` flag to the style `!tw-p-0`.

You should this very sparingly, but in this situation it's probably fine.

**Comment by kikky7** [comment]
Use `cn` function, this is how css works,  not a bug.

**Comment by Us3r-gitHub** [comment]
> Use `cn` function, this is how css works, not a bug.

I’ve implemented the `cn` function as shown in the screenshot, but the padding still persists. Could you please advise if my implementation might be incorrect?
![image](https://github.com/user-attachments/assets/40ce7ae5-bd01-423e-a31d-40087d43d22d)

Any guidance would be greatly appreciated!

**Comment by Us3r-gitHub** [comment]
> Or prefix your override class with `!` to add an `!important` flag to the style `!tw-p-0`.

Thanks for the suggestion! Using `!` does work, but I prefer to avoid it if possible.

Appreciate your help!

**Comment by kratos-digital** [comment]
> > Use `cn` function, this is how css works, not a bug.
> 
> I’ve implemented the `cn` function as shown in the screenshot, but the padding still persists. Could you please advise if my implementation might be incorrect? ![image](https://private-user-images.githubusercontent.com/58467104/387028446-40ce7ae5-bd01-423e-a31d-40087d43d22d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTU1NjcsIm5iZiI6MTczMTg5NTI2NywicGF0aCI6Ii81ODQ2NzEwNC8zODcwMjg0NDYtNDBjZTdhZTUtYmQwMS00MjNlLWEzMWQtNDAwODdkNDNkMjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAyMDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYmU4Y2YxMjE1NmExMWY4MjUxNDU0YmJhN2Q1ODI2MjgwZjkwYTQ4ZWIzM2I2ODIyZDcxZjg3ODg0NmYzZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oTrtD-hEMjlUx9ZsgY1Ao_X-r1i6HZ-Ra6JvmEX1u6w)
> 
> Any guidance would be greatly appreciated!

Show me the CardContent component, you should implement cn there, not here

**Comment by kratos-digital** [comment]
Try this. You pass the prop `class` and merge it with default class which is `tw-p-6`.

`<CardContent class="tw-p-0">Card content</CardContent>`

CardContent.vue
```
<script setup lang="ts">
import { type HTMLAttributes } from "vue";
import { cn } from "@/lib/utils";

const props = defineProps<{
  class?: HTMLAttributes["class"];
}>();

<template>
  <div :class="cn('tw-p-6', props.class)"><slot /></div>
</template>
```

**Comment by Us3r-gitHub** [comment]
> Show me the CardContent component, you should implement cn there, not here

The component is generated from the Shadcn Vue CLI `npx shadcn-vue@latest add card`.
[CardContent](https://github.com/Us3r-gitHub/Playground-Nuxt/blob/main/app/components/ui/card/CardContent.vue#L3-L11).

Thanks again for your help!

**Comment by kratos-digital** [comment]
It's not working due the prefix, I never used prefix.

But try this then in `utils.ts`:

```
import { extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({ prefix: 'tw-' });

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
```

**Comment by Us3r-gitHub** [comment]
> It's not working due the prefix, I never used prefix.

Thanks for the clarification! Just to confirm, implementing the prefix will cause issues, correct?

> But try this then in `utils.ts`:

Thanks for the suggestion! I did try modifying utils.ts previously (for example, adding console.log to debug), but I didn’t see any changes or logs.

Could there be something I’m missing when overriding or modifying that file? Just to note, I’m using Nuxt in my setup.

Looking forward to your insights!

**Comment by kratos-digital** [comment]
No, you can use prefix, but you must extend the `twMerge` function with your prefix, as I gave the example. This function is core part of custom `cn` function and you must adjust it to your use case. When you don't use prefix, you can use it with default settings.

I didn't use it with Nuxt, but that shouldn't affect it at any way.

**Comment by Us3r-gitHub** [comment]
> you must extend the twMerge function with your prefix

Thanks for the clarification! It works when we extend the `twMerge` function with our prefix, but we can’t directly override the `utils.ts` file.

Would you recommend opening a new issue to address this, or should I update the current issue’s title to reflect the exact problem we’re facing now?

Appreciate your advice on this!

**Comment by sadeghbarati** [comment]
Hey guys, configuring prettier plugin for TailwindCSS might help resolve this issue

**Comment by Us3r-gitHub** [comment]
> Hey guys, configuring prettier plugin for TailwindCSS might help resolve this issue

Do you have a working example for this?

**Comment by sadeghbarati** [comment]
Sry I misunderstood the issue,

Check this StackOverflow link for using `tailwind-merge` with `tailwind` **prefix** option

https://stackoverflow.com/questions/77698720/does-tailwind-merge-work-with-prefixed-tailwind-classes
https://github.com/dcastil/tailwind-merge/blob/b499bcc14c2dd4e21c806704cf7548a642fc65ba/src/lib/types.ts#L13

**Comment by Us3r-gitHub** [comment]
Yup, as kratos [commented](https://github.com/unovue/shadcn-vue/issues/903#issuecomment-2481791489), it works by extending the twMerge function with a prefix (I tested it by hardcoding the file in .nuxt — an auto-generated file).

However, when I tried overriding the cn function in the utils.ts file, even though I edited the file, the changes didn't take effect in the application.

I'm just curious about this [code](https://github.com/unovue/shadcn-vue/blob/dev/packages/module/src/module.ts#L48).

**Comment by sadeghbarati** [comment]
`shadcn-nuxt` will be refactored soon, I'll contact Zernonia and see what the status of the `Next` PR is

Meanwhile, use the manual module way in the Nuxt installation
