### ISSUE TITLE
[Bug]: Can't add components after installation > ERROR  did not recognize object of type "TSInterfaceHeritage"

### ISSUE THREAD

**Issue by Clickadelic** [radix-vue/shadcn-vue#908]
### Reproduction

Follow the docs until step 9

### Describe the bug

I've followed each step of the installation guide under: https://www.shadcn-vue.com/docs/installation/vite

Terminal/Vite says everything went successfully after step number 8.

Step 9 on the docs:

When I'm trying to add a button with: npx shadcn-vue@latest add button

in order to verify that the installation worked / use the a component

I'm encountering the followin error:

Error: did not recognize object of type "TSInterfaceHeritage".

### System Info

```bash
Windows 11, VS-Code, Node version: v20.9.0
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by aphofstede** [comment]
Probably a duplicate of https://github.com/unovue/shadcn-vue/issues/905

**Comment by Clickadelic** [comment]
Yes, it's the same issue - So I guess I'll close this one, right?
