### ISSUE TITLE
[Feature]: Stepper Component

### ISSUE THREAD

**Issue by deleugpn** [radix-vue/shadcn-vue#92]
### Describe the feature

This is an amazing project and tackles precisely a part that seems to be missing with Vue.

I'd like to put a request for a Stepper component inspired by this one: https://mui.com/material-ui/react-stepper/#alternative-label

Hope some day someone can pick this up!

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by hrynevychroman** [comment]
This package just migrate original [shadcn](https://ui.shadcn.com/)  package to Vue 3 codebase, don't think that we will add some components that are not present in reference package 🙂

**Comment by sadeghbarati** [comment]
There is `primevue` stepper (unstyled) that you can use besides `radix-vue` cause both have tree-shaking capability

https://primevue.org/steps/#api.steps.props.unstyled


---

Also, you can write your own stepper with [radix-vue Tabs](https://www.radix-vue.com/components/tabs.html)

**Comment by mashpie** [comment]
stumbled upon https://shadcn-stepper.vercel.app today and wanted to share. Maybe helpful. They also open a PR to original shadcn.

**Comment by rainbowdog1** [comment]
> stumbled upon https://shadcn-stepper.vercel.app today and wanted to share. Maybe helpful. They also open a PR to original shadcn.

This would be awesome!

**Comment by sadeghbarati** [comment]
@epr3 Thanks for accepting this

**After v1.9 release ofc** or maybe we can continue work on it with `pkg.pr.new` 😄
