### ISSUE TITLE
[Bug]: following install steps for shadcn-vue on nuxt fails due to missing step in documentation

### ISSUE THREAD

**Issue by joelstephen97** [radix-vue/shadcn-vue#930]
### Reproduction

https://www.shadcn-vue.com/docs/installation/nuxt.html

### Describe the bug

Currently following the steps listed in https://www.shadcn-vue.com/docs/installation/nuxt.html

if you proceed to **step 4** 
```npx nuxi@latest module add shadcn-nuxt```
after **step 3** 
```npx nuxi@latest module add @nuxtjs/tailwindcss```

it will raise this error 
```ERROR  Nuxt module should be a function: @nuxtjs/color-mode   ```

There seems to be a new step that is required now
```npx nuxi@latest module add @nuxtjs/color-mode```

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 21.12 GB / 31.94 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.1 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.8 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vueuse/core: ^12.0.0 => 12.0.0
    nuxt: ^3.14.1592 => 3.14.1592
    radix-vue: ^1.9.10 => 1.9.10
    shadcn-nuxt: ^0.11.3 => 0.11.3
    vue: latest => 3.5.13
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by Us3r-gitHub** [comment]
related #864 #945

**Comment by joelstephen97** [comment]
Noted I think #945 has a good explanation as well regarding the issue.
