### ISSUE TITLE
[Bug]: Components and utils are not creating 

### ISSUE THREAD

**Issue by Masumrahmanhasan** [radix-vue/shadcn-vue#940]
### Reproduction

install latest nuxt and setup via docs

### Describe the bug

when using latest nuxt while setuping the shadcn-vue first error comes is @nuxtjs/color-mode related and then after manually installing this and then setup no components is install its always says 
✔ Component sidebar already exists. Would you like to overwrite? … yes
✔ Done.

### System Info

```bash
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 92.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.8.1 - ~/Library/Application Support/Herd/config/nvm/versions/node/v20.16.0/bin/npm
    pnpm: 9.14.4 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
  npmPackages:
    @vueuse/core: ^12.0.0 => 12.0.0 
    nuxt: ^3.14.1592 => 3.14.1592 
    radix-vue: ^1.9.10 => 1.9.10 
    shadcn-nuxt: 0.11.3 => 0.11.3 
    vue: latest => 3.5.13
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by ROVND** [comment]
![Snipaste_2024-12-09_15-04-23](https://github.com/user-attachments/assets/8a485e92-5637-4f91-a555-4d540bb188ce)
when running `npx shadcn-vue@latest init` in a nuxt3 project do not specify your own tsconfig.json path specify .nuxt/tsconfig.json.

**Comment by Masumrahmanhasan** [comment]
the docs needs to be updated

**Comment by sadeghbarati** [comment]
If you are using Nuxt and JS check this https://github.com/unovue/shadcn-vue/issues/291#issuecomment-1901788144, `components` and `utils` generated outside of the project directory



With new CLI implementation this issue and related issues will be resolved
