### ISSUE TITLE
[Bug]: Avatar doesn't show the image

### ISSUE THREAD

**Issue by dukenmarga** [radix-vue/shadcn-vue#946]
### Reproduction

https://stackblitz.com/edit/b68fb3fd?file=src%2FApp.vue

### Describe the bug

When directly copy the Avatar example from the doc, the image isn't shown properly. If we inspect the DOM, the image tag include this `style="display: none;"`

That's why it always shows the fallback instead of the avatar image.

Also, another question is how can we bind reactive variable to src tag? For example below code will only render the item.src and doesn't bind to the item object:
```
<AvatarImage src="item.src" />
```

I've tried combination like {{item.src}} and "{{item.src}}", but it won't render the variable value.

### System Info

```bash
System:
    OS: Linux 5.14 openSUSE Leap 15.5
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700F
    Memory: 16.26 GB / 31.20 GB
    Container: Yes
    Shell: 5.6 - /usr/bin/zsh
  Binaries:
    Node: 18.20.4 - /usr/bin/node
    npm: 10.7.0 - /usr/bin/npm
  Browsers:
    Brave Browser: 131.1.73.91
    Chrome: 131.0.6778.85
  npmPackages:
    @vueuse/core: ^12.0.0 => 12.0.0 
    radix-vue: ^1.9.10 => 1.9.10 
    vue: ^3.5.13 => 3.5.13
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by fabianbernhart** [comment]
There is no Bug?, The image url _https://github.com/radix-vue.png_ just redirects to the url  _https://avatars.githubusercontent.com/u/184213685?v=4_ so use the redirected url instead.

![grafik](https://github.com/user-attachments/assets/fbb10b00-8b3f-48e2-9f92-b193b6201bea)

**Comment by dukenmarga** [comment]
Aha, now I can understand the behavior. If the main image can't be loaded, the image tag display is set to hidden.
This case is also applied to my line where item.src is supposed show the url, but end up as plain text, which I don't know how to make it works.

```
<AvatarImage src="item.src" />
```

Do you know how to bind the variable to src?

**Comment by buihanh2304** [comment]
@dukenmarga do you know how to bind variable to Vue component?
```
<AvatarImage :src="item.src" />
```

**Comment by dukenmarga** [comment]
Yup, I've tried that, but I think something was wrong with my code and it didn't work. But, now it's working. Thank you all for your help.

I will close this issue.
