### ISSUE TITLE
[Bug]: Typo in tailwind classes

### ISSUE THREAD

**Issue by Gerbuuun** [radix-vue/shadcn-vue#96]
https://github.com/radix-vue/shadcn-vue/blob/223583b2171a898d9b875a53167f295d7f59062b/apps/www/src/lib/registry/default/ui/avatar/index.ts#L8C1-L8C1

`text-foregorund` should be `text-foreground`

**Comment by zernonia** [comment]
Thanks for logging this! Welcome to contribute ya 😁
