### ISSUE TITLE
[Bug]: initialValues of @vee-validate/zod does not work with <Form> from @/components/ui/form

### ISSUE THREAD

**Issue by AytoKyto** [radix-vue/shadcn-vue#967]
### Reproduction

.

### Describe the bug

**Description**:

### **Issue**
When using `@vee-validate/zod` with the `<Form>` component from `@/components/ui/form`, the `initialValues` provided to the form are not applied correctly to the input fields. However, when switching to a basic HTML `<form>` structure, the `initialValues` work as expected.

### **Steps to Reproduce**:
1. Use the `<Form>` component from `@/components/ui/form`.
2. Integrate `@vee-validate/zod` for form validation and provide an `initialValues` object.
3. Observe that the initial values are not rendered in the form inputs.
4. Replace `<Form>` with a standard HTML `<form>` element.
5. Notice that `initialValues` now work as expected.

### **Expected Behavior**:
The `initialValues` provided to the form should populate the input fields correctly, regardless of whether the form uses the `<Form>` wrapper component or a basic HTML `<form>`.

### **Actual Behavior**:
The `initialValues` do not work when using the `<Form>` component from `@/components/ui/form`.

### **Environment**:
- `vee-validate` version: [provide version]
- `zod` version: [provide version]
- UI library version: [if applicable]

#### **Using the `<Form>` Component:**

```vue
<template>
  <Form v-slot="{ values }">
    <Field name="email" as="input" type="text" />
  </Form>
</template>

<script setup>
import { Form, Field } from "@/components/ui/form";
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";

const schema = toTypedSchema(z.object({ email: z.string().email() }));
const { handleSubmit, setFieldValue } = useForm({
  validationSchema: schema,
  initialValues: { email: "test@example.com" },
});
</script>
```

#### **Using a Basic HTML Form (Works):**

```vue
<template>
  <form @submit="handleSubmit">
    <Field name="email" as="input" type="text" />
  </form>
</template>

<script setup>
import { Field, useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";

const schema = toTypedSchema(z.object({ email: z.string().email() }));
const { handleSubmit } = useForm({
  validationSchema: schema,
  initialValues: { email: "test@example.com" },
});
</script>
```

### **Additional Context**:
It seems there might be an issue with how the `<Form>` wrapper interacts with `@vee-validate/zod` or how it passes down `initialValues`. Let me know if additional details or a minimal reproduction repository is needed to debug further.

### System Info

```bash
.
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by classicalguss** [comment]
Is this really fixed? I got it as well. I'm following shadcn exact documentation on vee-validate
https://www.shadcn-vue.com/docs/forms/vee-validate

It all works, except for initial values. They do not show up, unless an error happens
