### ISSUE TITLE
[Bug]: CLI adds a double set of quotes when you add components without using css vars.

### ISSUE THREAD

**Issue by drobertson-dev** [radix-vue/shadcn-vue#98]
### Environment

```bash
Developement/Production OS: Mac OS 13.6
Node version: 18.18.0
Package manager: pnpm@8.8.0
Radix Vue version: 0.4.1
Shadcn Vue version: 0.3.2
Nuxt version: 3.7.4
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
```

### Link to minimal reproduction

The CLI wont install on code sandbox

### Steps to reproduce

Add shadcn-vue to Nuxt 3 via CLI without using css variables for styling.

### Describe the bug

When I add shadcn-vue to a Nuxt 3 project without using the css variables for styling it double quotes all of the imports.
it does a double quote " followed by a single quote ' the imports are not recoginized by the editor or nuxt. It also ignores whatever is in the components json file for the import alias 

import { SelectItemText, type SelectItemTextProps } from "'radix-vue'"
import { ChevronDownIcon } from "'@radix-icons/vue'"

Here is what it does with component creation

<script setup lang="ts">
import { cn } from "'@/lib/utils'"

const props = defineProps({
  class: {
    type: String,
    default: "''",
  },
})
</script>

<template>
  <div
    :class=""
      cn(
        "'rounded-xl border border-gray-200 bg-white text-gray-950 shadow' dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50",
        props.class,
      )
    ""
  >
    <slot />
  </div>
</template>

### Expected behavior

To follow the components.json config and to not double quote where it should have a single quote.

### Conext & Screenshots (if applicable)

Here is the config setup

<img width="445" alt="Screenshot 2023-10-02 at 5 45 59 PM" src="https://github.com/radix-vue/shadcn-vue/assets/85001306/609503bd-0a1b-41c9-a3b9-ff02b418518b">
<img width="571" alt="Screenshot 2023-10-02 at 5 44 58 PM" src="https://github.com/radix-vue/shadcn-vue/assets/85001306/c5189da2-c623-4eb3-b7ea-a20ab42bb541">

**Comment by sidis405** [comment]
@daver987 came here to bring up the same issue

**Comment by beejaz** [comment]
Linking with issue #74
