### ISSUE TITLE
[Bug]: DropdownMenuPortal doesnt include in Dropdown Component

### ISSUE THREAD

**Issue by sabiqhasby** [radix-vue/shadcn-vue#99]
### Environment

```bash
Developement/Production OS: Windows 11
Node version: 18.12.1
Package manager: yarn@1.22.19
Radix Vue version: 0.4.1
Shadcn Vue version: 0.3.0
Nuxt version: 3.7.4
CSS framework: tailwindcss@3.3.2
Client OS: Windows 11
Browser: Chrome 117.0.5938.149
```

### Link to minimal reproduction

https://www.shadcn-vue.com/docs/components/dropdown-menu.html

### Steps to reproduce

installation using 'npx shadcn-vue@latest add dropdown-menu'

### Describe the bug

Hello, I'm using Dropdown Menu component. 
I was trying to make sub menu content in Dropdown Menu.  I was following exactly like the Shadcn-vue Docs. But something is missing. There is no DropdownMenuPortal in installation. 

![image](https://github.com/radix-vue/shadcn-vue/assets/103761762/4396ef1d-3887-421b-9f8b-02f111961c81)

in Documentation Shadcn:
![image](https://github.com/radix-vue/shadcn-vue/assets/103761762/e10b8062-9a52-41c3-b16f-2141c8ad7786)

**Comment by zernonia** [comment]
It should be exported here right? directly from `radix-vue` 

![image](https://github.com/radix-vue/shadcn-vue/assets/59365435/1b59698c-c32c-4912-b36c-ec6f5c2ca063)

**Comment by sabiqhasby** [comment]
Finally, thanks @zernonia. 
Because I use autoimport from Nuxt. So DropdownMenuPortal need to import manually from '@/components/ui/dropdown-menu'.
